import os

Import('env')
app1env = env.Clone()

app1env.Replace(HEXAGON_IMAGE_ENTRY = '0x1e200000')

app1env.Replace(CRT = '${Q6_RTOS_LIBS}/crt1.o')
app1env.Replace(QDSP6OBJS3  = [
      '${Q6_RTOS_LIBS}/libqurt.a',
      '${QDSP6_RELEASE_LIB_DIR}/libc.a',
      '${QDSP6_RELEASE_LIB_DIR}/libqcc.a',
	  '${Q6_RTOS_LIBS}/libqurtcfs.a',
      '${Q6_RTOS_LIBS}/libqube_compat.a',
      '${Q6_RTOS_LIBS}/libtimer.a',
      '${Q6_RTOS_LIBS}/libposix.a',
      '${LIB_DSP_ROOT}/libqdsp.a'
   ])

app1obj = app1env.Object('${BUILD_DIR}/app1', Glob('*.c'))
app1elf = app1env.Program('${BUILD_DIR}/app1.elf', app1obj)

Return('app1elf')
