import os

Import('env')
app2env = env.Clone()

app2env.Replace(HEXAGON_IMAGE_ENTRY = '0x1e300000')

app2env.Replace(CRT = '${Q6_RTOS_LIBS}/crt1.o')
app2env.Replace(QDSP6OBJS3  = [
      '${Q6_RTOS_LIBS}/libqurt.a',
      '${QDSP6_RELEASE_LIB_DIR}/libc.a',
      '${QDSP6_RELEASE_LIB_DIR}/libqcc.a',
	  '${Q6_RTOS_LIBS}/libqurtcfs.a',
      '${Q6_RTOS_LIBS}/libqube_compat.a',
      '${Q6_RTOS_LIBS}/libtimer.a',
      '${Q6_RTOS_LIBS}/libposix.a',
      '${LIB_DSP_ROOT}/libqdsp.a'
   ])

app2obj = app2env.Object('${BUILD_DIR}/app2', Glob('*.c'))
app2elf = app2env.Program('${BUILD_DIR}/app2.elf', app2obj)

Return('app2elf')
