/*=======================================================================*//**
 * @file        qhsusb_log.h
 * @author:     shreyasr
 * @date        13-Mar-2012
 *
 * @brief       QHSUSB (Qualcomm High-Speed USB) Logging implementation.
 *
 * @details     This file contains the implementation of the APIs to be used by
 *              the boot Sahara downloader.
 *
 * @note        
 *
 *              Copyright 2012 Qualcomm Technologies Incorporated.
 *              All Rights Reserved.
 *              Qualcomm Confidential and Proprietary
 * 
*//*========================================================================*/


// ===========================================================================
// 
//                            EDIT HISTORY FOR FILE
//   This section contains comments describing changes made to the module.
//   Notice that changes are listed in reverse chronological order.
// 
// $Header: //components/rel/boot.bf/3.1.2.c3/boot_images/core/wiredconnectivity/qhsusb/inc/qhsusb_log.h#1 $ 
// $DateTime: 2015/09/01 00:30:35 $ $Author: pwbldsvc $
// 
// when         who        what, where, why
// --------   ---        ----------------------------------------------------------
// 06/13/12   shreyasr 		Initial revision
//
// ===========================================================================

#ifndef _QHSUSB_LOG__H_
#define _QHSUSB_LOG__H_

#include "comdef.h" 

#define QHSUSB_GENERIC_LOG_SIZE 256

/* This enumerated type must end with a suffix _LOG */
typedef enum
{
  QHSUSB_DEFAULT_LOG, /*The default log which will be used*/

  /*QHSUSB Generic Logging Terms like ep, direction*/
  QHSUSB_EP_NUMBER_LOG,
  QHSUSB_TRANSFER_DIRECTION_LOG,
  QHSUSB_TRANSFER_LENGTH_LOG,
  QHSUSB_TRANSFER_DONE_LOG,
  QHSUSB_SUBMIT_RX_URB_LOG,
  QHSUSB_POLL_BEGIN_LOG,
  QHSUSB_POLL_ENDED_LOG,
  QHSUSB_TRANSFER_OK_LOG,
  QHSUSB_TRANSFER_ACTIVE_LOG,
  QHSUSB_TRANSFER_ERROR_LOG,

  /*QHSUSB_AL_BULK_C Logs*/
  QHSUSB_AL_BULK_SETUP_TIMER_LOG,
  QHSUSB_AL_BULK_START_TIMER_LOG,
  QHSUSB_AL_BULK_STOP_TIMER_LOG,
  QHSUSB_AL_CHECK_TIMER_FOR_EXPIRY_LOG,
  QHSUSB_AL_BULK_ZLP_TIMER_EXPIRED_LOG,
  QHSUSB_AL_BULK_RECEIVE_ZLP_LOG,
  QHSUSB_AL_BULK_ZLP_ARRIVED_LOG,
  QHSUSB_AL_BULK_HANDLE_RX_ZLP_MODE_LOG,
  QHSUSB_AL_BULK_RX_COMPLETE_LOG,
  QHSUSB_AL_BULK_RX_CB_RX_DONE_LOG,
  QHSUSB_AL_BULK_RX_CB_SHORT_PACKET_LOG,
  QHSUSB_AL_BULK_RX_CB_NO_ZLP_BUT_SHORT_PACKET_LOG,
  QHSUSB_AL_BULK_RX_ZLP_COPY_LOG,
  QHSUSB_AL_BULK_RX_MORE_DATA_LOG,
  QHSUSB_AL_BULK_TX_COMPLETE_LOG,
  QHSUSB_AL_ENUM_COMPLETE_LOG,
  QHSUSB_AL_BULK_INIT_ENTRY_LOG,
  QHSUSB_AL_BULK_INIT_EXIT_LOG,
  QHSUSB_AL_BULK_POLL_ENTRY_LOG,
  QHSUSB_AL_BULK_POLL_EXIT_LOG,
  QHSUSB_AL_BULK_SHUTDOWN_LOG,
  QHSUSB_AL_BULK_RECEIVE_LOG,
  QHSUSB_AL_BULK_TRANSMIT_LOG,
  QHSUSB_AL_BULK_GET_MAX_PACKET_SIZE_LOG,
  QHSUSB_AL_BULK_GET_MAX_RAW_DATA_SIZE_LOG,
  QHSUSB_AL_BULK_SHORT_PACKET_RECVD_LOG,
  QHSUSB_AL_BULK_DATA_RECVD_INSTEAD_OF_ZLP_LOG,
  QHSUSB_AL_BULK_ERR_WRITE_LOG,

  /*QHSUSB_AL_CHG_C Logs*/
  HSU_BOOT_START_STACK_LOG,
  HSU_BOOT_STOP_STACK_LOG,
  HSU_BOOT_POLL_STACK_LOG,
  HSU_BOOT_POLL_STACK_RESULT_LOG,
  QHSUSB_AL_CHG_DO_CHARGE_SOURCE_DETECTION_LOG,
  QHSUSB_AL_CHG_IS_ENUMERATED_LOG,
  QHSUSB_AL_CHG_UPDATE_VID_PID_LOG,
  QHSUSB_AL_CHG_GET_VID_PID_LOG,
  HSU_BOOT_IS_BATTERY_WEAK_LOG,
  HSU_BOOT_IS_BATTERY_PRESENT_LOG,
  HSU_BOOT_IS_DC_CHARGER_PRESENT_LOG,
  HSU_BOOT_IS_USB_CHARGER_PRESENT_LOG,
  HSU_BOOT_SHUTDOWN_DEVICE_LOG,
  HSU_BOOT_ENABLE_USB_CHARGING_LOG,
  HSU_BOOT_ENABLE_HW_TRICKLE_CHARGING_LOG,
  HSU_BOOT_DO_ENUMERATION_LOG,
  HSU_BOOT_DO_BATTERY_CHARGING_LOG,
  HSU_BOOT_DETECT_CHARGE_SOURCE_LOG,
  HSU_BOOT_DO_CHARGE_SOURCE_DETECTION_LOG,
  HSU_BOOT_DISCONNECT_FROM_HOST_LOG,
  HSU_BOOT_GET_CHARGER_PORT_TYPE_LOG,

  /*QHSUSB_FD_CHG_C Logs*/
  CHG_NOTIFY_CB_LOG,
  HID_SETUP_LOG,
  QHSUSB_FD_CHG_INIT_LOG,
  QHSUSB_FD_CHG_SHUTDOWN_LOG,
  QHSUSB_FD_CHG_DETECT_CHARGER_TYPE_LOG,
  QHSUSB_FD_CHG_UPDATE_VID_PID_LOG,
  QHSUSB_FD_CHG_GET_VID_PID_LOG,
  QHSUSB_FLCB_ENUM_ALREADY_EXISTS_LOG,

  /*QHSUSB_FD_HDLC_C Logs*/
  HDLC_NOTIFY_CB_LOG,
  HDLC_TX_CALLBACK_LOG,
  HDLC_RX_CALLBACK_ACTUAL_LENGTH_LOG,
  HDLC_RX_CALLBACK_TRANSFER_LENGTH_LOG,
  QHSUSB_FD_HDLC_SET_CORE_LOG,
  QHSUSB_FD_HDLC_INIT_LOG,
  QHSUSB_FD_HDLC_SHUTDOWN_LOG,
  QHSUSB_FD_HDLC_TX_BYTE_LOG,
  QHSUSB_FD_HDLC_TX_PKT_LOG,
  QHSUSB_FD_HDLC_IS_TX_ACTIVE_LOG,
  QHSUSB_FD_HDLC_RX_PKT_LOG,
  QHSUSB_FD_HDLC_RX_COMPLETED_LOG,
  QHSUSB_FD_HDLC_UPDATE_VID_PID_LOG,
  QHSUSB_FD_HDLC_GET_VID_PID_LOG,
  HDLC_INIT_RX_INT_BUF_MODE_LOG,
  HDLC_RX_CALLBACK_INT_BUF_MODE_LOG,
  QHSUSB_FD_HDLC_RX_COMPLETED_INT_BUF_MODE_LOG,
  QHSUSB_FD_HDLC_TX_PKT_ZERO_ADDRESS_LOG,

  /*Mass Storage and SCSI Logs*/
  MS_SETUP_PACKET_HANDLER_LOG,
  QHSUSB_MS_INIT_LOG,
  UPDATE_MS_DEVICES_PARAMS_LOG,
  MS_INIT_RX_LOG,
  SET_MS_PACKET_SIZE_LOG,
  MS_TX_CB_LOG,
  MS_RX_CB_LOG,
  MS_RX_CB_CURR_STATUS_LOG,
  QHSUSB_FD_MS_INIT_LOG,
  QHSUSB_FD_MS_IS_TX_ACTIVE_LOG,
  HOTPLUG_INFO_INIT_LOG,
  QHSUSB_ITER_INIT_HOTPLUG_LUN_LOG,
  INIT_LUN_LOG,
  POLL_LUN_LOG,
  UPDATE_NEW_LUN_PARAMS_LOG,
  QHSUSB_FD_MS_SEND_REQUEST_LOG,
  QHSUSB_FD_MS_HOTPLUG_DEV_READ_LOG,
  QHSUSB_FD_MS_HOTPLUG_DEV_WRITE_LOG,
  QHSUSB_SCSI_FAIL_LOG,

  INIT_SCSI_PARAMS_LOG,
  STALL_MS_EPS_LOG,
  IS_CBW_VALID_LOG,
  HANDLE_NEW_CBW_LOG,
  HANDLE_SCSI_COMMAND_LOG,
  HANDLE_INQUIRY_LOG,
  HANDLE_READ_FORMAT_CAPACITY_LOG,
  HANDLE_READ_CAPACITY_LOG,
  HANDLE_MODE_SENSE_LOG,
  HANDLE_MODE_SELECT_LOG,
  HANDLE_REQUEST_SENSE_LOG,
  HANDLE_TEST_UNIT_READY_LOG,
  SENDING_CSW_LOG,
  UPDATE_CURRENT_XFER_PARAMS_LOG,
  HANDLE_READ_LOG,
  HANDLE_WRITE_LOG,
  HANDLE_MAINTENANCE_IN_LOG,
  WRITE_TO_EMMC_CARD_LOG,
  QHSUSB_WRITE_LAST_DATA_TO_EMMC_LOG,
  HANDLE_UNSUPPORTED_SCSI_CMD_LOG,

  DCI_SKIP_ENUMERATION_LOG,
  DCI_HANDLE_USB_RESET_LOG,
  QHSUSB_SINGLE_BOOT_ENUM_MAGIC_DL_LOG,
  QHSUSB_SINGLE_BOOT_ENUM_MAGIC_FLCB_LOG,
  QHSUSB_IS_BULK_MODE_IN_PROGRESS_LOG,
  USB_TEST_MODE_INVALID_LOG,

  QHSUSB_CHG_STATE_TYPE_OFFSET,
  QHSUSB_CHG_ST_START_LOG,
  QHSUSB_CHG_ST_BSESS_VALID_LOG,
  QHSUSB_CHG_ST_WAIT_FOR_DCD_LOG,
  QHSUSB_CHG_ST_WAIT_FOR_DP_LOW_LOG,
  QHSUSB_CHG_ST_SE1_ON_BSESS_VALID_LOG,
  QHSUSB_CHG_ST_DCD_SUCCESS_LOG,
  QHSUSB_CHG_ST_DCD_FAILURE_LOG,
  QHSUSB_CHG_ST_CHARGING_PORT_DETECTED_LOG,
  QHSUSB_CHG_ST_ACA_PORT_DETECTED_LOG,
  QHSUSB_CHG_ST_SDP_LOG,
  QHSUSB_CHG_ST_CDP_LOG,
  QHSUSB_CHG_ST_DCP_LOG,
  QHSUSB_CHG_ST_INVALID_CHARGER_LOG, 
  QHSUSB_CHG_ST_DONE_LOG,
  QHSUSB_CHG_ST_END_LOG,
  QHSUSB_CHARGER_TYPE_IS_LOG,

  /*USB Events Logs*/
  QHSUSB_USBSTS_URI_LOG,
  QHSUSB_USBSTS_SLI_LOG,
  QHSUSB_USBSTS_PCI_LOG,
  QHSUSB_USBSTS_SEI_LOG,
  QHSUSB_USBSTS_UEI_LOG,


  /*Charger code API Logs */
  QHSUSB_AL_GET_CHARGER_TYPE_FROM_PBL_INFO_LOG,
  QHSUSB_AL_CHG_GET_CHARGER_PORT_TYPE_LOG,
  QHSUSB_AL_CHG_ENUMERATE_USB_LOG,
  QHSUSB_AL_CHG_ENUMERATE_USB_SUCCESS_LOG,
  QHSUSB_AL_CHG_ENUMERATE_USB_FAILURE_LOG,
  QHSUSB_ENUM_POLL_OFFSET,
  HSU_BOOT_POLL_RESULT_ERROR_LOG, 	
  HSU_BOOT_POLL_RESULT_NO_NEW_EVENT_LOG,
  HSU_BOOT_POLL_RESULT_CONNECTED_TO_HOST_PC_LOG,	
  HSU_BOOT_POLL_RESULT_DISCONNECTED_LOG,	
  HSU_BOOT_POLL_RESULT_NOT_CONNECTED_LOG,	
  HSU_BOOT_POLL_RESULT_RESUMED_NOT_ENUMERATED_LOG,	
  HSU_BOOT_POLL_RESULT_ENUMERATED_LOG,	
  HSU_BOOT_POLL_RESULT_SUSPENDED_LOG,	
  HSU_BOOT_POLL_RESULT_ENUMERATED_100MA_LOG,	
  HSU_BOOT_POLL_RESULT_MAX_LOG,
  QHSUSB_CHARGER_TYPE_OFFSET,
  QHSUSB_CHARGER_PORT_SDP_LOG,
  QHSUSB_CHARGER_PORT_CDP_LOG,
  QHSUSB_CHARGER_PORT_DCP_LOG,
  QHSUSB_CHARGER_PORT_INVALID_LOG, 
  QHSUSB_CHARGER_PORT_UNKNOWN_LOG,
  QHSUSB_AL_CHG_INIT_LOG,
  QHSUSB_AL_CHG_DEINIT_LOG,
  QHSUSB_AL_CHG_DISCONNECT_FROM_HOST_LOG,

  /* Logs for Force download mode */
  QHSUSB_SKIP_PBL_DLOAD_LOG,
  QHSUSB_ENTER_PBL_DLOAD_LOG,
  QHSUSB_SKIP_PBL_DLOAD_OTG_CABLE_CONNECTED_LOG,
  QHSUSB_SKIP_PBL_DLOAD_VBUS_LOW_LOG,
  QHSUSB_PBL_DLOAD_FEATURE_DISABLED_LOG,

  /* Logs for Error handling */
  QHSUSB_CORE_ID_ERROR_LOG,
  QHSUSB_DETECT_ID_ERROR_LOG,
  QHSUSB_NULL_PTR_LOG,

}qhsusb_generic_log_enum;

typedef struct 
{
	uint32 tick;
	qhsusb_generic_log_enum id_0;
	uint32 param_0;
} qhsusb_generic_log_type;

void qhsusb_log_init(void);
void qhsusb_log(uint32 id_0, uint32 offset_0,uint32 param_0);

#endif

