#include "AEEStdDef.idl"

module apps {
   interface mem {
      long request_map(in long heapid, in uint32 ion_flags, in uint32 rflags, in uint32 vin, in int32 len, rout uint32 vapps, rout uint32 vadsp);
      long request_unmap(in uint32 vadsp, in int32 len);
   };
};

