#ifndef TDSL1_PROFILING_LOG_H
#define TDSL1_PROFILING_LOG_H

/*===========================================================================
                     T D S L1M L O G . H

DESCRIPTION
  This header file describes the Layer 1 L1M log packet definitions.

Copyright (c) 2001-2011 by Qualcomm Technologies, Inc.  All Rights Reserved.
===========================================================================*/

/* ==========================================================================
** Includes and Public Data Declarations
** ========================================================================*/

/* -----------------------------------------------------------------------
** Include Files
** ----------------------------------------------------------------------- */

#include "tdscdma_variation.h"
#include "log.h"
#include "log_codes.h"
#include "log_codes_tdscdma.h"

/*--------------------------------------------------------------------------
                 LOG PACKET: TDSCDMA_L1_L1M_PROFILING_RESULT_LOG_PACKET    
                 (LOG CODE: 0xD064)
                     
This log packet will contain the TD-SCDMA L1M's records of profiling timing. 
 
This log record is generated whenever L1M triggers profiling output.
--------------------------------------------------------------------------*/
#ifdef FEATURE_TDSCDMA_L1M_PROFILING_LOG_PACKET

#define TDSL1MLOG_MAX_TIMING_RECORD_NUM 100 /* temp */

#define TDSL1MLOG_PACKET_SOURCE_IND_BIT     29
#define TDSL1MLOG_PACKET_DRAW_FLOW_IND_BIT    28
#define TDSL1MLOG_PACKET_MODULE_STT_BIT       11
#define TDSL1MLOG_PACKET_LINE_END_TYPE_BIT    16
#define TDSL1MLOG_PACKET_LINE_TYPE_BIT        17
#define TDSL1MLOG_PACKET_DES_MODULE_STT_BIT   18
#define TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT   23

typedef enum
{
  TDSL1M_LOG_SOURE_L1_TASK      = 0,
  TDSL1M_LOG_SOURE_STMR_IRQ     = 1,
  TDSL1M_LOG_SOURE_TRM_CONTEXT  = 2,
  TDSL1M_LOG_SOURE_RRC_CONTEXT  = 3,
  TDSL1M_LOG_SOURE_RFSW_CONTEXT = 4,
  TDSL1M_LOG_SOURE_FW_IRQ       = 5,
  TDSL1M_LOG_SOURE_TDRM_IDV     = 6,
  TDSL1M_LOG_SOURE_NUM 
}tdsl1mlog_packet_source_type;

#define TDSL1MLOG_OUTPUT_ALL_SOURCE      ((1<<TDSL1M_LOG_SOURE_NUM)-1)

#define TDSL1MLOG_PACKET_MAX_PAYLOAD     (TDSL1MLOG_MAX_TIMING_RECORD_NUM*TDSL1M_LOG_SOURE_NUM)


typedef enum
{
  TDS_PROFILING_L1M_MODULE     = 0,
  TDS_PROFILING_DL_MODULE      = 1,
  TDS_PROFILING_UL_MODULE      = 2,
  TDS_PROFILING_HSDPA_MODULE   = 3,
  TDS_PROFILING_HSUPA_MODULE   = 4,
  TDS_PROFILING_SRCH_MODULE    = 5,
  TDS_PROFILING_STMR_MODULE    = 6,
  TDS_PROFILING_RRC_MODULE     = 7,
  TDS_PROFILING_MAC_MODULE     = 8,
  TDS_PROFILING_LSM_MODULE     = 9,
  TDS_PROFILING_SEQ_MODULE     = 10,
  TDS_PROFILING_LTE_MODULE     = 11,
  TDS_PROFILING_GSM_MODULE     = 12,
  TDS_PROFILING_FW_MODULE      = 13,
  TDS_PROFILING_TDRF_MODULE    = 14,
  TDS_PROFILING_MCPM_MODULE    = 15, 
  TDS_PROFILING_TRM_MODULE     = 16,
  TDS_PROFILING_CXM_MODULE     = 17,
  TDS_PROFILING_TDRM_MODULE    = 18,
  TDS_PROFILING_RXD_MODULE     = 19,
  TDS_PROFILING_RFSW_MODULE    = 20,  
  TDS_PROFILING_MODULE_NUM  
}tds_profiling_log_modules;

//context source bit define macro
#define TDSL1_PROF_ACT_SROUCE_L1_TASK    TDSL1M_LOG_SOURE_L1_TASK      << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SROUCE_STMR_IRQ   TDSL1M_LOG_SOURE_STMR_IRQ     << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SROUCE_TRM_TASK   TDSL1M_LOG_SOURE_TRM_CONTEXT  << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SROUCE_RRC_TASK   TDSL1M_LOG_SOURE_RRC_CONTEXT  << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SOURCE_RFSW_TASK  TDSL1M_LOG_SOURE_RFSW_CONTEXT << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SOURCE_FW_IRQ     TDSL1M_LOG_SOURE_FW_IRQ       << TDSL1MLOG_PACKET_SOURCE_IND_BIT
#define TDSL1_PROF_ACT_SOURCE_TDRM_IDV   TDSL1M_LOG_SOURE_TDRM_IDV     << TDSL1MLOG_PACKET_SOURCE_IND_BIT //c0000000

//line type bit define macro
#define TDSL1MLOG_PACKET_SOLID_LINE   (0<<TDSL1MLOG_PACKET_LINE_TYPE_BIT)
#define TDSL1MLOG_PACKET_DASH_LINE    (1<<TDSL1MLOG_PACKET_LINE_TYPE_BIT)

//line end bit define macro
#define TDSL1MLOG_PACKET_LINE_WI_ARROW   (0<<TDSL1MLOG_PACKET_LINE_END_TYPE_BIT)
#define TDSL1MLOG_PACKET_LINE_WO_ARROW   (1<<TDSL1MLOG_PACKET_LINE_END_TYPE_BIT)

//draw ind bit define macro
#define TDSL1MLOG_PACKET_NO_CALLFLOW     (1<<TDSL1MLOG_PACKET_LINE_END_TYPE_BIT)
#define TDSL1MLOG_PACKET_DRAW_CALLFLOW   (0<<TDSL1MLOG_PACKET_LINE_END_TYPE_BIT)

//module bit define macro
#define TDSL1_PROF_ACT_MODULE_L1M      (TDS_PROFILING_L1M_MODULE   << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_DL       (TDS_PROFILING_DL_MODULE    << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_ULR4     (TDS_PROFILING_UL_MODULE    << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_DPA      (TDS_PROFILING_HSDPA_MODULE << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_UPA      (TDS_PROFILING_HSUPA_MODULE << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_SRCH     (TDS_PROFILING_SRCH_MODULE  << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_STMR     (TDS_PROFILING_STMR_MODULE  << TDSL1MLOG_PACKET_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_MODULE_TDRM     (TDS_PROFILING_TDRM_MODULE  << TDSL1MLOG_PACKET_MODULE_STT_BIT)//9000
#define TDSL1_PROF_ACT_MODULE_RFSW     (TDS_PROFILING_RFSW_MODULE  << TDSL1MLOG_PACKET_MODULE_STT_BIT)

//module souce bit define macro
#define TDSL1_PROF_ACT_SRC_L1M         (TDS_PROFILING_L1M_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)//0
#define TDSL1_PROF_ACT_SRC_RRC         (TDS_PROFILING_RRC_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)//3800000
#define TDSL1_PROF_ACT_SRC_MAC         (TDS_PROFILING_MAC_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_LSM         (TDS_PROFILING_LSM_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_STMR        (TDS_PROFILING_STMR_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_SEQ         (TDS_PROFILING_SEQ_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_LTE         (TDS_PROFILING_LTE_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_GSM         (TDS_PROFILING_GSM_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_FW          (TDS_PROFILING_FW_MODULE    <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_TDRF        (TDS_PROFILING_TDRF_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_SRCH        (TDS_PROFILING_SRCH_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_DL          (TDS_PROFILING_DL_MODULE    <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_UL          (TDS_PROFILING_UL_MODULE    <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_DPA         (TDS_PROFILING_HSDPA_MODULE <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_UPA         (TDS_PROFILING_HSUPA_MODULE <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_MCPM        (TDS_PROFILING_MCPM_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_TDRM        (TDS_PROFILING_TDRM_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)//9000000
#define TDSL1_PROF_ACT_SRC_TRM         (TDS_PROFILING_TRM_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_RXD         (TDS_PROFILING_RXD_MODULE   <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_SRC_RFSW        (TDS_PROFILING_RFSW_MODULE  <<TDSL1MLOG_PACKET_SRC_MODULE_STT_BIT)

//module destination bit define macro
#define TDSL1_PROF_ACT_DES_L1M         (TDS_PROFILING_L1M_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_RRC         (TDS_PROFILING_RRC_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_MAC         (TDS_PROFILING_MAC_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_LSM         (TDS_PROFILING_LSM_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_STMR        (TDS_PROFILING_STMR_MODULE  <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_SEQ         (TDS_PROFILING_SEQ_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_LTE         (TDS_PROFILING_LTE_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_GSM         (TDS_PROFILING_GSM_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_FW          (TDS_PROFILING_FW_MODULE    <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_TDRF        (TDS_PROFILING_TDRF_MODULE  <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_SRCH        (TDS_PROFILING_SRCH_MODULE  <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_DL          (TDS_PROFILING_DL_MODULE    <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_UL          (TDS_PROFILING_UL_MODULE    <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_DPA         (TDS_PROFILING_HSDPA_MODULE <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_UPA         (TDS_PROFILING_HSUPA_MODULE <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_MCPM        (TDS_PROFILING_MCPM_MODULE  <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)
#define TDSL1_PROF_ACT_DES_TDRM        (TDS_PROFILING_TDRM_MODULE  <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)//480000
#define TDSL1_PROF_ACT_DES_TRM         (TDS_PROFILING_TRM_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)//400000
#define TDSL1_PROF_ACT_DES_RXD         (TDS_PROFILING_TRM_MODULE   <<TDSL1MLOG_PACKET_DES_MODULE_STT_BIT)

//l1m task action
#define TDSL1M_LOG_ACT_L1_TASK_INIT    TDSL1_PROF_ACT_SROUCE_L1_TASK  | TDSL1_PROF_ACT_MODULE_L1M
//l1m stmr evt action
#define TDSL1M_LOG_ACT_STMR_EVT_INIT   TDSL1_PROF_ACT_SROUCE_STMR_IRQ | TDSL1_PROF_ACT_MODULE_L1M

//other module to l1m action
#define TDSL1M_LOG_ACT_L1_TASK_RRC_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_RRC  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_MAC_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_MAC  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_LSM_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_LSM  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_SEQ  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_LTE_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_LTE  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_GSM_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_GSM  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_FW_L1M   TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_FW   | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_TDRF | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_SRCH | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_DL_L1M   TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_DL   | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_UL_L1M   TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_UL   | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_DPA_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_DPA  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_UPA_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_UPA  | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_MCPM_L1M TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_MCPM | TDSL1_PROF_ACT_DES_L1M

//l1m to other module actions
#define TDSL1M_LOG_ACT_L1_TASK_L1M_L1M  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_L1M
#define TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_TDRF
#define TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_MCPM
#define TDSL1M_LOG_ACT_L1_TASK_L1M_DL   TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_DL
#define TDSL1M_LOG_ACT_L1_TASK_L1M_UL   TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_UL
#define TDSL1M_LOG_ACT_L1_TASK_L1M_DPA  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_DPA
#define TDSL1M_LOG_ACT_L1_TASK_L1M_UPA  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_UPA
#define TDSL1M_LOG_ACT_L1_TASK_L1M_RRC  TDSL1M_LOG_ACT_L1_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M | TDSL1_PROF_ACT_DES_RRC

//stmr to stmr actions
#define TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR  TDSL1_PROF_ACT_SROUCE_STMR_IRQ | TDSL1_PROF_ACT_SRC_STMR | TDSL1_PROF_ACT_DES_STMR                                     

#define TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_RRC_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_MAC_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_MAC_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_LSM_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_LSM_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_LTE_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_GSM_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_FW_L1M   |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW (TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_DL_L1M   |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_UL_L1M   |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_DPA_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_DPA_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_UPA_L1M  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW (TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)

#define TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_DL_SOLID_ARROW    (TDSL1M_LOG_ACT_L1_TASK_L1M_DL   |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW    (TDSL1M_LOG_ACT_L1_TASK_L1M_UL   |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_DPA_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_L1M_DPA  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_UPA_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_L1M_UPA  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW  (TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_L1M_DASH_WO_ARROW (TDSL1M_LOG_ACT_L1_TASK_L1M_L1M  |TDSL1MLOG_PACKET_DASH_LINE  |TDSL1MLOG_PACKET_LINE_WO_ARROW)
#define TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW   (TDSL1M_LOG_ACT_L1_TASK_L1M_RRC  |TDSL1MLOG_PACKET_SOLID_LINE |TDSL1MLOG_PACKET_LINE_WI_ARROW)

#define TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW (TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR|TDSL1MLOG_PACKET_DASH_LINE|TDSL1MLOG_PACKET_LINE_WO_ARROW)


/*******************************************************************************************************Linjia: for UL R4*/
#define TDSULR4_LOG_ACT_TASK_INIT  TDSL1_PROF_ACT_SROUCE_L1_TASK | TDSL1_PROF_ACT_MODULE_ULR4
#define TDSULR4_LOG_ACT_EVT_INIT   TDSL1_PROF_ACT_SROUCE_STMR_IRQ| TDSL1_PROF_ACT_MODULE_ULR4
/*******************************************************************************************************************/

/*******************************************************************************************************Linjia: for UL R4*/
/*UL to other module*/
#define TDSULR4_LOG_ACT_TASK_UL_L1M  TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_L1M

#define TDSULR4_LOG_ACT_TASK_UL_FW   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_FW

#define TDSULR4_LOG_ACT_TASK_UL_RF   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_TDRF

 #define TDSULR4_LOG_ACT_TASK_UL_MCPM TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_MCPM

#define TDSULR4_LOG_ACT_TASK_UL_SEQ   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_SEQ

#define TDSULR4_LOG_ACT_TASK_UL_MAC   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_MAC

#define TDSULR4_LOG_ACT_TASK_UL_RRC   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_RRC
  
#define TDSULR4_LOG_ACT_TASK_UL_DL   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_DL

/*UL internal module*/
#define TDSULR4_LOG_ACT_TASK_UL_UL   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_UL | TDSL1_PROF_ACT_DES_UL

/*other modules to UL module*/
#define TDSULR4_LOG_ACT_TASK_L1M_UL  TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_L1M  | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_FW_UL   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_FW   | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_RF_UL   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_TDRF | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_MCPM_UL TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_MCPM | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_SEQ_UL   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_SEQ  | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_MAC_UL   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_MAC  | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_RRC_UL   TDSULR4_LOG_ACT_TASK_INIT| TDSL1_PROF_ACT_SRC_RRC  | TDSL1_PROF_ACT_DES_UL

#define TDSULR4_LOG_ACT_TASK_DL_UL   TDSULR4_LOG_ACT_TASK_INIT | TDSL1_PROF_ACT_SRC_DL   | TDSL1_PROF_ACT_DES_UL                                     

/*for UL event*/
#define TDSULR4_LOG_ACT_TASK_STMR_STMR  TDSULR4_LOG_ACT_TASK_INIT|TDSL1_PROF_ACT_SRC_STMR|TDSL1_PROF_ACT_DES_STMR                                     

/*******************************************************************************************************************/

/*******************************************************************************************************Linjia: for UL R4*/
#define TDSULR4_LOG_ACT_TASK_UL_L1M_SOLID_ARROW (TDSULR4_LOG_ACT_TASK_UL_L1M|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_FW|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_RF|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_MCPM_SOLID_ARROW (TDSULR4_LOG_ACT_TASK_UL_MCPM|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_SEQ_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_SEQ|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_MAC|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_L1M_SOLID_ARROW (TDSULR4_LOG_ACT_TASK_UL_L1M|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_RRC_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_RRC|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_UL_DL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_DL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)

#define TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_UL_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)

#define TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_L1M_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_FW_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_FW_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_RF_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_MCPM_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_MCPM_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_SEQ_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_SEQ_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_MAC_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_MAC_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_RRC_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_RRC_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDSULR4_LOG_ACT_TASK_DL_UL_SOLID_ARROW  (TDSULR4_LOG_ACT_TASK_DL_UL|TDSL1MLOG_PACKET_SOLID_LINE|TDSL1MLOG_PACKET_LINE_WI_ARROW)

#define TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW (TDSULR4_LOG_ACT_TASK_STMR_STMR|TDSL1MLOG_PACKET_DASH_LINE|TDSL1MLOG_PACKET_LINE_WO_ARROW)
/*******************************************************************************************************************/

/**********************************************TDRM********************************************************/
//tdrm act in different context
#define TDRM_LOG_ACT_L1_TASK    TDSL1_PROF_ACT_SROUCE_L1_TASK  | TDSL1_PROF_ACT_MODULE_TDRM
#define TDRM_LOG_ACT_TDRM_IDV   TDSL1_PROF_ACT_SOURCE_TDRM_IDV | TDSL1_PROF_ACT_MODULE_TDRM //c0009000
#define TDRM_LOG_ACT_TRM_TASK   TDSL1_PROF_ACT_SROUCE_TRM_TASK | TDSL1_PROF_ACT_MODULE_TDRM

//other module to tdrm
#define TDRM_LOG_ACT_L1_TASK_L1M_TDRM   TDRM_LOG_ACT_L1_TASK  | TDSL1_PROF_ACT_SRC_L1M  | TDSL1_PROF_ACT_DES_TDRM
#define TDRM_LOG_ACT_TRM_TASK_TRM_TDRM  TDRM_LOG_ACT_TRM_TASK | TDSL1_PROF_ACT_SRC_TRM  | TDSL1_PROF_ACT_DES_TDRM
#define TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM  TDRM_LOG_ACT_TDRM_IDV | TDSL1_PROF_ACT_SRC_L1M  | TDSL1_PROF_ACT_DES_TDRM  //c0489000
#define TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM  TDRM_LOG_ACT_TDRM_IDV | TDSL1_PROF_ACT_SRC_RRC  | TDSL1_PROF_ACT_DES_TDRM  //c3c89000

//tdrm to other module
#define TDRM_LOG_ACT_L1_TASK_TDRM_L1M   TDRM_LOG_ACT_L1_TASK  | TDSL1_PROF_ACT_SRC_TDRM | TDSL1_PROF_ACT_DES_L1M
#define TDRM_LOG_ACT_L1_TASK_TDRM_RRC   TDRM_LOG_ACT_L1_TASK  | TDSL1_PROF_ACT_SRC_TDRM | TDSL1_PROF_ACT_DES_RRC
#define TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM  TDRM_LOG_ACT_TDRM_IDV | TDSL1_PROF_ACT_SRC_TDRM | TDSL1_PROF_ACT_DES_TRM  //c9409000

//actions with solid arrow line
#define TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW  (TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW  (TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW  (TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW   (TDRM_LOG_ACT_L1_TASK_L1M_TDRM  |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_L1_TASK_TDRM_L1M_SOLID_ARROW   (TDRM_LOG_ACT_L1_TASK_TDRM_L1M  |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_L1_TASK_TDRM_RRC_SOLID_ARROW   (TDRM_LOG_ACT_L1_TASK_TDRM_RRC  |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)
#define TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW  (TDRM_LOG_ACT_TRM_TASK_TRM_TDRM |TDSL1MLOG_PACKET_SOLID_LINE | TDSL1MLOG_PACKET_LINE_WI_ARROW)

/********************************************end of TDRM****************************************************************/

typedef enum
{   
  /************************** Commands from RRC ***************************************/
  TDSL1M_LOG_ACT_CPHY_DEACTIVATE_REQ                          = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x2,
  TDSL1M_LOG_ACT_CPHY_STOP_TDSCDMA_MODE_REQ                   = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x4,
  TDSL1M_LOG_ACT_CPHY_START_TDSCDMA_MODE_REQ                  = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x6,
  TDSL1M_LOG_ACT_CPHY_SUSPEND_TDSCDMA_MODE_REQ                = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x8,
  TDSL1M_LOG_ACT_CPHY_RESUME_TDSCDMA_MODE_REQ                 = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0xA,
  TDSL1M_LOG_ACT_CPHY_FREQ_SCAN_REQ                           = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0xC,
  TDSL1M_LOG_ACT_CPHY_ACQ_REQ                                 = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0xE,
  TDSL1M_LOG_ACT_CPHY_CELL_PARM_REQ                           = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x10,
  TDSL1M_LOG_ACT_CPHY_SETUP_REQ                               = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x12,
  TDSL1M_LOG_ACT_CPHY_DRX_REQ                                 = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x14,
  TDSL1M_LOG_ACT_CPHY_CIPHERING_KEY_REQ                       = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x16,
  TDSL1M_LOG_ACT_CPHY_MEASUREMENT_REQ                         = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x18,
  TDSL1M_LOG_ACT_CPHY_CELL_SELECTION_REQ                      = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x1A,
  TDSL1M_LOG_ACT_CPHY_CELL_TRANSITION_REQ                     = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x1C,
  TDSL1M_LOG_ACT_CPHY_ACT_TIME_CANCEL_REQ                     = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x1E,
                                                                                           
  /* Commands from MAC */                                                                  
  TDSL1M_LOG_ACT_CPHY_UL_TX_CONTROL_REQ                       = TDSL1M_LOG_ACT_L1_TASK_MAC_L1M_SOLID_ARROW + 0x20,
  TDSL1M_LOG_ACT_CPHY_MAC_UL_CONFIG_CNF                       = TDSL1M_LOG_ACT_L1_TASK_MAC_L1M_SOLID_ARROW + 0x22,
  TDSL1M_LOG_ACT_CPHY_MAC_DL_CONFIG_CNF                       = TDSL1M_LOG_ACT_L1_TASK_MAC_L1M_SOLID_ARROW + 0x24,
  TDSL1M_LOG_ACT_CPHY_MAC_DL_CONFIG_AT_L1_FAIL_CNF            = TDSL1M_LOG_ACT_L1_TASK_MAC_L1M_SOLID_ARROW + 0x26,
                                                                                           
  /* Commands from LSM (Location Services Manager) */                                      
  TDSL1M_LOG_ACT_CPHY_LSM_TIMETAG_REQ                         = TDSL1M_LOG_ACT_L1_TASK_LSM_L1M_SOLID_ARROW + 0x28,
  TDSL1M_LOG_ACT_CPHY_LSM_CELL_MEAS_REQ                       = TDSL1M_LOG_ACT_L1_TASK_LSM_L1M_SOLID_ARROW + 0x2A,
  
  TDSL1M_LOG_ACT_CPHY_CELL_BAR_REQ                            = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x2C,
  TDSL1M_LOG_ACT_CPHY_UPD_DL_SYNC_PARMS                       = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x2E,
                                                                                           
  /* Commands for SIBS */                                                                  
  TDSL1M_LOG_ACT_CPHY_SIB_SCHED_CHANGE_IND                    = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x30,
                                                                                           
  TDSL1M_LOG_ACT_CPHY_GO_TO_SLEEP_IND                         = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x32,
                                                                                           
  /* MBMS related command and indication */                                                
  /* ----------------------------------- */                                                
                                                                                           
  /* MCCH DRX request */                                                                   
  TDSL1M_LOG_ACT_CPHY_MBMS_MCCH_DRX_REQ                       = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x34,
  /* MBMS IDLE request */                                                                  
  TDSL1M_LOG_ACT_CPHY_MBMS_IDLE_REQ                           = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x36,
  /* MBMS Preferred layer (FLC) request */                                                 
  TDSL1M_LOG_ACT_CPHY_MBMS_PL_PARM_REQ                        = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x38,
                                                                                           
  TDSL1M_LOG_ACT_CPHY_UPD_OTA_PARMS_IND                       = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x3A,
                                                                                           
  /* Commands from RRC */                                                                  
  /* Uplink Physical Channel Control */                                                    
  TDSL1M_LOG_ACT_CPHY_UL_PHY_CHANNEL_CTRL_REQ                 = TDSL1M_LOG_ACT_L1_TASK_RRC_L1M_SOLID_ARROW + 0x3C,
                                                                                           
  /* L1 internal command */                                                                
  TDSL1M_LOG_ACT_INTERNAL_SETUP_REQ_RESUME_AFTER_UL_RESYNC    = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0x3E,
  TDSL1M_LOG_ACT_INTERNAL_SETUP_REQ_RESUME_BHO_ACT_PLUS_8     = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0x40,
  /********************* end of EXT CMD ****************************/                      
  /************************** MSGR ***********************************/                    
#if defined(FEATURE_TDSCDMA_TO_LTE) && defined(FEATURE_TDSCDMA_ABSOLUTE_PRIORITY)          
  TDSL1M_LOG_ACT_LTE_CPHY_IRAT_MEAS_T2L_INIT_CNF              = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x42,
  TDSL1M_LOG_ACT_LTE_CPHY_IRAT_MEAS_T2L_SEARCH_CNF            = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x44,
  TDSL1M_LOG_ACT_LTE_CPHY_IRAT_MEAS_T2L_MEAS_CNF              = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x46,
  TDSL1M_LOG_ACT_LTE_CPHY_IRAT_MEAS_T2L_CLEANUP_CNF           = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x48,
  TDSL1M_LOG_ACT_LTE_CPHY_IRAT_MEAS_T2L_DEINIT_CNF            = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x4A,
#endif                                                                                     
  TDSL1M_LOG_ACT_GERAN_GL1_ACQ_RSP                            = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x4C,
  TDSL1M_LOG_ACT_GERAN_GL1_SCH_RSP                            = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x4E,
  TDSL1M_LOG_ACT_GERAN_GL1_MEAS_RSP                           = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x50,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_INIT_CMD                        = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x52,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_INIT_CMD                    = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x54,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_STOP_CMD                        = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x56,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_STOP_CMD                    = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x58,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_STARTUP_REQ                     = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x5A,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_ACQ_REQ                         = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x5C,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_MEAS_REQ                        = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x5E,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_ABORT_CMD                       = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x60,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_STARTUP_REQ                 = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x62,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_ACQ_REQ                     = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x64,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_MEAS_REQ                    = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x66,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_L2T_ABORT_CMD                   = TDSL1M_LOG_ACT_L1_TASK_LTE_L1M_SOLID_ARROW + 0x68,
  TDSL1M_LOG_ACT_TDSCDMA_IRAT_BUILD_RF_SCRIPTS_CMD            = TDSL1M_LOG_ACT_L1_TASK_GSM_L1M_SOLID_ARROW + 0x6A,
  /**************************** MSGR FW ***************************************/           
  TDSL1M_LOG_ACT_TDSCDMA_FW_STATE_CFG_RSP                     = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x6C,
  TDSL1M_LOG_ACT_TDSCDMA_FW_SRCH_GAP_DETECT_RSP               = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x6E,
  TDSL1M_LOG_ACT_TDSCDMA_FW_SRCH_SYNCDL_MIDAMBLE_DETECT_RSP   = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x70,
  TDSL1M_LOG_ACT_TDSCDMA_FW_MEASURE_ALL_RSCP_RSP              = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x72,
  TDSL1M_LOG_ACT_TDSCDMA_FW_MEASURE_RSCP_RSP                  = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x74,
  TDSL1M_LOG_ACT_TDSCDMA_FW_MEASURE_ISCP_RSP                  = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x76,
#ifdef FEATURE_JDS_OPT                                                                     
  TDSL1M_LOG_ACT_TDSCDMA_FW_TS0_CELL_RSP                      = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x78,
  TDSL1M_LOG_ACT_TDSCDMA_FW_NONTS0_CELL_RSP                   = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x7A,
#endif                                                                                     
  TDSL1M_LOG_ACT_TDSCDMA_FW_CELL_INFO_IND                     = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x7C,
                                                       
  TDSL1M_LOG_ACT_TDSCDMA_FW_SRCH_REACQ_RSP                    = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x7E,

  TDSL1M_LOG_ACT_TDSCDMA_FW_BATON_HANDOVER_RSP                = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x80,
  TDSL1M_LOG_ACT_TDSCDMA_FW_SRCH_POWER_SCAN_RSP               = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x82,
  TDSL1M_LOG_ACT_TDSCDMA_FW_ERROR_DETECTED_IND                = TDSL1M_LOG_ACT_L1_TASK_FW_L1M_SOLID_ARROW + 0x84,
  /********************************** MSGR RF **************************************/      
  TDSL1M_LOG_ACT_RF_TDSCDMA_ENTER_MODE_CNF                    = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x86,
  TDSL1M_LOG_ACT_RF_TDSCDMA_EXIT_MODE_CNF                     = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x88,
  TDSL1M_LOG_ACT_RF_TDSCDMA_ENABLE_RX_CNF                     = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x8A,
  TDSL1M_LOG_ACT_RF_TDSCDMA_ENABLE_TX_CNF                     = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x8C,
  TDSL1M_LOG_ACT_RF_TDSCDMA_DISABLE_TX_CNF                    = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x8E,
  TDSL1M_LOG_ACT_RF_TDSCDMA_SLEEP_CNF                         = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x90,
  TDSL1M_LOG_ACT_RF_TDSCDMA_WAKEUP_CNF                        = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x92,
  TDSL1M_LOG_ACT_RF_TDSCDMA_UPDATE_TDS_NBR_CNF                = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x94,
  TDSL1M_LOG_ACT_RF_TDSCDMA_UPDATE_BHO_CNF                    = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x96,
  TDSL1M_LOG_ACT_RF_TDSCDMA_SWITCH_BUF_CNF                    = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x98,
  TDSL1M_LOG_ACT_RF_TDSCDMA_GET_MAX_TX_PWR_CNF                = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x9A,
  TDSL1M_LOG_ACT_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF              = TDSL1M_LOG_ACT_L1_TASK_TDRF_L1M_SOLID_ARROW + 0x9C,
  
  /*************************************** important LOCAL CMD **********************************/
  TDSL1M_LOG_ACT_SRCH_DONE_CMD                                = TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW + 0x9E,
  TDSL1M_LOG_ACT_SEQ_ALIGN_CELL_TRANS_DONE                    = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0xA0,
  TDSL1M_LOG_ACT_DL_CELL_TRANS_DROP_DONE_CMD                  = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xA2,
  TDSL1M_LOG_ACT_ACT_TIME_CMD                                 = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0xA4,
  TDSL1M_LOG_ACT_L1_CHANNEL_SETUP_START                       = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0xA6,
  TDSL1M_LOG_ACT_DL_CCTRCH_SETUP_DONE_CMD                     = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xA8,
  TDSL1M_LOG_ACT_UL_PHYCHAN_DROP_DONE_CMD                     = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xAA,
  TDSL1M_LOG_ACT_DL_PHYCHAN_DROP_DONE_CMD                     = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xAC,
  TDSL1M_LOG_ACT_DL_PHYCHAN_ADD_DONE_CMD                      = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xAE,
  TDSL1M_LOG_ACT_UL_RACH_DONE_CMD                             = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xB0,
  TDSL1M_LOG_ACT_UL_CCTRCH_SETUP_DONE_CMD                     = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xB2,
  TDSL1M_LOG_ACT_UL_PHYCHAN_CFG_DONE_CMD                      = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xB4,
  TDSL1M_LOG_ACT_DL_PHYCHAN_CFG_DONE_CMD                      = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xB6,
  TDSL1M_LOG_ACT_UL_PHYCHAN_ADD_DONE_CMD                      = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xB8,
  TDSL1M_LOG_ACT_UL_DL_PHYCHAN_DROP_DONE_CMD                  = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xBA,
  TDSL1M_LOG_ACT_UL_HHO_RESYNC_SUCCESS_IND_CMD                = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xBC,
#ifdef FEATURE_TDSCDMA_HSUPA                                                               
  TDSL1M_LOG_ACT_E_DL_PHYCHAN_DONE_CMD                        = TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW + 0xBE,  
  TDSL1M_LOG_ACT_E_UL_PHYCHAN_DONE_CMD                        = TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW + 0xC0,
  TDSL1M_LOG_ACT_NON_SCHED_GRANT_CFG_DONE_CMD                 = TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW + 0xC2,
#endif                                                                                     
  TDSL1M_LOG_ACT_L1_HS_CHAN_CFG_DONE                          = TDSL1M_LOG_ACT_L1_TASK_DPA_L1M_SOLID_ARROW + 0xC4,
  TDSL1M_LOG_ACT_L1_PHYCHAN_NOOP_DONE_CMD                     = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xC6,
  TDSL1M_LOG_ACT_DL_PCCPCH_WEAK_IND_CMD                       = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xC8,
  TDSL1M_LOG_ACT_DL_ACQ_BCH_DECODE_DONE_CMD                   = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xCA,

  TDSL1M_LOG_ACT_ALL_MODULE_CLEANUP_DONE_CMD                 = TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW + 0xCC,

  TDSL1M_LOG_ACT_MODULE_DROP_DONE_CMD                         = TDSL1M_LOG_ACT_L1_TASK_L1M_L1M_DASH_WO_ARROW + 0xCE,
  TDSL1M_LOG_ACT_UL_HHO_RESYNC_FAIL_IND_CMD                   = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0xD0,
  TDSL1M_LOG_ACT_L1_CELL_CHANGE_IND_CMD                       = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xD2,
  TDSL1M_LOG_ACT_L1_FACH_RACH_RESUME_DONE_IND_CMD             = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0xD4,
/**************************************** lOCAL CMD END ***************************************/  
/****************************************L1 RF ACTION **********************************************/
   TDSL1M_LOG_ACT_RF_CFG_RXLM_MODE                            = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xD6,
   TDSL1M_LOG_ACT_RF_CFG_TXLM_MODE                            = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xD8,
   TDSL1M_LOG_ACT_RF_DISABLE_RF_AND_EXIT_MODE                 = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xDA,
   TDSL1M_LOG_ACT_RF_DISABLE_TX                               = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xDC,
   TDSL1M_LOG_ACT_RF_ENABLE_RF_AND_ENTER_MODE                 = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xDE,
   TDSL1M_LOG_ACT_RF_ENABLE_TX                                = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xE0,
   TDSL1M_LOG_ACT_RF_SEND_FW_RX_CONFIG                        = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xE2,
   TDSL1M_LOG_ACT_RF_SEND_UPDATE_BHO_REQ                      = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xE4,
   TDSL1M_LOG_ACT_RF_SET_TX_POWER_LIMIT                       = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xE6,
   TDSL1M_LOG_ACT_RF_SLEEP                                    = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xE8,
   TDSL1M_LOG_ACT_RF_SWITCH_BUFF                              = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xEA,
   TDSL1M_LOG_ACT_RF_THERM_BACKOFF                            = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xEC,
   TDSL1M_LOG_ACT_RF_TUNE_TO_CHAN                             = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xEE,
   TDSL1M_LOG_ACT_RF_TUNE_TO_CHAN_WITH_MODE                   = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xF0,
   TDSL1M_LOG_ACT_RF_UPDATE_HS_CFG                            = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xF2,
   TDSL1M_LOG_ACT_RF_UPDATE_IFREQ_NBR_LIST                    = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xF4,
   TDSL1M_LOG_ACT_RF_WAKEUP                                   = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0xF6,
/****************************************L1 RF ACTION END**********************************************/   
/****************************************MCPM ACTION **************************************************/
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_STACK_ACTIVE         = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0xF8,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_ACQ_ACTIVE           = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0xFA,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_IDLE_OR_DL_ACTIVE    = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0xFC,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_WAKE_UP              = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0xFE,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_T2G                  = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x100,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_T2L                  = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x102,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_UL_ACTIVE            = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x104,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_HSDPA                = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x106,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_HSUPA                = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x108,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_TURBO                = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x10A,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_GOTO_SLEEP           = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x10C,
   TDSL1M_LOG_ACT_MCPM_REQUEST_POWER_FOR_RXD                  = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x10E,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_STACK_ACTIVE      = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x110,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_ACQ_ACTIVE        = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x112,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_IDLE_OR_DL_ACTIVE = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x114,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_WAKE_UP           = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x116,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_T2G               = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x118,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_T2L               = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x11A,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_UL_ACTIVE         = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x11C,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_HSDPA             = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x11E,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_HSUPA             = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x120,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_TURBO             = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x122,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_GOTO_SLEEP        = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x124,
   TDSL1M_LOG_ACT_MCPM_RELINQUISH_POWER_FOR_RXD               = TDSL1M_LOG_ACT_L1_TASK_L1M_MCPM_SOLID_ARROW + 0x126,

/****************************************MCPM ACTION end**************************************************/   
/****************************************UL/DL ACTION**************************************************/      
   TDSL1M_LOG_ACT_DROP_DPA_CHAN                               = TDSL1M_LOG_ACT_L1_TASK_L1M_DPA_SOLID_ARROW + 0x128,
   TDSL1M_LOG_ACT_DROP_PRACH_CHAN                             = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x12A,
   TDSL1M_LOG_ACT_DROP_DL_PHYCHAN                             = TDSL1M_LOG_ACT_L1_TASK_L1M_DL_SOLID_ARROW + 0x12C,
   TDSL1M_LOG_ACT_DROP_UL_PHYCHAN                             = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x12E,
   TDSL1M_LOG_ACT_SETUP_DL_CCTRCH                             = TDSL1M_LOG_ACT_L1_TASK_L1M_DL_SOLID_ARROW + 0x130,
   TDSL1M_LOG_ACT_SETUP_UL_CCTRCH                             = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x132,
   TDSL1M_LOG_ACT_ADD_DL_PHYCHAN                              = TDSL1M_LOG_ACT_L1_TASK_L1M_DL_SOLID_ARROW + 0x134,
   TDSL1M_LOG_ACT_ADD_UL_PHYCHAN                              = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x136,
   TDSL1M_LOG_ACT_DL_RECFG_PHYCHAN                            = TDSL1M_LOG_ACT_L1_TASK_L1M_DL_SOLID_ARROW + 0x138,
   TDSL1M_LOG_ACT_UL_RECFG_PHYCHAN                            = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x13A,
   TDSL1M_LOG_ACT_HSDPA_PHYCHAN_CFG                           = TDSL1M_LOG_ACT_L1_TASK_L1M_DPA_SOLID_ARROW + 0x13C,
   TDSL1M_LOG_ACT_HSUPA_EDL_PHYCHAN_CFG                       = TDSL1M_LOG_ACT_L1_TASK_L1M_UPA_SOLID_ARROW + 0x13E,
   TDSL1M_LOG_ACT_HSUPA_EUL_PHYCHAN_CFG                       = TDSL1M_LOG_ACT_L1_TASK_L1M_UPA_SOLID_ARROW + 0x140,
   TDSL1M_LOG_ACT_HSUPA_NONSCH_PHYCHAN_CFG                    = TDSL1M_LOG_ACT_L1_TASK_L1M_UPA_SOLID_ARROW + 0x142,
   TDSL1M_LOG_ACT_SUSPEND_RACH                                = TDSL1M_LOG_ACT_L1_TASK_L1M_UL_SOLID_ARROW + 0x144,

/****************************************UL/DL ACTION end**************************************************/
   TDSL1M_LOG_ACT_RF_GET_RF_TXCHAIN_NO                        = TDSL1M_LOG_ACT_L1_TASK_L1M_TDRF_SOLID_ARROW + 0x146,
   
//module cleanup done  
  TDSL1M_LOG_ACT_SRCH_MODULE_CLEANUP_DONE_CMD                 = TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW + 0x148,
  TDSL1M_LOG_ACT_DL_MODULE_CLEANUP_DONE_CMD                   = TDSL1M_LOG_ACT_L1_TASK_DL_L1M_SOLID_ARROW + 0x14A,
  TDSL1M_LOG_ACT_UL_MODULE_CLEANUP_DONE_CMD                   = TDSL1M_LOG_ACT_L1_TASK_UL_L1M_SOLID_ARROW + 0x14C,
  TDSL1M_LOG_ACT_SEQ_MODULE_CLEANUP_DONE_CMD                  = TDSL1M_LOG_ACT_L1_TASK_SEQ_L1M_SOLID_ARROW + 0x14E,
  TDSL1M_LOG_ACT_HS_MODULE_CLEANUP_DONE_CMD                   = TDSL1M_LOG_ACT_L1_TASK_DPA_L1M_SOLID_ARROW + 0x150,  
#ifdef FEATURE_TDSCDMA_HSUPA
  TDSL1M_LOG_ACT_EDL_MODULE_CLEANUP_DONE_CMD                  = TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW + 0x152,
  TDSL1M_LOG_ACT_EUL_MODULE_CLEANUP_DONE_CMD                  = TDSL1M_LOG_ACT_L1_TASK_UPA_L1M_SOLID_ARROW + 0x154,
#endif  
#if defined(FEATURE_TDSCDMA_IDLEINTERVAL_INFO_SUPPORT) || defined(FEATURE_TDSCDMA_DMO_SUPPORT)
  TDSL1M_LOG_ACT_GAPMGR_MODULE_CLEANUP_DONE_CMD               = TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW + 0x156,
  TDSL1M_LOG_ACT_T2L_CM_MEAS_MODULE_CLEANUP_DONE_CMD          = TDSL1M_LOG_ACT_L1_TASK_SRCH_L1M_SOLID_ARROW + 0x158,
#endif

  /********************* EXT CNF ****************************/
  TDSL1M_LOG_ACT_CPHY_ACQ_CNF                                 = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x15A,                                                   
  TDSL1M_LOG_ACT_CPHY_SETUP_CNF                               = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x15C,                                                              
  TDSL1M_LOG_ACT_CPHY_ERROR_IND                               = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x15E,                                                              
  TDSL1M_LOG_ACT_CPHY_IDLE_CNF                                = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x160,                                                              
  TDSL1M_LOG_ACT_CPHY_CELL_SELECTION_CNF                      = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x162,                                                              
  TDSL1M_LOG_ACT_CPHY_CELL_RESELECTION_IND                    = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x164,                                                              
  TDSL1M_LOG_ACT_CPHY_MEASUREMENT_IND                         = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x166,                                                              
  TDSL1M_LOG_ACT_CPHY_PHYCHAN_ESTABLISHED_IND                 = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x168,                                                              
  TDSL1M_LOG_ACT_CPHY_IN_SYNC_IND                             = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x16A,                                                              
  TDSL1M_LOG_ACT_CPHY_OUT_OF_SYNC_IND                         = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x16C,                                                              
  TDSL1M_LOG_ACT_CPHY_RL_FAILURE_IND                          = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x16E,                                                              
  TDSL1M_LOG_ACT_CPHY_CELL_TRANSITION_CNF                     = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x170,                                                              
  TDSL1M_LOG_ACT_CPHY_FREQ_SCAN_CNF                           = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x172,                                                              
  TDSL1M_LOG_ACT_CPHY_DRX_CNF                                 = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x174,                                                              
  TDSL1M_LOG_ACT_CPHY_OUT_OF_SERVICE_AREA_IND                 = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x176,                                                              
  TDSL1M_LOG_ACT_CPHY_DEACTIVATE_CNF                          = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x178,                                                              
  TDSL1M_LOG_ACT_CPHY_MEAS_CTRL_CNF                           = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x17A,                                                              
  TDSL1M_LOG_ACT_CPHY_ACT_CANCEL_CNF                          = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x17C,                                                              
  TDSL1M_LOG_ACT_CPHY_START_TDS_MODE_CNF                      = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x17E,                                                              
  TDSL1M_LOG_ACT_CPHY_STOP_TDS_MODE_CNF                       = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x180,                                                              
  TDSL1M_LOG_ACT_CPHY_SUSPEND_TDS_MODE_CNF                    = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x182,                                                              
  TDSL1M_LOG_ACT_CPHY_RESUME_TDS_MODE_CNF                     = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x184,                                                              
  TDSL1M_LOG_ACT_CPHY_COMPRESSED_MODE_IND                     = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x186,                                                              
  TDSL1M_LOG_ACT_CPHY_DL_WEAK_IND                             = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x188,                                                              
  TDSL1M_LOG_ACT_CPHY_ACTIVATION_TIME_IND                     = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x18A,                                                             
#ifdef FEATURE_TDSCDMA_FREE_FLOATING_TASK                                                              
  TDSL1M_LOG_ACT_CPHY_DATA_FOR_UI_DISP_CNF                    = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x18C,                                                              
  TDSL1M_LOG_ACT_CPHY_RSSI_CNF                                = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x18E,                                                              
  TDSL1M_LOG_ACT_CPHY_CHECK_S_CRIT_CNF                        = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x190,                                                              
  TDSL1M_LOG_ACT_CPHY_CHECK_SLEEP_REQ                         = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x192,                                                              
  TDSL1M_LOG_ACT_CPHY_GET_IMM_MEAS_RSP                        = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x194,                                                              
  TDSL1M_LOG_ACT_CPHY_UTRAN_NMR_INFO_CNF                      = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x196,                                                              
  TDSL1M_LOG_ACT_CPHY_ADDITIONAL_MEAS_DATA_RSP                = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x198,                                                              
  TDSL1M_LOG_ACT_CPHY_NUDGE_FOR_SFN_MISS_MATCH_REQ            = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x19A,                                                              
  TDSL1M_LOG_ACT_CPHY_MODEM_STATISTICS_RSP                    = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x19C,                                                              
#endif                                                              
#ifdef FEATURE_TDSCDMA_DSDS_QTA /*FEATURE_QTA*/               
  TDSL1M_LOG_ACT_CPHY_START_QTA_CNF                           = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0x19E,
  TDSL1M_LOG_ACT_CPHY_STOP_QTA_CNF                            = TDSL1M_LOG_ACT_L1_TASK_L1M_RRC_SOLID_ARROW + 0X200,
#endif
   /********************* end of EXT CNF ****************************/

/****************************************L1 EVENT  **********************************************/
   TDSL1M_LOG_ACT_SEQ_SFN_CFN_UPDATE_EVENT_START              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x0,
   TDSL1M_LOG_ACT_SEQ_SFN_CFN_UPDATE_EVENT_END                = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1,
   TDSL1M_LOG_ACT_SEQ_CHNL_SETUP_EVENT_START                  = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x2,
   TDSL1M_LOG_ACT_SEQ_CHNL_SETUP_EVENT_END                    = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x3,                                             
   TDSL1M_LOG_ACT_SEQ_RXD_STATE_UPDATE_EVENT_START            = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x4,
   TDSL1M_LOG_ACT_SEQ_RXD_STATE_UPDATE_EVENT_END              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x5,
   TDSL1M_LOG_ACT_SEQ_TX_HSUPA_EDCH_EVENT_START               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x6,
   TDSL1M_LOG_ACT_SEQ_TX_HSUPA_EDCH_EVENT_END                 = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x7,
   TDSL1M_LOG_ACT_SEQ_RX_GEN_SRCH_HB_EVENT_START              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x8,
   TDSL1M_LOG_ACT_SEQ_RX_GEN_SRCH_HB_EVENT_END                = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x9,
   //TDSL1M_LOG_ACT_SEQ_RX_DL_SCHEDULER_EVENT_START           = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xA,
   //TDSL1M_LOG_ACT_SEQ_RX_DL_SCHEDULER_EVENT_END               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xB,
   TDSL1M_LOG_ACT_SEQ_RX_GEN_DL_MAINT_EVENT_START             = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xC,
   TDSL1M_LOG_ACT_SEQ_RX_GEN_DL_MAINT_EVENT_END               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xD,
   TDSL1M_LOG_ACT_SEQ_TX_GEN_GET_DATA_EVENT_START             = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xE,
   TDSL1M_LOG_ACT_SEQ_TX_GEN_GET_DATA_EVENT_END               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0xF,
   TDSL1M_LOG_ACT_SEQ_GSM_MEAS_SCHED_EVENT_START              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x10,
   TDSL1M_LOG_ACT_SEQ_GSM_MEAS_SCHED_EVENT_END                = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x11,
   TDSL1M_LOG_ACT_SEQ_RX_READ_SHARED_MEMORY_EVENT_START       = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x12,
   TDSL1M_LOG_ACT_SEQ_RX_READ_SHARED_MEMORY_EVENT_END         = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x13,
   TDSL1M_LOG_ACT_SEQ_RX_DPA_DEC_MAINT_EVENT_START            = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x14,
   TDSL1M_LOG_ACT_SEQ_RX_DPA_DEC_MAINT_EVENT_END              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x15,
   TDSL1M_LOG_ACT_SEQ_RX_TIME_ADJUST_EVENT_START              = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x16,
   TDSL1M_LOG_ACT_SEQ_RX_TIME_ADJUST_EVENT_END                = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x17,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_1_START                   = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x18,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_1_END                     = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x19,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_2_START                   = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1A,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_2_END                     = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1B,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_3_START                   = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1C,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_3_END                     = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1D,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_4_START                   = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1E,
   TDSL1M_LOG_ACT_SEQ_RUNTIME_EVENT_4_END                     = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x1F,
   TDSL1M_LOG_ACT_TIMER_SYNC_USTMR                            = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x20,
   TDSL1M_LOG_ACT_TIMER_SYNC_RXSTMR                           = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x22,
   TDSL1M_LOG_ACT_TDSSTMR_RXTIME_INT_ISR_START                = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x24,
   TDSL1M_LOG_ACT_TDSSTMR_RXTIME_INT_ISR_END                  = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x25,
   TDSL1M_LOG_ACT_SEQ_MCVS_CTRL_EVENT_TS6_START               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x26,
   TDSL1M_LOG_ACT_SEQ_MCVS_CTRL_EVENT_TS6_END                 = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x27,
   TDSL1M_LOG_ACT_SEQ_FW_TIMESLOT_SUSPEND_EVENT_START         = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x28,
   TDSL1M_LOG_ACT_SEQ_FW_TIMESLOT_SUSPEND_EVENT_END           = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x29,   
   TDSL1M_LOG_ACT_SEQ_MCVS_CTRL_EVENT_TS2_START               = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x2A,
   TDSL1M_LOG_ACT_SEQ_MCVS_CTRL_EVENT_TS2_END                 = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x2B,   
   TDSL1M_LOG_ACT_SEQ_TX_HSUPA_A2_START                       = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x2C, 
   TDSL1M_LOG_ACT_SEQ_TX_HSUPA_A2_END                         = TDSL1M_LOG_ACT_STMR_EVT_STMR_STMR_DASH_WO_ARROW + 0x2D,
/****************************************L1 EVENT END**********************************************/       

   /*************************************************UL R4 profiling actions*******************************************\*/
   //tdsrf_cfg_wav_mk
   TDSULR4_LOG_ACT_UL_FW_RF_CFG_WAV_MK                           = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x2,
   //tdsenc_common_update_vpe_lmem_map
   TDSULR4_LOG_ACT_UL_FW_ENC_UPDATE_VPE_LMEM_MAP                 = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x4,
   //TRAMP_TDSENC_CMD_DONE_INT_IRQ Registration
   TDSULR4_LOG_ACT_UL_UL_TRAMP_ENC_CMD_DONE_INT_IRQ_REG          = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x6,
   //tdsulcmd_phychan_add_cmd
   TDSULR4_LOG_ACT_L1M_UL_CPHY_ADD_CMD                           = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x8,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_REQ
   TDSULR4_LOG_ACT_UL_RF_RFA_SET_TX_PWR_LIMIT_REQ                = TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW + 0x10,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF
   TDSULR4_LOG_ACT_UL_RF_RFA_SET_TX_PWR_LIMIT_CNF                = TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW + 0x12,
   //mcaltds_mcpmdrv_request_power_config
   TDSULR4_LOG_ACT_UL_MCPM_DRV_REQ_PWR_CFG                       = TDSULR4_LOG_ACT_TASK_UL_MCPM_SOLID_ARROW + 0x14,
   //TDSCDMA_FW_TX_HW_BLOCK_CONFIG_CMD
   TDSULR4_LOG_ACT_UL_FW_TX_HW_BLOCK_CFG_CMD                     = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x16,
   //MCALTDS_EVT_GEN_TL_INTR Registration
   TDSULR4_LOG_ACT_UL_SEQ_ENT_GEN_TL_INTR_REG                    = TDSULR4_LOG_ACT_TASK_UL_SEQ_SOLID_ARROW+ 0x18,
   //TDS_UL_PHYCHAN_ADD_DONE_CMD
   TDSULR4_LOG_ACT_UL_L1M_CPHY_ADD_DONE_CMD                      = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x20, 
   //***tdsuldpchctrl_process_dpch_data
   //RFA_RF_TDSCDMA_ENABLE_TX_REQ
   TDSULR4_LOG_ACT_UL_RF_TDS_ENABLE_TX_REQ                       = TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW + 0x22,
   //RFA_RF_TDSCDMA_ENABLE_TX_CNF
   TDSULR4_LOG_ACT_RF_UL_TDS_ENABLE_TX_CFN                       = TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW + 0x24,
   //***tdsenc_program_enc_for_r4_chan
   //tdsenc_common_trigger_encode
   TDSULR4_LOG_ACT_UL_UL_ENC_TRIGGER                             = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x26,
   //tdsenc_common_cmd_done_handler
   TDSULR4_LOG_ACT_UL_UL_ENC_DONE                                = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x28,
   //TDSCDMA_FW_DPCH_TX_PWR_TIMING_CONFIG_CMD
   TDSULR4_LOG_ACT_UL_FW_DPCH_TX_PWR_TIME_CFG_CMD                = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x30,
   //TDSCDMA_FW_UL_DPCH_CONFIG_CMD
   TDSULR4_LOG_ACT_UL_FW_DPCH_CFG_CMD                            = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x32,
   //TDSCDMA_FW_UL_DPCH_CANCEL_CMD
   TDSULR4_LOG_ACT_UL_FW_DPCH_CANCEL_CMD                         = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x34,
   //***tdsl1_phy_ul_build_frame_ind
   //tdsl1_phy_ul_build_frame_ind
   TDSULR4_LOG_ACT_UL_MAC_BUILD_FRAME_IND                        = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0x36,
   //tdsuldpchctrl_tx_enable
   TDSULR4_LOG_ACT_DL_UL_TX_ENABLE                               = TDSULR4_LOG_ACT_TASK_DL_UL_SOLID_ARROW + 0x38,
   //tdsuldpchctrl_tx_disable
   TDSULR4_LOG_ACT_DL_UL_TX_DISABLE                              = TDSULR4_LOG_ACT_TASK_DL_UL_SOLID_ARROW + 0x40,
   //tdsuldpchctrl_suspend_bfi_two_frames_before_act_time
   TDSULR4_LOG_ACT_L1M_UL_SUSPEND_BFI_TWO_FRAME_BEFORE_ACT       = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x42, 
   //tdsulcmd_phychan_recfg_cmd
   TDSULR4_LOG_ACT_L1M_UL_CPHY_RECFG_CMD                         = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x44,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_REQ
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF
   //TDSCDMA_FW_TX_HW_BLOCK_CONFIG_CMD
   //MCALTDS_EVT_GEN_TL_INTR Registration
   //TDS_UL_PHYCHAN_CFG_DONE_CMD
   //tdsulcmd_phychan_drop_cmd
   TDSULR4_LOG_ACT_L1M_UL_CPHY_DROP_CMD                          = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x46,
   //register_sub_frame_boundary_cb
   TDSULR4_LOG_ACT_UL_UL_REG_SUB_FRAME_BOUND_CB                  = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x48,
   //tdsuldpchctrl_delay_drop_cb
   TDSULR4_LOG_ACT_UL_UL_DELAY_DROP_CB                           = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x50,
   //MCALTDS_EVT_GEN_TL_INTR De-registration
   TDSULR4_LOG_ACT_UL_SEQ_DEREG_ENT_GEN                          = TDSULR4_LOG_ACT_TASK_UL_SEQ_SOLID_ARROW + 0x52,
   //TDS_UL_PHYCHAN_DROP_DONE_CMD
   TDSULR4_LOG_ACT_UL_PHYCHAN_DROP_DONE_CMD                      = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x54,
   //tx_hw_block_disable (Blocking)
   TDSULR4_LOG_ACT_UL_FW_TX_HW_BLOCK_DISENABLE                   = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x56,
   //RFA_RF_TDSCDMA_DISABLE_TX_REQ
   TDSULR4_LOG_ACT_UL_RF_DISABLE_TX_REQ                          = TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW + 0x60,
   //RFA_RF_TDSCDMA_DISABLE_TX_CNF
   TDSULR4_LOG_ACT_UL_RF_DISABLE_TX_CNF                          = TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW + 0x62,
 
   //***tdsuldpchctrl_process_dpch_data
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_START                   = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x64,
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_END                     = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x65,
   //***tdsenc_program_enc_for_r4_chan
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_START                      = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x66,
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_END                        = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x67,
   //***tdsl1_phy_ul_build_frame_ind
   TDSULR4_LOG_ACT_SEQ_PHY_UL_BUILD_FRAME_START                  = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x68,
   TDSULR4_LOG_ACT_SEQ_PHY_UL_BUILD_FRAME_END                    = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x69,
   //***tdsuldpchctrl_process_dpch_data, profile SB and TX seperately
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_SB_START                = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x6A,
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_SB_END                  = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x6B,
   //*** SB
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_TX_START		 = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x6C,
   TDSULR4_LOG_ACT_SEQ_PROCESS_DPCH_DATA_TX_END			 = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0x6D,

   //RACH ADD
   //tdsulcmd_phychan_add_cmd
   TDSULR4_LOG_ACT_L1M_UL_CPHY_ADD_CMD_PRACH			 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x80,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_REQ (share)
   TDSULR4_LOG_ACT_UL_RF_RFA_SET_TX_PWR_LIMIT_REQ_PRACH	         = TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW + 0x82,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF (share)
   TDSULR4_LOG_ACT_UL_RF_RFA_SET_TX_PWR_LIMIT_CNF_PRACH	         = TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW + 0x84,
   //RFA_RF_TDSCDMA_ENABLE_TX_REQ (share)
   TDSULR4_LOG_ACT_UL_RF_TDS_ENABLE_TX_REQ_PRACH	         = TDSULR4_LOG_ACT_TASK_UL_RF_SOLID_ARROW + 0x86,
   //RFA_RF_TDSCDMA_ENABLE_TX_CNF (share)
   TDSULR4_LOG_ACT_RF_UL_TDS_ENABLE_TX_CFN_PRACH		 = TDSULR4_LOG_ACT_TASK_RF_UL_SOLID_ARROW + 0x88,
   //mcaltds_mcpmdrv_request_power_config (share)
   TDSULR4_LOG_ACT_UL_MCPM_DRV_REQ_PWR_CFG_PRACH		 = TDSULR4_LOG_ACT_TASK_UL_MCPM_SOLID_ARROW + 0x8A,
   //TDSCDMA_FW_TX_HW_BLOCK_CONFIG_CMD (share)
   TDSULR4_LOG_ACT_UL_FW_TX_HW_BLOCK_CFG_CMD_PRACH 		 = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x8C,
   //TDS_TFW_INT_FPACH_DEC_DONE Registration
   TDSULR4_LOG_ACT_UL_UL_FW_INT_FPACH_DEC_DONE_REG               = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x8E, 
   //MCALTDS_EVT_GEN_TL_INTR Registration (share)
   TDSULR4_LOG_ACT_UL_SEQ_ENT_GEN_TL_INTR_REG_PRACH		 = TDSULR4_LOG_ACT_TASK_UL_SEQ_SOLID_ARROW+ 0x90,
   //TDS_UL_PHYCHAN_ADD_DONE_CMD
   TDSULR4_LOG_ACT_UL_L1M_CPHY_ADD_DONE_CMD_PRACH		 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0x92, 

   //RACH GET DATA
   //tdsenc_common_trigger_encode	Enc Interactions
   TDSULR4_LOG_ACT_UL_UL_TRIGGER_ENC 			         = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x94, 
   //tdsenc_common_cmd_done_handler	 Enc Interaction
   TDSULR4_LOG_ACT_UL_UL_DONE_CMD_ENC 			         = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0x96, 
   //TDSCDMA_FW_UPPCH_TX_PWR_TIMING_CONFIG_CMD	 FW Interaction
   TDSULR4_LOG_ACT_UL_FW_UPPCH_TX_PWR_TIMING_CONFIG_CMD          = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x98,
   //TDSCDMA_FW_FPACH_CONFIG_CMD	FW Interaction
   TDSULR4_LOG_ACT_UL_FW_FPACH_CONFIG_CMD	                 = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x9A,
   //TDSCDMA_FW_PRACH_CONFIG_CMD	FW Interaction
   TDSULR4_LOG_ACT_UL_FW_PRACH_CONFIG_CMD	                 = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0x9C,
   //tdsl1_phy_ul_build_frame_ind	MAC interaction (share)
   TDSULR4_LOG_ACT_UL_MAC_BUILD_FRAME_IND_PRACH                  = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0x9E,
   //TDSL1_PRACH_MSG_DONE	 MAC interaction (share)
   TDSULR4_LOG_ACT_UL_MAC_PRACH_MSG_DONE                         = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0xA0,
   
   //***tdsulra_process_prach_data Duaration
   TDSULR4_LOG_ACT_SEQ_PROCESS_PRACH_DATA_START                  = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA2,
   TDSULR4_LOG_ACT_SEQ_PROCESS_PRACH_DATA_END                    = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA3,
   //***tdsenc_program_enc_for_r4_chan
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_PRACH_START                = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA4,
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_PRACH_END                  = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA5,
   //***tdsl1_phy_ul_build_frame_ind
   TDSULR4_LOG_ACT_SEQ_PHY_UL_BUILD_FRAME_PRACH_START            = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA6,
   TDSULR4_LOG_ACT_SEQ_PHY_UL_BUILD_FRAME_PRACH_END              = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xA7,

   //FPACH for PRACH
   //tdsulra_fpach_dec_done_isr_for_prach	FW Interaction
   TDSULR4_LOG_ACT_UL_FW_FPACH_DEC_DONE_ISR_FOR_PRACH	         = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0xA8,
   //TDSL1_PRACH_NO_ACK	MAC interaction
   TDSULR4_LOG_ACT_UL_MAC_FPACH_NO_ACQ_PRACH                     = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0xAA,
   //TDSL1_PRACH_ACK	MAC interaction (no)
   TDSULR4_LOG_ACT_UL_MAC_FPACH_ACQ_PRACH                        = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0xAC,

   //RA ABORT
   //tdsulra_abort_random_access_proc
   TDSULR4_LOG_ACT_UL_FW_ABORT_RA_PROC	                         = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0xAE,
   //TDS_UL_RACH_DONE_CMD
   TDSULR4_LOG_ACT_L1M_UL_RACH_DONE_CMD			         = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xB0, 

   //RA resume/suspend
   //tdsulra_suspend_rach
   TDSULR4_LOG_ACT_L1M_UL_SUSPEND_RACH				 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xB2,
   //tdsulra_resume_rach
   TDSULR4_LOG_ACT_L1M_UL_RESUME_RACH				 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xB4,

   //RA DROP
   //tdsulcmd_cell_trans_drop_cmd	L1 Internal Interaction
   TDSULR4_LOG_ACT_L1M_UL_CELL_TRANS_DROP_CMD			 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xB6,
   //tdsulcmd_phychan_drop_cmd	L1 Internal Interaction (share)
   TDSULR4_LOG_ACT_L1M_UL_PHY_CHAN_DROP_CMD			 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xB8,
   //MCALTDS_EVT_GEN_TL_INTR De-registration	L1 Internal Interaction
   //TDS_TFW_INT_FPACH_DEC_DONE De-registration	L1 Internal Interaction
   TDSULR4_LOG_ACT_UL_SEQ_INT_FPACH_DEC_DONE_DEREG		 = TDSULR4_LOG_ACT_TASK_UL_SEQ_SOLID_ARROW + 0xBA,
   //TDSL1_PRACH_ABORT	MAC interaction
   TDSULR4_LOG_ACT_UL_MAC_PRACH_ABORT            		 = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0xBC,
   //TDS_UL_PHYCHAN_DROP_DONE_CMD	L1 Internal Interaction  (L1M done)
   //tx_hw_block_disable (Blocking)	Duaration  (without)
   //RFA_RF_TDSCDMA_DISABLE_TX_REQ	RF Interaction (share)
   //RFA_RF_TDSCDMA_DISABLE_TX_CNF	RF Interaction

   //***HHO resync
   //tdsulcmd_phychan_hho_resync_cmd	L1 Internal Interaction
   TDSULR4_LOG_ACT_L1M_UL_HHO_RESYNC_CMD		         = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xBE,
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_REQ	RF Interaction(share)
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF	RF Interaction(share)
   //TDS_TFW_INT_FPACH_DEC_DONE Registration	FW Interaction(share)
   //mcaltds_mcpmdrv_request_power_config	MCPM Interaction(share)
   //TDSCDMA_FW_TX_HW_BLOCK_CONFIG_CMD	FW Interaction(share)
   //MCALTDS_EVT_GEN_TL_INTR Registration	L1 Internal Interaction(share)

   //***HHO resync get data
   //tdsulra_process_hho_resync	Duaration
   TDSULR4_LOG_ACT_SEQ_PROCESS_HHO_RESYNC_DATA_START             = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xC0,
   TDSULR4_LOG_ACT_SEQ_PROCESS_HHO_RESYNC_DATA_END               = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xC1,
   //TDSCDMA_FW_UPPCH_TX_PWR_TIMING_CONFIG_CMD	FW Interaction (share)
   //TDSCDMA_FW_FPACH_CONFIG_CMD	FW Interaction (share)

   //***FPACH Decode Done ISR For HHO Resync
   //tdsulra_fpach_dec_done_isr_for_hho_resync   FW Interaction
   TDSULR4_LOG_ACT_UL_FW_FPACH_DEC_DONE_ISR_FOR_HHO_RESYNC       = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0xC2,
   //TDS_UL_HHO_RESYNC_SUCCESS_IND_CMD   L1 Internal Interaction (L1M done)
   TDSULR4_LOG_ACT_UL_UL_HHO_RESYNC_SUCCESS_IND_CMD	         = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0xC4, 
   //TDS_UL_HHO_RESYNC_FAIL_IND_CMD  L1 Internal Interaction
   TDSULR4_LOG_ACT_UL_UL_HHO_RESYNC_FAIL_IND_CMD	         = TDSULR4_LOG_ACT_TASK_UL_UL_SOLID_ARROW + 0xC6, 

   //ERUCCH CFG
   //tdsulcmd_e_rucch_cfg_cmd	L1 Internal Interaction
   TDSULR4_LOG_ACT_L1M_UL_ERUCCH_CONFIG_CMD		         = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xC8,
   
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_REQ	RF Interaction (share)
   //RFA_RF_TDSCDMA_SET_TX_PWR_LIMIT_CNF	RF Interaction(share)
   //RFA_RF_TDSCDMA_ENABLE_TX_REQ	RF Interaction(share)
   //RFA_RF_TDSCDMA_ENABLE_TX_CNF	RF Interaction(share)
   //mcaltds_mcpmdrv_request_power_config	MCPM Interaction (share)
   //TDSCDMA_FW_TX_HW_BLOCK_CONFIG_CMD	FW Interaction(share)
   //TDS_TFW_INT_FPACH_DEC_DONE Registration	FW Interaction(share)
   //MCALTDS_EVT_GEN_TL_INTR Registration	L1 Internal Interaction (share)

   //ERUCCH Get_Data   
   //tdsulra_process_erucch_data	Duaration
   TDSULR4_LOG_ACT_SEQ_PROCESS_ERUCCH_DATA_START                 = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xCA,
   TDSULR4_LOG_ACT_SEQ_PROCESS_ERUCCH_DATA_END                   = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xCB,
   //tdsenc_program_enc_for_erucch_chan	Duaration
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_ERUCCH_START               = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xCC,
   TDSULR4_LOG_ACT_SEQ_PROGRAM_ENC_R4_ERUCCH_END                 = TDSULR4_LOG_ACT_TASK_STMR_STMR_DASH_WO_ARROW + 0xCD,
   //tdsenc_common_trigger_encode	Enc Interaction (share)
   //tdsenc_common_cmd_done_handler	Enc Interaction (share)
   //TDSCDMA_FW_UPPCH_TX_PWR_TIMING_CONFIG_CMD	FW Interaction (share)
   //TDSCDMA_FW_FPACH_CONFIG_CMD	FW Interaction (share)
   //TDSCDMA_FW_PRACH_CONFIG_CMD	FW Interaction (share)
   //tdseul_erucch_fpach_ack_rvd	L1 Internal Interaction
   TDSULR4_LOG_ACT_UL_MAC_ERUCCH_FPACH_ACK_RVD                   = TDSULR4_LOG_ACT_TASK_UL_MAC_SOLID_ARROW + 0xD0,
   //TDSL1_PRACH_MSG_DONE	MAC interaction (share)

   //***FPACH Decode Done ISR For ERUCCH
   //tdsulra_fpach_dec_done_isr_for_erucch
   TDSULR4_LOG_ACT_UL_FW_FPACH_DEC_DONE_ISR_FOR_ERUCCH	         = TDSULR4_LOG_ACT_TASK_UL_FW_SOLID_ARROW + 0xD2,

   //ERUCCH ABORT
   //tdsulcmd_e_rucch_abort_cmd	L1 Internal Interaction	L1M
   TDSULR4_LOG_ACT_L1M_UL_ERUCCH_ABORT_CMD			 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xD4,
   //MCALTDS_EVT_GEN_TL_INTR De-registration	L1 Internal Interaction	SEQ (share)
   //TDS_TFW_INT_FPACH_DEC_DONE De-registration	L1 Internal Interaction	SEQ (share)

   //Ciphering
   //tdsulcmd_set_ciphering_keys	L1 Internal Interaction	L1M
   TDSULR4_LOG_ACT_L1M_UL_SET_CIPHERING_KEY			 = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xD6,
   //UPCC	tdsulcmd_phychan_ctrl_cmd	L1 Internal Interaction	L1M
   TDSULR4_LOG_ACT_L1M_UL_UPCC_UL_PHY_CTRL_CMD				       = TDSULR4_LOG_ACT_TASK_L1M_UL_SOLID_ARROW + 0xD8,

/*******************************************************************************************************************/

/***********************************************TDRM profiling actions*********************************************************/

/****************************** TDRM buffer ***************************************/
//L1M TO TDRM LOCK PROCESS
TDRM_LOG_ACT_L1M_TDRM_REQ_AND_NOTFY               = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x0,
TDRM_LOG_ACT_L1M_TDRM_RETAIN_LOCK                 = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x2,
TDRM_LOG_ACT_L1M_TDRM_RESERVE_AT                  = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x4,
TDRM_LOG_ACT_L1M_TDRM_REQUEST_LOCK                = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x6,
TDRM_LOG_ACT_L1M_TDRM_CHANGE_PRIORITY             = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x8,
TDRM_LOG_ACT_L1M_TDRM_RELEASE_LOCK                = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0xA,
TDRM_LOG_ACT_L1M_TDRM_EXTEND_DURATION             = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0xC,
TDRM_LOG_ACT_L1M_TDRM_BAND_CHANGE_REQ             = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0xE,
TDRM_LOG_ACT_L1M_TDRM_EXCHANGE                    = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x10,
                                                  
//RRC TO TDRM LOCK PROCESS                        
TDRM_LOG_ACT_RRC_TDRM_REQ_AND_NOTFY               = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x12,
TDRM_LOG_ACT_RRC_TDRM_RETAIN_LOCK                 = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x14,
TDRM_LOG_ACT_RRC_TDRM_REQUEST_LOCK                = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x16,
TDRM_LOG_ACT_RRC_TDRM_CHANGE_PRIORITY             = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x18,
TDRM_LOG_ACT_RRC_TDRM_RELEASE_LOCK                = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x1A,
TDRM_LOG_ACT_RRC_TDRM_EXTEND_DURATION             = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x1C,
TDRM_LOG_ACT_RRC_TDRM_BAND_CHANGE_REQ             = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x1E,
TDRM_LOG_ACT_RRC_TDRM_EXCHANGE                    = TDRM_LOG_ACT_TDRM_IDV_RRC_TDRM_SOLID_ARROW + 0x20,
                                                  
//TDRM TO TRM                                     
TDRM_LOG_ACT_TDRM_TRM_REQ_AND_NOTFY               = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x22,
TDRM_LOG_ACT_TDRM_TRM_RETAIN_LOCK                 = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x24,
TDRM_LOG_ACT_TDRM_TRM_RESERVE_AT                  = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x26,
TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK                = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x28,
TDRM_LOG_ACT_TDRM_TRM_CHANGE_PRIORITY             = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x2A,
TDRM_LOG_ACT_TDRM_TRM_RELEASE_LOCK                = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x2C,
TDRM_LOG_ACT_TDRM_TRM_EXTEND_DURATION             = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x2E,
TDRM_LOG_ACT_TDRM_TRM_BAND_CHANGE_REQ             = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x30,
TDRM_LOG_ACT_TDRM_TRM_EXCHANGE                    = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x32,

TDRM_LOG_ACT_TDRM_TRM_REQ_AND_NOTFY_SEC           = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x34,
TDRM_LOG_ACT_TDRM_TRM_RETAIN_LOCK_SEC             = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x36,
TDRM_LOG_ACT_TDRM_TRM_RESERVE_AT_SEC              = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x38,
TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK_SEC            = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x3A,
TDRM_LOG_ACT_TDRM_TRM_RELEASE_LOCK_SEC            = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x3C,
TDRM_LOG_ACT_TDRM_TRM_EXTEND_DURATION_SEC         = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x3E,

TDRM_LOG_ACT_L1M_TDRM_RETAIN_LOCK_SEC             = TDRM_LOG_ACT_TDRM_IDV_L1M_TDRM_SOLID_ARROW + 0x4E,

/***************************** end of L1 task context ****************************/                      

/****************************** L1 buffer ***************************************/
//L1M TO TDRM CMD HANDLER
TDRM_LOG_ACT_L1M_TDRM_PRI_GRANT_CB_CMD_HANDLER    = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x50,
TDRM_LOG_ACT_L1M_TDRM_SECOND_GRANT_CB_CMD_HANDLER = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x52,
TDRM_LOG_ACT_L1M_TDRM_MODFY_REASON_CMD_HANDLER    = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x54,
TDRM_LOG_ACT_L1M_TDRM_MODFY_BAND_CMD_HANDLER      = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x56,
TDRM_LOG_ACT_L1M_TDRM_UNLOCK_SECOND_CMD_HANDLER   = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x58,
TDRM_LOG_ACT_L1M_TDRM_LOCK_REQ_FAIL_IND           = TDRM_LOG_ACT_L1_TASK_L1M_TDRM_SOLID_ARROW + 0x5A,

//TDRM TO L1M
TDRM_LOG_ACT_TDRM_L1M_DS_GRANT_CB                 = TDRM_LOG_ACT_L1_TASK_TDRM_L1M_SOLID_ARROW + 0x5C,
TDRM_LOG_ACT_TDRM_L1M_BAND_GRANT_CB               = TDRM_LOG_ACT_L1_TASK_TDRM_L1M_SOLID_ARROW + 0x5E,
TDRM_LOG_ACT_TDRM_L1M_MODFY_INFO_CB               = TDRM_LOG_ACT_L1_TASK_TDRM_RRC_SOLID_ARROW + 0x60,
TDRM_LOG_ACT_TDRM_L1M_CHANGE_PRIORITY_CB          = TDRM_LOG_ACT_L1_TASK_TDRM_L1M_SOLID_ARROW + 0x62,
                                                  
//TDRM TO RRC                                     
TDRM_LOG_ACT_TDRM_RRC_DS_GRANT_CB                 = TDRM_LOG_ACT_L1_TASK_TDRM_RRC_SOLID_ARROW + 0x64,
TDRM_LOG_ACT_TDRM_RRC_MODFY_INFO_CB               = TDRM_LOG_ACT_L1_TASK_TDRM_RRC_SOLID_ARROW + 0x66,
TDRM_LOG_ACT_TDRM_RRC_CHANGE_PRIORITY_CB          = TDRM_LOG_ACT_L1_TASK_TDRM_RRC_SOLID_ARROW + 0x68,  
/************************** end of L1 buffer ****************************/ 

/***************************** TRM task context ***************************************/
TDRM_LOG_ACT_TRM_TDRM_ASYNC_CB                    = TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW + 0x80,
TDRM_LOG_ACT_TRM_TDRM_UNLOCK_PRI_CB               = TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW + 0x82,
TDRM_LOG_ACT_TRM_TDRM_UNLOCK_SEC_CB               = TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW + 0x84,
TDRM_LOG_ACT_TRM_TDRM_GRANT_PRI_CB                = TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW + 0x86,
TDRM_LOG_ACT_TRM_TDRM_GRANT_SEC_CB                = TDRM_LOG_ACT_TRM_TASK_TRM_TDRM_SOLID_ARROW + 0x88,
/************************** end of TRM task context ****************************/ 
 
/***********************************start_end action  **********************************************/
TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK_STT       = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x100,
TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK_END       = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x101,

TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK_SEC_STT       = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x102,
TDRM_LOG_ACT_TDRM_TRM_REQUEST_LOCK_SEC_END       = TDRM_LOG_ACT_TDRM_IDV_TDRM_TRM_SOLID_ARROW + 0x103,

/***********************************************end of TDRM profiling actions*********************************************************/


}tdsl1mlog_packet_action_type_enum;

typedef struct
{
  /* Word 0*/
  /*! \brief action(enum type) */
  tdsl1mlog_packet_action_type_enum module_action;
  /* Word 1*/
  /*! \brief universal STMR */    
  uint32 univ_or_rx_stmr;
  /* Word 2*/
  /*! \brief rx_sfn */
  //uint32 rx_sfn:16 ;
  /*! \brief rx_cx8 */
  //uint32 rx_cx8:16 ;
}tdsl1mlog_profiling_result_struct_type;

typedef struct
{
  uint32 u_stmr; //0~0x7FFFFFF

  uint32 rx_sub_frame_num:16;  //0~8191

  uint32 rx_cx8:16;     //0~C7FF
}tdsl1m_profiling_stmr_in_head;


typedef struct
{  
  tdsl1m_profiling_stmr_in_head univ_rx_stmr_in_head[2];//pingpong buffer to save the timing of in header of log packet
  
  uint16  current_log_packet_buff_ping_pang_index;/* ping-pang index */  
  uint16  record_ping_pang_index;
  
  uint16  current_l1m_log_packet_index[TDSL1M_LOG_SOURE_NUM];  
  uint16  start_l1m_log_packet_index[TDSL1M_LOG_SOURE_NUM];
  
  uint16  record_num[TDSL1M_LOG_SOURE_NUM];
  uint16  record_start_index[TDSL1M_LOG_SOURE_NUM];

  uint16  triger_local_cmd_flag;
}tdsl1m_profiling_control_data;


/*! \brief L1M timing frofiling.*/
typedef struct
{
  /*! \brief Log header */
  log_hdr_type header;

  /* Word 0 */
  /*! \brief Log packet version; range is 0 to 255 */
  uint32  version:8;
  
  /*number of profiling source: 
      0: only 1 profiling source in the log packet. The entries in the log packet are in order, no sorting is needed
      1: 2 profiling source in the log packet. the entries in the log packet are captured parallel, so sorting is need*/
  uint32 record_source: 8;

  /*! \brief Number of dob status info table */
  uint32 NumL1mRecord: 16;

  uint32 u_stmr; //0~0x7FFFFFF

  uint32 rx_sub_frame_num:16;  //0~8191

  uint32 rx_cx8:16;     //0~C7FF

  /* size 24 bytes */
  /*! \brief timing record table, actual number determined by current L1M timing records */
  tdsl1mlog_profiling_result_struct_type l1m_profiling_db[TDSL1MLOG_PACKET_MAX_PAYLOAD];

}tdsl1mlog_profiling_log_pkt_type;

typedef struct
{
  /* local command header type */
  tdsl1def_l1_local_cmd_hdr_type       hdr;

  uint32 cmd_source_bmp;

}tdsl1m_log_packet_cmd_type;


#define TDSL1LOG_L1M_TIMING_PROFILING_PKT_LEN(NumL1mRecord) \
  FPOS(tdsl1mlog_profiling_log_pkt_type, l1m_profiling_db)+  \
  (NumL1mRecord*sizeof(tdsl1mlog_profiling_result_struct_type))

#define TDSL1MLOG_PROFILING_DB_POSITION \
  FPOS(tdsl1mlog_profiling_log_pkt_type, l1m_profiling_db)

#endif

/* DSDS QTA log packet */
#ifdef FEATURE_TDSCDMA_DSDS_QTA  /*FEATURE_QTA*/


/*--------------------------------------------------------------------------
        LOG PACKET: TDSCDMA_L1_DSDS_QTA_REPORT_LOG_PACKET
                 (LOG CODE: 0xD06E)
                     
This packet hold quick tune away status for T/G + G DSDS UE, including its 
start time, end time, duration, L1 state, etc
 
This log record is generated whenever a quick tune away happens

Size: 12 + 52 = 64 bytes
----------------------------------------------------------------------------*/

/*! \brief qta time struct, size: 12 bytes */
typedef struct
{
  /* Word 0&1*/
  /*! \brief sleep clock */    
  int64 cur_timetick;
  /* Word 2*/
  /*! \brief rx_sfn */
  uint16 rx_sfn ;
  /*! \brief rx_cx8 */
  uint16 rx_cx8 ;
  /* Word 3*/
  uint32 pad3;
}tdsl1mlog_dsds_qta_time_struct_type;

/*! \brief L1M DSDS QTA report.*/
typedef struct
{
  /*! \brief Log header */
  log_hdr_type header;

  /* Word 0 */
  /*! \brief Log packet version; range is 0 to 255 */
  uint32  version:8;

  /*! \brief Reserved */
  uint32  pad1: 24;  
  
  /* word 1~4 */
  /*! \brief QTA start time */
  tdsl1mlog_dsds_qta_time_struct_type qta_start_time;
  /* word 5~8 */
  /*! \brief QTA end time */
  tdsl1mlog_dsds_qta_time_struct_type qta_end_time;  

  /* word 9~10 */
  /*! \brief QTA duration(QTA end time ¨C QTA start time) in sleep clock, 32kHz */
  int64 qta_l1_duration_in_slk;
  /* word 11 */
  /*! \brief QTA duration(QTA end time ¨C QTA start time) in ms */
  uint16 qta_l1_duration_in_ms;
  /*! \brief QTA duration(cxmLockLostTime ¨C cxmLockAcqTime) in ms */
  uint16 qta_fw_duration_in_ms;
  
  /* word 12 */
  /*! \brief L1M state when QTA happen(DCH:7 or FACH:6) */
  uint8 l1m_state_when_qta;
  /*! \brief HSDPA HARQ flush after QTA (TRUE or FALSE) */
  uint8 dpa_harq_flash_flag;
  /*! \brief Re-ACQ complete indicator after QTA (TRUE or FALSE) */
  uint8 reacq_complete_ind;
  
  uint8 pad2;

}tdsl1mlog_dsds_qta_log_pkt_type;
#endif /* DSDS QTA */

//FR 20258 Power Logging
typedef struct
{
  /*! \brief Log header */
  log_hdr_type header;

  /* Word 0 */
  /*! \brief Log packet version; range is 0 to 255 */
  uint8  version;

  /*! \brief Voice/data/both (1:VOICE_CALL_ACTIVE, 2:PS_CALL_ACTIVE, 3:Both ACTIVE) */
  uint8 service_type;

  /*! \brief EQ/MUD/NoDemod (0:NoDemod, 1:EQ, 2:MUD, 3:EQ&MUD) */
  uint8 demod_mode;

  /*! \brief Since this is for power logging, this field specifies whether RxD is turned on or off. Baseband may or may not process the diversity signal. */
  boolean rxd_on;

  /* Word 1-2 */
  /*! \Allows time correlation of all data in all device power information log packets to < 1ms accuracy */
  uint64 ustmr_time;

  /* Word 3 */
  /*! \brief Max value = 8 {DPCH, SCCH, PDSCH, SICH, EAGCH, EHICH, EDCH, ERUCH} */
  uint8 num_channels;

  /*! \brief currently maximum number of JDS cells; Max value = 8 */
  uint8 num_jds_cells;

  /*! \brief Number of cells measured in a normal operation per 20ms; Max value = 160 */
  uint8 num_meas_cells;

  /*! \brief Bitmap. 0x1:TDSL1_DL_CONV_1_BY_2_CODING, 0x2:TDSL1_DL_CONV_1_BY_3_CODING, 0x4:TDSL1_DL_TURBO_CODING, 0x8:TDSL1_DL_UNCODED 
             This is to indicate whether the decoders are enabled or not. They may not be active */
  uint8 decoder;

  /* Word 4 */
  /*! \brief Number of active DL TS over 20ms period */
  uint8 active_dl_slots;

  /*! \brief Number of active DL TS over 20ms period */
  uint8 active_ul_slots;

  /*! \brief Average Tx power over the past 20ms, in 8Q1 format, 0.5dbm step */
  int8 uplink_power;

  /*! \brief Reserved */
  uint8 reserved;
 

}tdsl1mlog_mcpm_power_reporting_log_packet_type;

#define TDSL1MLOG_MCPM_POWER_REPORTING_PKT_LEN()  ( \
    sizeof(tdsl1mlog_mcpm_power_reporting_log_packet_type))

void tdsl1_profiling_time_record(tdsl1mlog_packet_action_type_enum current_act);

#endif /* TDSL1MLOG_H */


