#!/bin/bash

${Q6_TOOLS_ROOT}/gnu/bin/qdsp6-objcopy --change-start $2 --change-section-lma .start$2 --change-section-lma .init$2 --change-section-lma .text$2 --change-section-lma .fini$2 --change-section-lma .rodata$2 --change-section-lma .data$2 --change-section-lma .eh_frame$2 --change-section-lma .ctors$2 --change-section-lma .dtors$2 --change-section-lma .bss$2 --change-section-lma .sdata$2 --change-section-lma .sbss$2 $1
