/*============================================================================

FILE:      DalChipInfoLocal.c

DESCRIPTION:
  This file implements the portion of the ChipInfo DAL that reads information
  from the hardware.

PUBLIC CLASSES:
  ChipInfo_DriverInit
  ChipInfo_DriverDeInit

============================================================================
        Copyright (c) 2010 Qualcomm Technologies Incorporated.
               All Rights Reserved.
            QUALCOMM Proprietary/GTDR
============================================================================
  $Header: //components/rel/core.mpss/3.5.c12.3/systemdrivers/chipinfo/src/DalChipInfoLocalVirtio.c#1 $
  $DateTime: 2016/12/13 07:59:23 $
  $Author: mplcsds1 $
 
when       who     what, where, why
--------   ---     --------------------------------------------------------
07/11/11   pbi     Fixed warnings.
============================================================================*/


/*=========================================================================
      Include Files
==========================================================================*/

#include "DALDeviceId.h"
#include "DalChipInfo.h"
#include "DDIHWIO.h"
#include <stringl/stringl.h>


/*=========================================================================
      Type Definitions
==========================================================================*/


/*
 * DalChipInfoDataLUTType
 *
 * Static per-chip data definitions.
 *
 * szChipId:  String representing the MSM name.
 * nFamily:   Chip Family enum.
 * nModem:    Bitmask of supported modems on this MSM.
 */
typedef struct
{
  const char          *szChipId;
  DalChipInfoFamilyType nFamily;
  DalChipInfoModemType nModem;
} DalChipInfoDataLUTType;


/*
 * Define some modem combination shortcuts.
 */
#define DALCHIPINFO_MODEM_1XEVDO       (DALCHIPINFO_MODEM_1X | DALCHIPINFO_MODEM_EVDO)
#define DALCHIPINFO_MODEM_1XEVDO_REVA  (DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_EVDO_REVA)
#define DALCHIPINFO_MODEM_1XEVDO_REVB  (DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_EVDO_REVB)
#define DALCHIPINFO_MODEM_WWAN         (DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS)


/*=========================================================================
      Data Definitions
==========================================================================*/

/*
 * DALCHIPINFO_MFGNUM_*
 *
 * Manufacturer IDs
 */
#define DALCHIPINFO_MFGNUM_QUALCOMM 0x170

/*
 * DALCHIPINFO_PARTNUM_*
 *
 * Definitions of part number fields.
 */
#define DALCHIPINFO_PARTNUM_MSM7600        0x100
#define DALCHIPINFO_PARTNUM_MDM1000        0x160
#define DALCHIPINFO_PARTNUM_MSM7200A       0x170
#define DALCHIPINFO_PARTNUM_MSM7500A       0x190
#define DALCHIPINFO_PARTNUM_ESM7205A       0x2B0
#define DALCHIPINFO_PARTNUM_QST1000        0x1F0
#define DALCHIPINFO_PARTNUM_QST1100        0x200
#define DALCHIPINFO_PARTNUM_QST1005        0x230
#define DALCHIPINFO_PARTNUM_QST1105        0x210

#define DALCHIPINFO_PARTNUM_MSM7225_0      0x1B0
#define DALCHIPINFO_PARTNUM_MSM7225_1      0x1B1
#define DALCHIPINFO_PARTNUM_ESM7225        0x2F0
#define DALCHIPINFO_PARTNUM_MSM7525        0x1D0
#define DALCHIPINFO_PARTNUM_MSM7625        0x1E0
#define DALCHIPINFO_PARTNUM_QST1500        0x350
#define DALCHIPINFO_PARTNUM_QST1600        0x360
#define DALCHIPINFO_PARTNUM_QST1700        0x370

#define DALCHIPINFO_PARTNUM_QSD8250_0      0x240
#define DALCHIPINFO_PARTNUM_QSD8250_1      0x241
#define DALCHIPINFO_PARTNUM_QSD8250_2      0x242
#define DALCHIPINFO_PARTNUM_QSD8250_3      0x243
#define DALCHIPINFO_PARTNUM_QSD8250_4      0x244
#define DALCHIPINFO_PARTNUM_QSD8250_5      0x245
#define DALCHIPINFO_PARTNUM_QSD8250_6      0x246
#define DALCHIPINFO_PARTNUM_QSD8650_0      0x280
#define DALCHIPINFO_PARTNUM_QSD8650_1      0x281
#define DALCHIPINFO_PARTNUM_QSD8650_2      0x282
#define DALCHIPINFO_PARTNUM_QSD8650_3      0x283
#define DALCHIPINFO_PARTNUM_QSD8650_4      0x284
#define DALCHIPINFO_PARTNUM_QSD8650_5      0x285
#define DALCHIPINFO_PARTNUM_QSD8650_6      0x286

#define DALCHIPINFO_PARTNUM_MSM7227        0x3C0
#define DALCHIPINFO_PARTNUM_MSM7227D1      0x3C1
#define DALCHIPINFO_PARTNUM_MSM7627        0x3E0
#define DALCHIPINFO_PARTNUM_MSM7627D1      0x3E1
#define DALCHIPINFO_PARTNUM_MSM7627D2      0x3E2

#define DALCHIPINFO_PARTNUM_MSM7230_0      0x430
#define DALCHIPINFO_PARTNUM_MSM7230_1      0x431
#define DALCHIPINFO_PARTNUM_MSM7230_2      0x432
#define DALCHIPINFO_PARTNUM_MSM7230_3      0x433
#define DALCHIPINFO_PARTNUM_MSM7630_0      0x440
#define DALCHIPINFO_PARTNUM_MSM7630_1      0x441
#define DALCHIPINFO_PARTNUM_MSM7630_2      0x442
#define DALCHIPINFO_PARTNUM_MSM7630_3      0x443

#define DALCHIPINFO_PARTNUM_MDM8220        0x3F0 
#define DALCHIPINFO_PARTNUM_MDM9200        0x3F1
#define DALCHIPINFO_PARTNUM_MDM9600        0x460

#define DALCHIPINFO_PARTNUM_MSM8255_0      0x570
#define DALCHIPINFO_PARTNUM_MSM8255_1      0x571
#define DALCHIPINFO_PARTNUM_MSM8255_2      0x572
#define DALCHIPINFO_PARTNUM_MSM8255_3      0x573
#define DALCHIPINFO_PARTNUM_MSM8255_4      0x574
#define DALCHIPINFO_PARTNUM_MSM8255_5      0x576
#define DALCHIPINFO_PARTNUM_MSM8255_6      0x57A
#define DALCHIPINFO_PARTNUM_MSM8655_0      0x580
#define DALCHIPINFO_PARTNUM_MSM8655_1      0x581
#define DALCHIPINFO_PARTNUM_MSM8655_2      0x582
#define DALCHIPINFO_PARTNUM_MSM8655_3      0x583
#define DALCHIPINFO_PARTNUM_MSM8655_4      0x584
#define DALCHIPINFO_PARTNUM_MSM8655_5      0x586
#define DALCHIPINFO_PARTNUM_MSM8655_6      0x58A
#define DALCHIPINFO_PARTNUM_MSM8660_0      0x530
#define DALCHIPINFO_PARTNUM_MSM8660_1      0x531
#define DALCHIPINFO_PARTNUM_MSM8660_2      0x534
#define DALCHIPINFO_PARTNUM_MSM8660_3      0x535
#define DALCHIPINFO_PARTNUM_MSM8660_4      0x536
#define DALCHIPINFO_PARTNUM_MSM8660_5      0x424
#define DALCHIPINFO_PARTNUM_MSM8660_6      0x425
#define DALCHIPINFO_PARTNUM_MSM8660_7      0x426
#define DALCHIPINFO_PARTNUM_QSD8672_0      0x522
#define DALCHIPINFO_PARTNUM_QSD8672_1      0x524
#define DALCHIPINFO_PARTNUM_QSD8672_2      0x523
#define DALCHIPINFO_PARTNUM_QSD8672_3      0x521
#define DALCHIPINFO_PARTNUM_QSD8672_4      0x520
#define DALCHIPINFO_PARTNUM_QSD8672_5      0x5D2
#define DALCHIPINFO_PARTNUM_QSD8672_6      0x5D4
#define DALCHIPINFO_PARTNUM_QSD8672_7      0x5D3
#define DALCHIPINFO_PARTNUM_QSD8672_8      0x5D1
#define DALCHIPINFO_PARTNUM_QSD8672_9      0x5D0

#define DALCHIPINFO_PARTNUM_ESM7227        0x510

#define DALCHIPINFO_PARTNUM_APQ8055_0      0x770
#define DALCHIPINFO_PARTNUM_APQ8055_1      0x772
#define DALCHIPINFO_PARTNUM_APQ8055_2      0x776
#define DALCHIPINFO_PARTNUM_APQ8055_3      0x77A

#define DALCHIPINFO_PARTNUM_MSM8260_0      0x420
#define DALCHIPINFO_PARTNUM_MSM8260_1      0x421

#define DALCHIPINFO_PARTNUM_APQ8060_0      0x6A0
#define DALCHIPINFO_PARTNUM_APQ8060_1      0x6A1
#define DALCHIPINFO_PARTNUM_APQ8060_2      0x6A4
#define DALCHIPINFO_PARTNUM_APQ8060_3      0x6A5

#define DALCHIPINFO_PARTNUM_MSM8960_0      0x6B0
#define DALCHIPINFO_PARTNUM_MSM8960_1      0x6B1
#define DALCHIPINFO_PARTNUM_MSM8960_2      0x6B2
#define DALCHIPINFO_PARTNUM_MSM8960_3      0x6B3
#define DALCHIPINFO_PARTNUM_MSM8960_4      0x6B4
#define DALCHIPINFO_PARTNUM_MSM8960_5      0x6B5
#define DALCHIPINFO_PARTNUM_MSM8960_6      0x6B6
#define DALCHIPINFO_PARTNUM_MSM8960_7      0x6B7
#define DALCHIPINFO_PARTNUM_MSM8960_8      0x6B8
#define DALCHIPINFO_PARTNUM_MSM8960_9      0x6B9
#define DALCHIPINFO_PARTNUM_MSM8960_10     0x6BA
#define DALCHIPINFO_PARTNUM_MSM8960_11     0x6BB
#define DALCHIPINFO_PARTNUM_MSM8960_12     0x6BC
#define DALCHIPINFO_PARTNUM_MSM8960_13     0x6BD
#define DALCHIPINFO_PARTNUM_MSM8960_14     0x6BE
#define DALCHIPINFO_PARTNUM_MSM8960_15     0x6BF

#define DALCHIPINFO_PARTNUM_MSM8660A_0     0x7A0
#define DALCHIPINFO_PARTNUM_MSM8660A_1     0x7A1
#define DALCHIPINFO_PARTNUM_MSM8660A_2     0x7A2
#define DALCHIPINFO_PARTNUM_MSM8660A_3     0x7A3

#define DALCHIPINFO_PARTNUM_MSM8260A_0     0x790
#define DALCHIPINFO_PARTNUM_MSM8260A_1     0x791
#define DALCHIPINFO_PARTNUM_MSM8260A_2     0x792
#define DALCHIPINFO_PARTNUM_MSM8260A_3     0x793
#define DALCHIPINFO_PARTNUM_MSM8260A_4     0x794
#define DALCHIPINFO_PARTNUM_MSM8260A_5     0x795
#define DALCHIPINFO_PARTNUM_MSM8260A_6     0x796
#define DALCHIPINFO_PARTNUM_MSM8260A_7     0x797
#define DALCHIPINFO_PARTNUM_MSM8260A_8     0x798
#define DALCHIPINFO_PARTNUM_MSM8260A_9     0x799
#define DALCHIPINFO_PARTNUM_MSM8260A_10    0x79A
#define DALCHIPINFO_PARTNUM_MSM8260A_11    0x79B

#define DALCHIPINFO_PARTNUM_APQ8060A_0      0x780
#define DALCHIPINFO_PARTNUM_APQ8060A_1      0x781
#define DALCHIPINFO_PARTNUM_APQ8060A_2      0x782
#define DALCHIPINFO_PARTNUM_APQ8060A_3      0x783

#define DALCHIPINFO_PARTNUM_QSC6195        0x3B0
#define DALCHIPINFO_PARTNUM_QSC6185        0x3B2
#define DALCHIPINFO_PARTNUM_QSC6175        0x3B4
#define DALCHIPINFO_PARTNUM_QSC6165        0x3B6
#define DALCHIPINFO_PARTNUM_QSC6155        0x3B8
#define DALCHIPINFO_PARTNUM_QSC6295        0x470
#define DALCHIPINFO_PARTNUM_ESC6295        0x472
#define DALCHIPINFO_PARTNUM_QSC6695        0x480
#define DALCHIPINFO_PARTNUM_MDM3000        0x410
#define DALCHIPINFO_PARTNUM_MDM6200        0x490
#define DALCHIPINFO_PARTNUM_MDM6600        0x500
#define DALCHIPINFO_PARTNUM_MDM6210        0x590
#define DALCHIPINFO_PARTNUM_MDM6610        0x5A0
#define DALCHIPINFO_PARTNUM_MDM6215_0      0x5E0
#define DALCHIPINFO_PARTNUM_MDM6215_1      0x5E1
#define DALCHIPINFO_PARTNUM_MDM6215_2      0x5E2
#define DALCHIPINFO_PARTNUM_MDM6215_3      0x5E3
#define DALCHIPINFO_PARTNUM_MDM6215_4      0x5E4
#define DALCHIPINFO_PARTNUM_MDM6215_5      0x5E5
#define DALCHIPINFO_PARTNUM_MDM6215_6      0x5E6
#define DALCHIPINFO_PARTNUM_MDM6215_7      0x5E7
#define DALCHIPINFO_PARTNUM_MDM6615_0      0x5F0
#define DALCHIPINFO_PARTNUM_MDM6615_1      0x5F1
#define DALCHIPINFO_PARTNUM_MDM6615_2      0x5F2
#define DALCHIPINFO_PARTNUM_MDM6615_3      0x5F3
#define DALCHIPINFO_PARTNUM_MDM6615_4      0x5F4
#define DALCHIPINFO_PARTNUM_MDM6615_5      0x5F5
#define DALCHIPINFO_PARTNUM_MDM6615_6      0x5F6
#define DALCHIPINFO_PARTNUM_MDM6615_7      0x5F7
#define DALCHIPINFO_PARTNUM_QSC6195D2      0x3BA
#define DALCHIPINFO_PARTNUM_MDM9615        0x6F0
#define DALCHIPINFO_PARTNUM_MDM9615M       0x6F1
#define DALCHIPINFO_PARTNUM_MDM8215        0x6E0
#define DALCHIPINFO_PARTNUM_MDM9215        0x740
#define DALCHIPINFO_PARTNUM_MDM9215M       0x741

#define DALCHIPINFO_PARTNUM_MSM8930_0      0x720
#define DALCHIPINFO_PARTNUM_MSM8930_1      0x721
#define DALCHIPINFO_PARTNUM_MSM8930_2      0x722
#define DALCHIPINFO_PARTNUM_MSM8930_3      0x723
#define DALCHIPINFO_PARTNUM_MSM8930_4      0x724
#define DALCHIPINFO_PARTNUM_MSM8930_5      0x725
#define DALCHIPINFO_PARTNUM_MSM8930_6      0x726
#define DALCHIPINFO_PARTNUM_MSM8930_7      0x727
#define DALCHIPINFO_PARTNUM_MSM8930_8      0x728
#define DALCHIPINFO_PARTNUM_MSM8930_9      0x729
#define DALCHIPINFO_PARTNUM_MSM8930_10     0x72A
#define DALCHIPINFO_PARTNUM_MSM8930_11     0x72B

#define DALCHIPINFO_PARTNUM_MSM8630_0      0x730
#define DALCHIPINFO_PARTNUM_MSM8630_1      0x731

#define DALCHIPINFO_PARTNUM_MSM8230_0      0x750
#define DALCHIPINFO_PARTNUM_MSM8230_1      0x751
#define DALCHIPINFO_PARTNUM_MSM8230_2      0x752
#define DALCHIPINFO_PARTNUM_MSM8230_3      0x753
#define DALCHIPINFO_PARTNUM_MSM8230_4      0x754
#define DALCHIPINFO_PARTNUM_MSM8230_5      0x755

#define DALCHIPINFO_PARTNUM_APQ8030_0      0x760
#define DALCHIPINFO_PARTNUM_APQ8030_1      0x761

#define DALCHIPINFO_PARTNUM_MSM8627        0x7C0

#define DALCHIPINFO_PARTNUM_MSM8227_0      0x7D0
#define DALCHIPINFO_PARTNUM_MSM8227_1      0x7D1

#define DALCHIPINFO_PARTNUM_APQ8064_0      0x710
#define DALCHIPINFO_PARTNUM_APQ8064_1      0x711
#define DALCHIPINFO_PARTNUM_APQ8064_2      0x712
#define DALCHIPINFO_PARTNUM_APQ8064_3      0x713
#define DALCHIPINFO_PARTNUM_APQ8064_4      0x716
#define DALCHIPINFO_PARTNUM_APQ8064_5      0x717
#define DALCHIPINFO_PARTNUM_APQ8064_6      0x718
#define DALCHIPINFO_PARTNUM_APQ8064_7      0x719

#define DALCHIPINFO_PARTNUM_MPQ8062_0      0x714
#define DALCHIPINFO_PARTNUM_MPQ8062_1      0x715

#define DALCHIPINFO_PARTNUM_MSM8974_0      0x7B0

/*
 * amPartMap
 *
 * Map of part numbers to logical parts.
 */
DalChipInfoPartMapType amPartMap[] =
{
  { DALCHIPINFO_PARTNUM_MSM7600,    DALCHIPINFO_ID_MSM7600   },
  { DALCHIPINFO_PARTNUM_MDM1000,    DALCHIPINFO_ID_MDM1000   },
  { DALCHIPINFO_PARTNUM_MSM7200A,   DALCHIPINFO_ID_MSM7200A  },
  { DALCHIPINFO_PARTNUM_MSM7500A,   DALCHIPINFO_ID_MSM7500A  },
  { DALCHIPINFO_PARTNUM_ESM7205A,   DALCHIPINFO_ID_ESM7205A  },
  { DALCHIPINFO_PARTNUM_MSM7225_0,  DALCHIPINFO_ID_MSM7225   },
  { DALCHIPINFO_PARTNUM_MSM7225_1,  DALCHIPINFO_ID_MSM7225   },
  { DALCHIPINFO_PARTNUM_ESM7225,    DALCHIPINFO_ID_ESM7225   },
  { DALCHIPINFO_PARTNUM_MSM7525,    DALCHIPINFO_ID_MSM7525   },
  { DALCHIPINFO_PARTNUM_MSM7625,    DALCHIPINFO_ID_MSM7625   },
  { DALCHIPINFO_PARTNUM_QST1000,    DALCHIPINFO_ID_QST1000   },
  { DALCHIPINFO_PARTNUM_QST1100,    DALCHIPINFO_ID_QST1100   },
  { DALCHIPINFO_PARTNUM_QST1005,    DALCHIPINFO_ID_QST1005   },
  { DALCHIPINFO_PARTNUM_QST1105,    DALCHIPINFO_ID_QST1105   },
  { DALCHIPINFO_PARTNUM_QST1500,    DALCHIPINFO_ID_QST1500,  },
  { DALCHIPINFO_PARTNUM_QST1600,    DALCHIPINFO_ID_QST1600,  },
  { DALCHIPINFO_PARTNUM_QST1700,    DALCHIPINFO_ID_QST1700,  },
  { DALCHIPINFO_PARTNUM_QSD8250_0,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_1,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_2,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_3,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_4,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_5,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8250_6,  DALCHIPINFO_ID_QSD8250   },
  { DALCHIPINFO_PARTNUM_QSD8650_0,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_1,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_2,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_3,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_4,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_5,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_QSD8650_6,  DALCHIPINFO_ID_QSD8650   },
  { DALCHIPINFO_PARTNUM_MSM7227,    DALCHIPINFO_ID_MSM7227   },
  { DALCHIPINFO_PARTNUM_MSM7227D1,  DALCHIPINFO_ID_MSM7227D1 },
  { DALCHIPINFO_PARTNUM_MSM7627,    DALCHIPINFO_ID_MSM7627   },
  { DALCHIPINFO_PARTNUM_MSM7627D1,  DALCHIPINFO_ID_MSM7627D1 },
  { DALCHIPINFO_PARTNUM_MSM7627D2,  DALCHIPINFO_ID_MSM7627D2 },
  { DALCHIPINFO_PARTNUM_MSM7230_0,  DALCHIPINFO_ID_MSM7230   }, 
  { DALCHIPINFO_PARTNUM_MSM7230_1,  DALCHIPINFO_ID_MSM7230   },
  { DALCHIPINFO_PARTNUM_MSM7230_2,  DALCHIPINFO_ID_MSM7230   },
  { DALCHIPINFO_PARTNUM_MSM7230_3,  DALCHIPINFO_ID_MSM7230   },
  { DALCHIPINFO_PARTNUM_MSM7630_0,  DALCHIPINFO_ID_MSM7630   },
  { DALCHIPINFO_PARTNUM_MSM7630_1,  DALCHIPINFO_ID_MSM7630   },
  { DALCHIPINFO_PARTNUM_MSM7630_2,  DALCHIPINFO_ID_MSM7630   },
  { DALCHIPINFO_PARTNUM_MSM7630_3,  DALCHIPINFO_ID_MSM7630   },
  { DALCHIPINFO_PARTNUM_MDM8220,    DALCHIPINFO_ID_MDM8220   },
  { DALCHIPINFO_PARTNUM_MDM9200,    DALCHIPINFO_ID_MDM9200   },
  { DALCHIPINFO_PARTNUM_MDM9600,    DALCHIPINFO_ID_MDM9600   },
  { DALCHIPINFO_PARTNUM_MSM8255_0,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_1,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_2,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_3,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_4,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_5,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8255_6,  DALCHIPINFO_ID_MSM8255   },
  { DALCHIPINFO_PARTNUM_MSM8655_0,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_1,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_2,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_3,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_4,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_5,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8655_6,  DALCHIPINFO_ID_MSM8655   },
  { DALCHIPINFO_PARTNUM_MSM8660_0,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_1,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_2,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_3,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_4,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_5,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_6,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_MSM8660_7,  DALCHIPINFO_ID_MSM8660   },
  { DALCHIPINFO_PARTNUM_QSD8672_0,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_1,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_2,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_3,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_4,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_5,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_6,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_7,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_8,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_QSD8672_9,  DALCHIPINFO_ID_QSD8672   },
  { DALCHIPINFO_PARTNUM_ESM7227,    DALCHIPINFO_ID_ESM7227   },
  { DALCHIPINFO_PARTNUM_APQ8055_0,  DALCHIPINFO_ID_APQ8055   },
  { DALCHIPINFO_PARTNUM_APQ8055_1,  DALCHIPINFO_ID_APQ8055   },
  { DALCHIPINFO_PARTNUM_APQ8055_2,  DALCHIPINFO_ID_APQ8055   },
  { DALCHIPINFO_PARTNUM_APQ8055_3,  DALCHIPINFO_ID_APQ8055   },
  { DALCHIPINFO_PARTNUM_MSM8260_0,  DALCHIPINFO_ID_MSM8260   },
  { DALCHIPINFO_PARTNUM_MSM8260_1,  DALCHIPINFO_ID_MSM8260   },
  { DALCHIPINFO_PARTNUM_APQ8060_0,  DALCHIPINFO_ID_APQ8060   },
  { DALCHIPINFO_PARTNUM_APQ8060_1,  DALCHIPINFO_ID_APQ8060   },
  { DALCHIPINFO_PARTNUM_APQ8060_2,  DALCHIPINFO_ID_APQ8060   },
  { DALCHIPINFO_PARTNUM_APQ8060_3,  DALCHIPINFO_ID_APQ8060   },
  { DALCHIPINFO_PARTNUM_MSM8960_0,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_1,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_2,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_3,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_4,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_5,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_6,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_7,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_8,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_9,  DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_10, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_11, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_12, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_13, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_14, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8960_15, DALCHIPINFO_ID_MSM8960   },
  { DALCHIPINFO_PARTNUM_MSM8660A_0, DALCHIPINFO_ID_MSM8660A  },
  { DALCHIPINFO_PARTNUM_MSM8660A_1, DALCHIPINFO_ID_MSM8660A  },
  { DALCHIPINFO_PARTNUM_MSM8660A_2, DALCHIPINFO_ID_MSM8660A  },
  { DALCHIPINFO_PARTNUM_MSM8660A_3, DALCHIPINFO_ID_MSM8660A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_0, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_1, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_2, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_3, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_4, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_5, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_6, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_7, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_8, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_9, DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_10,DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_MSM8260A_11,DALCHIPINFO_ID_MSM8260A  },
  { DALCHIPINFO_PARTNUM_APQ8060A_0, DALCHIPINFO_ID_APQ8060A  },
  { DALCHIPINFO_PARTNUM_APQ8060A_1, DALCHIPINFO_ID_APQ8060A  },
  { DALCHIPINFO_PARTNUM_APQ8060A_2, DALCHIPINFO_ID_APQ8060A  },
  { DALCHIPINFO_PARTNUM_APQ8060A_3, DALCHIPINFO_ID_APQ8060A  },
  { DALCHIPINFO_PARTNUM_QSC6195,    DALCHIPINFO_ID_QSC6195   },
  { DALCHIPINFO_PARTNUM_QSC6185,    DALCHIPINFO_ID_QSC6185   },
  { DALCHIPINFO_PARTNUM_QSC6175,    DALCHIPINFO_ID_QSC6175   },
  { DALCHIPINFO_PARTNUM_QSC6165,    DALCHIPINFO_ID_QSC6165   },
  { DALCHIPINFO_PARTNUM_QSC6155,    DALCHIPINFO_ID_QSC6155   },
  { DALCHIPINFO_PARTNUM_QSC6295,    DALCHIPINFO_ID_QSC6295   },
  { DALCHIPINFO_PARTNUM_ESC6295,    DALCHIPINFO_ID_ESC6295   },
  { DALCHIPINFO_PARTNUM_QSC6695,    DALCHIPINFO_ID_QSC6695   },
  { DALCHIPINFO_PARTNUM_MDM3000,    DALCHIPINFO_ID_MDM3000   },
  { DALCHIPINFO_PARTNUM_MDM6200,    DALCHIPINFO_ID_MDM6200   },
  { DALCHIPINFO_PARTNUM_MDM6600,    DALCHIPINFO_ID_MDM6600   },
  { DALCHIPINFO_PARTNUM_MDM6210,    DALCHIPINFO_ID_MDM6210   },
  { DALCHIPINFO_PARTNUM_MDM6610,    DALCHIPINFO_ID_MDM6610   },
  { DALCHIPINFO_PARTNUM_MDM6215_0,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_1,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_2,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_3,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_4,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_5,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_6,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6215_7,  DALCHIPINFO_ID_MDM6215   },
  { DALCHIPINFO_PARTNUM_MDM6615_0,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_1,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_2,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_3,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_4,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_5,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_6,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_MDM6615_7,  DALCHIPINFO_ID_MDM6615   },
  { DALCHIPINFO_PARTNUM_QSC6195D2,  DALCHIPINFO_ID_QSC6195D2 },
  { DALCHIPINFO_PARTNUM_MDM9615,    DALCHIPINFO_ID_MDM9615   },
  { DALCHIPINFO_PARTNUM_MDM9615M,   DALCHIPINFO_ID_MDM9615M  },
  { DALCHIPINFO_PARTNUM_MDM8215,    DALCHIPINFO_ID_MDM8215   },
  { DALCHIPINFO_PARTNUM_MDM9215,    DALCHIPINFO_ID_MDM9215   },
  { DALCHIPINFO_PARTNUM_MDM9215M,   DALCHIPINFO_ID_MDM9215M  },
  { DALCHIPINFO_PARTNUM_MSM8930_0,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_1,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_2,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_3,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_4,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_5,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_6,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_7,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_8,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_9,  DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_10, DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8930_11, DALCHIPINFO_ID_MSM8930   },
  { DALCHIPINFO_PARTNUM_MSM8630_0,  DALCHIPINFO_ID_MSM8630   },
  { DALCHIPINFO_PARTNUM_MSM8630_1,  DALCHIPINFO_ID_MSM8630   },
  { DALCHIPINFO_PARTNUM_MSM8230_0,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_MSM8230_1,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_MSM8230_2,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_MSM8230_3,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_MSM8230_4,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_MSM8230_5,  DALCHIPINFO_ID_MSM8230   },
  { DALCHIPINFO_PARTNUM_APQ8030_0,  DALCHIPINFO_ID_APQ8030   },
  { DALCHIPINFO_PARTNUM_APQ8030_1,  DALCHIPINFO_ID_APQ8030   },
  { DALCHIPINFO_PARTNUM_MSM8627,    DALCHIPINFO_ID_MSM8627   },
  { DALCHIPINFO_PARTNUM_MSM8227_0,  DALCHIPINFO_ID_MSM8227   },
  { DALCHIPINFO_PARTNUM_MSM8227_1,  DALCHIPINFO_ID_MSM8227   },
  { DALCHIPINFO_PARTNUM_APQ8064_0,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_1,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_2,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_3,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_4,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_5,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_6,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_APQ8064_7,  DALCHIPINFO_ID_APQ8064   },
  { DALCHIPINFO_PARTNUM_MPQ8062_0,  DALCHIPINFO_ID_MPQ8062   },
  { DALCHIPINFO_PARTNUM_MPQ8062_1,  DALCHIPINFO_ID_MPQ8062   },
  { DALCHIPINFO_PARTNUM_MSM8974_0,  DALCHIPINFO_ID_MSM8974   },
};

#define DALCHIPINFO_ID_MAP_SIZE (sizeof(amPartMap) / sizeof(amPartMap[0]))
/*
 * DalChipInfoDataLUT
 *
 * Array of chip id strings, families and modem support indexed by MSM ID.
 */
static const DalChipInfoDataLUTType DalChipInfoDataLUT[DALCHIPINFO_NUM_IDS] =
{
  { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
  { "MDM1000",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "ESM6235",     DALCHIPINFO_FAMILY_MSM6246,  DALCHIPINFO_MODEM_GSM },
  { "QSC6240",     DALCHIPINFO_FAMILY_QSC6270,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM6245",     DALCHIPINFO_FAMILY_MSM6246,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM6255",     DALCHIPINFO_FAMILY_MSM6280,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM6255A",    DALCHIPINFO_FAMILY_MSM6280,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM6260",     DALCHIPINFO_FAMILY_MSM6260,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM6246",     DALCHIPINFO_FAMILY_MSM6246,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "QSC6270",     DALCHIPINFO_FAMILY_QSC6270,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM6280",     DALCHIPINFO_FAMILY_MSM6280,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM6290",     DALCHIPINFO_FAMILY_MSM6290,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM7200",     DALCHIPINFO_FAMILY_MSM7200,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "MSM7201",     DALCHIPINFO_FAMILY_MSM7200,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS },
  { "ESM7205",     DALCHIPINFO_FAMILY_MSM7200,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESM7206",     DALCHIPINFO_FAMILY_MSM7200,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7200A",    DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7201A",    DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "ESM7205A",    DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESM7206A",    DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESM7225",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7225",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7500",     DALCHIPINFO_FAMILY_MSM7500,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM },
  { "MSM7500A",    DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7525",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7600",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7601",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7625",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7800",     DALCHIPINFO_FAMILY_MSM7800,  DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MDM8200",     DALCHIPINFO_FAMILY_MDM8200,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSD8650",     DALCHIPINFO_FAMILY_QSD8650,  DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MDM8900",     DALCHIPINFO_FAMILY_MDM8200,  0 },
  { "QST1000",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_CGPS },
  { "QST1005",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_CGPS },
  { "QST1100",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "QST1105",     DALCHIPINFO_FAMILY_MSM7600,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "QSD8250",     DALCHIPINFO_FAMILY_QSD8650,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSD8550",     DALCHIPINFO_FAMILY_QSD8650,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "QSD8850",     DALCHIPINFO_FAMILY_QSD8650,  DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MDM2000",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QST1500",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_CGPS },
  { "QST1600",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "QST1700",     DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7227",     DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7627",     DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSC6165",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_1X },
  { "QSC6175",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_1XEVDO },
  { "QSC6185",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_EHRPD },
  { "QSC6195",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_EHRPD },
  { "QSC6285",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM },
  { "QSC6295",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "QSC6695",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_1XEVDO_REVB | DALCHIPINFO_MODEM_EHRPD | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESM6246",     DALCHIPINFO_FAMILY_MSM6246,  DALCHIPINFO_MODEM_GSM },
  { "ESM6290",     DALCHIPINFO_FAMILY_MSM6290,  DALCHIPINFO_MODEM_GSM },
  { "ESC6270",     DALCHIPINFO_FAMILY_QSC6270,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESC6240",     DALCHIPINFO_FAMILY_QSC6270,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MDM8220",     DALCHIPINFO_FAMILY_MDM9X00,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_GNSS },
  { "MDM9200",     DALCHIPINFO_FAMILY_MDM9X00,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_GNSS | DALCHIPINFO_MODEM_LTE },
  { "MDM9600",     DALCHIPINFO_FAMILY_MDM9X00,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_GNSS | DALCHIPINFO_MODEM_LTE },
  { "MSM7630",     DALCHIPINFO_FAMILY_MSM7X30,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MSM7230",     DALCHIPINFO_FAMILY_MSM7X30,  DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "ESM7227",     DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7625-1",   DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_1X | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7225-1",   DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSD8250A",    DALCHIPINFO_FAMILY_QSD8650A, DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSD8650A",    DALCHIPINFO_FAMILY_QSD8650A, DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MSM7625-2",   DALCHIPINFO_FAMILY_MSM7625,  DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7227-1",   DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM7627-1",   DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_1X | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM7627-2",   DALCHIPINFO_FAMILY_MSM7627,  DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM8260",     DALCHIPINFO_FAMILY_MSM8X60,  DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM8660",     DALCHIPINFO_FAMILY_MSM8X60,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MDM8200A",    DALCHIPINFO_FAMILY_MDM8200A, DALCHIPINFO_MODEM_1XEVDO_REVA | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "QSC6155",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_1X | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MSM8255",     DALCHIPINFO_FAMILY_MSM7X30,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_CGPS },
  { "MSM8655",     DALCHIPINFO_FAMILY_MSM7X30,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "ESC6295",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM },
  { "MDM3000",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM },
  { "MDM6200",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS },
  { "MDM6600",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MDM6210",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MDM6610",     DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "QSD8672",     DALCHIPINFO_FAMILY_QSD8672,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "MDM6215",     DALCHIPINFO_FAMILY_MDM6615,  DALCHIPINFO_MODEM_UMTS | DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS},
  { "MDM6615",     DALCHIPINFO_FAMILY_MDM6615,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS },
  { "APQ8055",     DALCHIPINFO_FAMILY_MSM7X30,  DALCHIPINFO_MODEM_CGPS },
  { "APQ8060",     DALCHIPINFO_FAMILY_MSM8X60,  DALCHIPINFO_MODEM_CGPS },
  { "MSM8960",     DALCHIPINFO_FAMILY_MSM8960,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM7225A",    DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7625A",    DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7227A",    DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "MSM7627A",    DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "ESM7227A",    DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "QSC6195-2",   DALCHIPINFO_FAMILY_QSC6695,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_1XEVDO_REVB },
  { "FSM9200",     DALCHIPINFO_FAMILY_MDM9X00,  0 },
  { "FSM9800",     DALCHIPINFO_FAMILY_MDM9X00,  0 },
  { "MSM7225AD1",  DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7227AD1",  DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "MSM7225AA",   DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7225AAD1", DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7625AA",   DALCHIPINFO_FAMILY_MSM7625,  0 },
  { "MSM7227AA",   DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "MSM7227AAD1", DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "MSM7627AA",   DALCHIPINFO_FAMILY_MSM7627,  0 },
  { "MDM9615",     DALCHIPINFO_FAMILY_MDM9X15,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_LTE },
  { "MDM9615M",    DALCHIPINFO_FAMILY_MDM9X15,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_LTE },
  { "MDM8215",     DALCHIPINFO_FAMILY_MDM9X15,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_1XEVDO | DALCHIPINFO_MODEM_LTE },
  { "MDM9215",     DALCHIPINFO_FAMILY_MDM9X15,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MDM9215M",    DALCHIPINFO_FAMILY_MDM9X15,  DALCHIPINFO_MODEM_GSM | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "APQ8064",     DALCHIPINFO_FAMILY_MSM8X60,  0 },
  { "MSM8930",     DALCHIPINFO_FAMILY_MSM8930,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM8630",     DALCHIPINFO_FAMILY_MSM8630,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM8230",     DALCHIPINFO_FAMILY_MSM8230,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "APQ8030",     DALCHIPINFO_FAMILY_APQ8030,  0 },
  { "MSM8627",     DALCHIPINFO_FAMILY_MSM8627,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM8227",     DALCHIPINFO_FAMILY_MSM8227,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM8660A",    DALCHIPINFO_FAMILY_MSM8960,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "MSM8260A",    DALCHIPINFO_FAMILY_MSM8960,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },
  { "APQ8060A",    DALCHIPINFO_FAMILY_MSM8960,  0 },
  { "MPQ8062",     DALCHIPINFO_FAMILY_MSM8X60,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "UNKNOWN",     DALCHIPINFO_FAMILY_UNKNOWN,  0 },
 { "MSM8974",     DALCHIPINFO_FAMILY_MSM8974,  DALCHIPINFO_MODEM_WWAN | DALCHIPINFO_MODEM_CGPS | DALCHIPINFO_MODEM_LTE },

};

/* -----------------------------------------------------------------------
**                           FUNCTIONS
** ----------------------------------------------------------------------- */

/* ===========================================================================
**  ChipInfo_GetFamily
**
** ======================================================================== */

void ChipInfo_GetFamily
(
  ChipInfoDrvCtxt       *pCtxt,
  DalChipInfoFamilyType *peFamily,
  uint32                pHWRevNum
)
{
  DalChipInfoIdType ePart;

  /*
   * Read part number from hardware.
   */
  ChipInfo_GetPart(pCtxt, &ePart, pHWRevNum);

  /*
   * Look up family.
   */
  if (ePart < DALCHIPINFO_NUM_IDS)
  {
    *peFamily = DalChipInfoDataLUT[ePart].nFamily;
  }
  else
  {
    *peFamily = DALCHIPINFO_FAMILY_UNKNOWN;
  }

} /* END ChipInfo_GetFamily */


/* ===========================================================================
**  ChipInfo_GetFamilyByPart
**
** ======================================================================== */

void ChipInfo_GetFamilyByPart
(
  DalChipInfoIdType    ePart,
  DalChipInfoFamilyType *peFamily
)
{
  /*
   * Look up family.
   */
  if (ePart < DALCHIPINFO_NUM_IDS)
  {
    *peFamily = DalChipInfoDataLUT[ePart].nFamily;
  }
  else
  {
    *peFamily = DALCHIPINFO_FAMILY_UNKNOWN;
  }

} /* END ChipInfo_GetFamilyByPart */


/* ===========================================================================
**  ChipInfo_GetPart
**
** ======================================================================== */

void ChipInfo_GetPart
(
  ChipInfoDrvCtxt     *pCtxt,
  DalChipInfoIdType   *pePart,
  uint32              pHWRevNum
)
{
  uint32 nPart, n;

  /*
   * Read the part number.
   */
  ChipInfo_GetRawPart(pCtxt, &nPart, pHWRevNum);

  /*
   * Look up using the table.
   */
  for (n = 0; n < DALCHIPINFO_ID_MAP_SIZE; n++)
  {
    if (nPart == amPartMap[n].nPart)
    {
      *pePart = amPartMap[n].ePart;
      break;
    }
  }

  if (n == DALCHIPINFO_ID_MAP_SIZE)
  {
    *pePart = DALCHIPINFO_ID_UNKNOWN;
  }

} /* END ChipInfo_GetPart */


/* ===========================================================================
**  ChipInfo_GetVersion
**
** ======================================================================== */

void ChipInfo_GetVersion
(
  ChipInfoDrvCtxt        *pCtxt,
  DalChipInfoVersionType *pnVersion,
  uint32                 pHWRevNum
)
{
  DalChipInfoFamilyType eFamily;
  uint32 nVersion;

  ChipInfo_GetRawVersion(pCtxt,&nVersion, pHWRevNum);
  /*
   * Get the chip family to know how to interpret the MSM version.
   */
  ChipInfo_GetFamily(pCtxt, &eFamily, pHWRevNum);

  switch (eFamily)
  {
    /*
     * 8650
     */
    case DALCHIPINFO_FAMILY_QSD8650:
    {
      switch (nVersion)
      {
        case 0:  *pnVersion = DALCHIPINFO_VERSION(1, 0); break;
        case 1:  *pnVersion = DALCHIPINFO_VERSION(1, 2); break;
        case 2:  *pnVersion = DALCHIPINFO_VERSION(2, 0); break;
        default: *pnVersion = DALCHIPINFO_VERSION(2, nVersion - 2); break;
      }
      break;
    }

    /*
     * 7x30
     */
    case DALCHIPINFO_FAMILY_MSM7X30:
    {
      switch (nVersion)
      {
        case 0:  *pnVersion = DALCHIPINFO_VERSION(1, 0); break;
        case 1:  *pnVersion = DALCHIPINFO_VERSION(2, 0); break;
        default: *pnVersion = DALCHIPINFO_VERSION(2, nVersion - 1); break;
      }
      break;
    }
    case DALCHIPINFO_FAMILY_MDM9X00:
    {
      switch (nVersion)
      {
        case 0:  *pnVersion = DALCHIPINFO_VERSION(1, nVersion); break;
        case 1:  *pnVersion = DALCHIPINFO_VERSION(1, nVersion); break;
        case 2:  *pnVersion = DALCHIPINFO_VERSION(2, 0); break;
        default: *pnVersion = DALCHIPINFO_VERSION(2, nVersion - 1); break;
      }
      break;
    }
    case DALCHIPINFO_FAMILY_MSM8660:
    {
      switch (nVersion)
      {
        case 0:  *pnVersion = DALCHIPINFO_VERSION(1, 0); break;
        case 1:  *pnVersion = DALCHIPINFO_VERSION(2, 0); break;
        default: *pnVersion = DALCHIPINFO_VERSION(2, nVersion - 1); break;
      }
      break;
    }
    case DALCHIPINFO_FAMILY_MSM8960:
    {
      switch (nVersion)
      {
        case 0:  *pnVersion = DALCHIPINFO_VERSION(1, 0); break;
        case 1:  *pnVersion = DALCHIPINFO_VERSION(1, 1); break;
        case 2:  *pnVersion = DALCHIPINFO_VERSION(2, 0); break;
        case 4:  *pnVersion = DALCHIPINFO_VERSION(3, 1); break;
        default: *pnVersion = DALCHIPINFO_VERSION(3, nVersion - 3); break;
      }
      break;
    }
    /*
     * Default map.
     */
    default:
    {
      *pnVersion = DALCHIPINFO_VERSION(1, nVersion);
      break;
    }
  }

} /* END ChipInfo_GetVersion */


/* ===========================================================================
**  ChipInfo_GetManufacturer
**
** ======================================================================== */

void ChipInfo_GetManufacturer
(
  ChipInfoDrvCtxt             *pCtxt,
  DalChipInfoManufacturerType *peManufacturer,
  uint32                      pHWRevNum
)
{
  uint32 pnRawManufacturer;

  ChipInfo_GetRawManufacturer(pCtxt, &pnRawManufacturer, pHWRevNum);
  switch(pnRawManufacturer)
    {
    case DALCHIPINFO_MFGNUM_QUALCOMM:
    {
      *peManufacturer = DALCHIPINFO_MFG_QUALCOMM;
      break;
    }

    default:
    {
      *peManufacturer = DALCHIPINFO_MFG_UNKNOWN;
      break;
    }
  }

} /* END ChipInfo_GetManufacturer */


/* ===========================================================================
**  ChipInfo_GetRawManufacturer
**
** ======================================================================== */

void ChipInfo_GetRawManufacturer
(
  ChipInfoDrvCtxt     *pCtxt,
  uint32 *pnRawManufacturer,
  uint32 pHWRevNum
)
{

  uint32 mfgIdBmsk, mfgIdShft;
  DALSYSPropertyVar PropVar;


  DALSYS_GetPropertyValue(pCtxt->hProps,"QUALCOMM_MFG_ID_BMSK",0,&PropVar);
  mfgIdBmsk = PropVar.Val.dwVal;

  DALSYS_GetPropertyValue(pCtxt->hProps,"QUALCOMM_MFG_ID_SHFT",0,&PropVar);
  mfgIdShft = PropVar.Val.dwVal;

  *pnRawManufacturer = (pHWRevNum & mfgIdBmsk) >> mfgIdShft;

} /* END ChipInfo_GetRawManufacturer */


/* ===========================================================================
**  ChipInfo_GetRawPart
**
** ======================================================================== */

void ChipInfo_GetRawPart
(
  ChipInfoDrvCtxt     *pCtxt,
  uint32 *pnRawPart,
  uint32 pHWRevNum
)
{

  uint32 partNumBmsk, partNumShft;
  DALSYSPropertyVar PropVar;

  DALSYS_GetPropertyValue(pCtxt->hProps,"PARTNUM_BMSK",0,&PropVar);
  partNumBmsk = PropVar.Val.dwVal;

  DALSYS_GetPropertyValue(pCtxt->hProps,"PARTNUM_SHFT",0,&PropVar);
  partNumShft = PropVar.Val.dwVal;

  *pnRawPart = (pHWRevNum & partNumBmsk) >> partNumShft;

} /* END ChipInfo_GetRawPart */


/* ===========================================================================
**  ChipInfo_GetRawVersion
**
** ======================================================================== */

void ChipInfo_GetRawVersion
(
  ChipInfoDrvCtxt     *pCtxt,
  uint32 *pnRawVersion,
  uint32 pHWRevNum
)
{
  uint32 versionIdBmsk, versionIdShft;
  DALSYSPropertyVar PropVar;

  DALSYS_GetPropertyValue(pCtxt->hProps,"VERSION_ID_BMSK",0,&PropVar);
  versionIdBmsk = PropVar.Val.dwVal;

  DALSYS_GetPropertyValue(pCtxt->hProps,"VERSION_ID_SHFT",0,&PropVar);
  versionIdShft = PropVar.Val.dwVal;

  *pnRawVersion = (pHWRevNum & versionIdBmsk) >> versionIdShft;

} /* END ChipInfo_GetRawVersion */



/*=========================================================================
      Implementation
==========================================================================*/


/*==========================================================================

  FUNCTION      ChipInfo_DriverInit

  DESCRIPTION   See DDIChip.h

==========================================================================*/

DALResult ChipInfo_DriverInit
(
  ChipInfoDrvCtxt     *pCtxt
)
{
  DALResult eResult = DAL_SUCCESS;
  DALSYSPropertyVar PropVar;
  uint32 nHWIORegAddr = 0;
  uint32 nHWRevNum;
  uint32 pPhysAddress;
    
  /* Get the property handle */
  DALSYS_GetDALPropertyHandle(DALDEVICEID_CHIPINFO,pCtxt->hProps);

  DALSYS_GetPropertyValue(pCtxt->hProps,"HWREVNUM_PHYS_ADDR",0,&PropVar);
  pPhysAddress = PropVar.Val.dwVal;

  /*-----------------------------------------------------------------------*/
  /* Attach to the HWIO DAL.                                               */
  /*-----------------------------------------------------------------------*/
  eResult = DAL_DeviceAttach(DALDEVICEID_HWIO, &pCtxt->phDalHWIO);
  if (eResult == DAL_SUCCESS)
  {
     eResult = DalHWIO_MapRegionByAddress(pCtxt->phDalHWIO, (uint8*)pPhysAddress,(uint8 **)&nHWIORegAddr);
  }
  else
  {
    nHWIORegAddr = pPhysAddress;
  }
  DALSYS_GetPropertyValue(pCtxt->hProps,"HWREVNUM_OFFSET",0,&PropVar);
  nHWIORegAddr = PropVar.Val.dwVal  + nHWIORegAddr;

  nHWRevNum = 0X007B00E1;

  /*-----------------------------------------------------------------------*/
  /* Read chip information from HW.                                        */
  /*-----------------------------------------------------------------------*/

  ChipInfo_GetVersion(pCtxt,(DalChipInfoVersionType *)&pCtxt->nChipVersion, nHWRevNum);
  ChipInfo_GetPart(pCtxt,(DalChipInfoIdType *)&pCtxt->eChipId, nHWRevNum);
  ChipInfo_GetRawVersion(pCtxt,&pCtxt->nRawChipVersion, nHWRevNum);
  ChipInfo_GetRawPart(pCtxt,&pCtxt->nRawChipId, nHWRevNum);
  ChipInfo_GetFamily(pCtxt,(DalChipInfoFamilyType *)&pCtxt->eChipFamily, nHWRevNum);

  /*-----------------------------------------------------------------------*/
  /* Check for override of the ChipId from the properties.                 */
  /*-----------------------------------------------------------------------*/

  if (pCtxt->eChipId == DALCHIPINFO_ID_UNKNOWN)
  {
    eResult = DALSYS_GetPropertyValue(pCtxt->hProps, "ChipIdOverride", 0, &PropVar);

    if (eResult == DAL_SUCCESS)
    {
      pCtxt->eChipId = (DalChipInfoIdType)PropVar.Val.dwVal;

      ChipInfo_GetFamilyByPart(
        (DalChipInfoIdType)pCtxt->eChipId,
        (DalChipInfoFamilyType *)&pCtxt->eChipFamily);
    }
  }

  /*-----------------------------------------------------------------------*/
  /* Fill in derived information.                                          */
  /*-----------------------------------------------------------------------*/

  pCtxt->nModemSupport = DalChipInfoDataLUT[pCtxt->eChipId].nModem;
  strlcpy(
    pCtxt->szChipIdString, DalChipInfoDataLUT[pCtxt->eChipId].szChipId,
    DALCHIPINFO_MAX_ID_LENGTH);


  /*-----------------------------------------------------------------------*/
  /* Success.                                                              */
  /*-----------------------------------------------------------------------*/

  return DAL_SUCCESS;

} /* END ChipInfo_DriverInit */


/*==========================================================================

  FUNCTION      ChipInfo_DriverDeInit

  DESCRIPTION   See DDIChip.h

==========================================================================*/

DALResult ChipInfo_DriverDeInit
(
  ChipInfoDrvCtxt *pCtxt
)
{
  if (pCtxt->phDalHWIO != NULL)
  {
    DalDevice_Close(pCtxt->phDalHWIO);
  }

  /*-----------------------------------------------------------------------*/
  /* Success.                                                              */
  /*-----------------------------------------------------------------------*/

  return DAL_SUCCESS;

} /* END ChipInfo_DriverDeInit */


