/******************************************************************************
  @file    ds_profile_3gpp_modem.c
  @brief   

  DESCRIPTION
  Tech specific implementation of 3GPP Profile Management  

  INITIALIZATION AND SEQUENCING REQUIREMENTS
  N/A

  ---------------------------------------------------------------------------
  Copyright (C) 2009 - 2016 Qualcomm Technologies Incorporated.
  All Rights Reserved. QUALCOMM Proprietary and Confidential.
  ---------------------------------------------------------------------------
****************************************************************************/
/*===========================================================================

                        EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.

  $Header: //commercial/MPSS.JO.2.0.c1.4/Main/modem_proc/datamodem/3gpp/dsprofile/src/ds_profile_3gpp_modem.c#1 $ $DateTime: 2016/12/13 08:00:03 $ $Author: mplcsds1 $

when       who     what, where, why
--------   ---     ----------------------------------------------------------
11/27/12   vs      Removed ds_profile ENTRY and EXIT log messages
09/13/11   ttv     Changes to add src_stat_desc as profile parameter.
07/27/11   ttv     Added changes required for source statistics descriptor
                   addition.
05/31/11   rr      Added support for transient profiles
04/13/11   ttv     Added changes to pass v4v6 to set all profile data to 
                   default function.
02/28/11   hs      Added changes to support APN class in profile
02/16/11   ttv     Added DSDS changes for consolidated profile family.
01/26/11   ars     Added support for apn_disabled_flag and inactivity_timer_val
01/17/11   ss      Added support for Iface linger.
07/14/10   sa      Added reset support for UMTS_MIN_QOS_EXTENDED and 
                   UMTS_REQ_QOS_EXTENDED.
06/21/10   vk      Support for apn based profile search
05/17/10   hs      Added APN disable and PDN inactivity feature support.
04/30/10   ars     Made modem_mem_alloc/free and str fns platform independent
01/04/10   vk      Removing certain macros from PDP reg API header file
                   that cause problems with autogenerated RPC stub code
10/15/09   vk      Added support for LTE params
09/30/09   mg      Created the module. First version of the file.
===========================================================================*/
#include "datamodem_variation.h"
#include "dsumtspdpreg.h"
#include "ds_profile_3gppi.h"
#include "ds_profile_os.h"
#include "ds_util.h"
#include "amssassert.h"
#include "ds_profile_db.h"
#include "ds_3gpp_profile_cache_hdlr.h"
#include "dsumts_subs_mgr.h"
#include "ds_3gpp_profile_validator.h"
#include "ds_profile_db_internal.h"
#include "ds_profile_db_handler.h" 
#include "dsumtspdpregint.h"
#include "ds_3gpp_profile_api.h"

/*----------------------------------------------------------------------- 
  GLOBAL/STATIC VARIABLES
  -----------------------------------------------------------------------*/

  /* ------------------------------------------------------------------
     Boolean variable to know if a command needs to be posted to MH for
     APN param change processing
  ---------------------------------------------------------------------*/
static boolean ds_profile_apn_param_changed = FALSE;

/*-------------------------------------------------------------------------
  These macros used to be in dsumtspdpreg.h but had to removed from there 
  due to compilation issues seen with pdp reg rpc stub code.
-------------------------------------------------------------------------*/
#define pdp_addr_ipv4 pdp_addr.pdp_addr_ipv4
#define pdp_addr_ipv6 pdp_addr.pdp_addr_ipv6

typedef struct 
{
  ds_profile_db_ident_type  ident;

  void(*write_fn)(
    ds_profile_num_type   num,
    const ds_profile_db_3gpp_tech_params_type *ds_3gpp_tech_params_ptr,
    const ds_profile_db_gen_params_type       *gen_params,
    ds_profile_db_supported_tech_mask tech_mask
  );

  validate_3gpp_fn_type validate_fn;

}dsi_profile_3gpp_fn_tbl_type;

/*lint -save -e641*/
/*===========================================================================
  Table for identifier and its correponding write and validate function  
===========================================================================*/

static dsi_profile_3gpp_fn_tbl_type ds_profile_3gpp_fn_tbl[] = {

  {(ds_profile_identifier_type)
      INVALID_PROFILE_PARAM,
  NULL,
  NULL},


  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_TYPE,
  ds_3gpp_profile_cache_write_pdp_type,
  ds_3gpp_profile_validate_pdp_type},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_H_COMP,
  ds_3gpp_profile_cache_write_pdp_context_h_comp,
  ds_3gpp_profile_validate_h_comp},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_D_COMP,
  ds_3gpp_profile_cache_write_pdp_context_d_comp,
  NULL},

  {(ds_profile_identifier_type)
      INVALID_PROFILE_PARAM,
  NULL,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_DNS_ADDR_V4_PRIMARY,
  ds_3gpp_profile_cache_write_v4_dns_addr_primary,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_DNS_ADDR_V4_SECONDARY,
  ds_3gpp_profile_cache_write_v4_dns_addr_secondary,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_UMTS_REQ_QOS_EXTENDED,
  ds_3gpp_profile_cache_write_umts_qos_req_extended,
  ds_3gpp_profile_validate_umts_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_UMTS_MIN_QOS_EXTENDED,
  ds_3gpp_profile_cache_write_umts_qos_min_extended,
  ds_3gpp_profile_validate_umts_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_GPRS_REQ_QOS,
  ds_3gpp_profile_cache_write_gprs_qos_req,
  ds_3gpp_profile_validate_gprs_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_GPRS_MIN_QOS,
  ds_3gpp_profile_cache_write_gprs_qos_min,
  ds_3gpp_profile_validate_gprs_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_AUTH_USERNAME,
  ds_3gpp_profile_cache_write_auth_username,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_AUTH_PASSWORD,
  ds_3gpp_profile_cache_write_auth_password,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_AUTH_TYPE,
  ds_3gpp_profile_cache_write_auth_type,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_ADDR_V4,
  ds_3gpp_profile_cache_write_pdp_context_v4_pdp_addr,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PCSCF_REQ_FLAG,
  ds_3gpp_profile_cache_write_request_pcscf_address_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_TE_MT_ACCESS_CTRL_FLAG,
  ds_3gpp_profile_cache_write_access_ctrl_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PCSCF_DHCP_REQ_FLAG,
  ds_3gpp_profile_cache_write_request_pcscf_address_using_dhcp_flag,
  NULL},                   
                          
  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_IM_CN_FLAG,
  ds_3gpp_profile_cache_write_im_cn_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_TFT_FILTER_ID1,
  ds_3gpp_profile_cache_write_tft_filter_id1,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_TFT_FILTER_ID2,
  ds_3gpp_profile_cache_write_tft_filter_id2,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_NUMBER,
  ds_3gpp_profile_cache_write_pdp_context_number,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_SECONDARY_FLAG,
  ds_3gpp_profile_cache_write_pdp_context_secondary_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PRIMARY_ID,
  ds_3gpp_profile_cache_write_pdp_context_primary_id,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_ADDR_V6,
  ds_3gpp_profile_cache_write_pdp_context_v6_pdp_addr,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_UMTS_REQ_QOS,
  ds_3gpp_profile_cache_write_umts_qos_req,
  ds_3gpp_profile_validate_umts_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_UMTS_MIN_QOS,
  ds_3gpp_profile_cache_write_umts_qos_min,
  ds_3gpp_profile_validate_umts_qos_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_DNS_ADDR_V6_PRIMARY,
  ds_3gpp_profile_cache_write_v6_dns_addr_primary,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_DNS_ADDR_V6_SECONDARY,
  ds_3gpp_profile_cache_write_v6_dns_addr_secondary,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_IPV4_ADDR_ALLOC,
  ds_3gpp_profile_cache_write_pdp_context_ipv4_addr_alloc,
  NULL},

#ifdef FEATURE_DATA_LTE
  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_LTE_REQ_QOS,
  ds_3gpp_profile_cache_write_lte_qos_req,
  ds_3gpp_profile_validate_lte_qos_params},
#else
  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_LTE_REQ_QOS,
  NULL,
  NULL},
#endif

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_APN_DISABLE_FLAG,
  ds_3gpp_profile_cache_write_apn_disable_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_INACTIVITY_TIMER_VAL,
  ds_3gpp_profile_cache_write_inactivity_timer_val,
  ds_3gpp_profile_validate_inactivity_timer_val},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_APN_CLASS,
  ds_3gpp_profile_cache_write_apn_class,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_LINGER_PARAMS,
  ds_3gpp_profile_cache_write_linger_params,
  ds_3gpp_profile_validate_linger_params},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_SRC_STAT_DESC_REQ,
  ds_3gpp_profile_cache_write_src_stat_desc_req,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_SRC_STAT_DESC_MIN,
  ds_3gpp_profile_cache_write_src_stat_desc_min,
  ds_3gpp_profile_validate_src_stat_desc},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_APN_BEARER,
  ds_3gpp_profile_cache_write_apn_bearer,
  ds_3gpp_profile_validate_apn_bearer},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_EMERGENCY_CALLS_SUPPORTED,
  ds_3gpp_profile_cache_write_emergency_flag,
  NULL},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_OPERATOR_RESERVED_PCO,
  ds_3gpp_profile_cache_write_operartor_reserved_pco,
  ds_3gpp_profile_validate_operator_pco},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_MCC,
  ds_3gpp_profile_cache_write_mcc,
  ds_3gpp_profile_validate_mcc},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_MNC,
  ds_3gpp_profile_cache_write_mnc,
  ds_3gpp_profile_validate_mnc},

  {(ds_profile_identifier_type)
  TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_PER_BLOCK,
  ds_3gpp_profile_cache_write_max_pdn_conn_per_block, 
  ds_3gpp_profile_validate_max_pdn_conn_per_blk},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_TIMER,
  ds_3gpp_profile_cache_write_pdn_conn_timer,
  ds_3gpp_profile_validate_max_pdn_conn_time},

  {(ds_profile_identifier_type)
      TECH_3GPP_PROFILE_PARAM_PDN_REQ_WAIT_TIMER,
  ds_3gpp_profile_cache_write_pdn_req_wait_timer,
  ds_3gpp_profile_validate_max_pdn_req_wait_time},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_USER_APP_DATA,
   ds_3gpp_profile_cache_write_user_app_data,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_ROAMING_DISALLOWED,
  ds_3gpp_profile_cache_write_roaming_disallowed,
  NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_PDN_DISCON_WAIT_TIME,
   ds_3gpp_profile_cache_write_pdn_discon_wait_time,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_DNS_DHCP_REQ_FLAG,
   ds_3gpp_profile_cache_write_request_dns_address_using_dhcp_flag,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_LTE_ROAMING_PDP_TYPE,
   ds_3gpp_profile_cache_write_lte_roaming_pdp_type,
   ds_3gpp_profile_validate_roaming_pdp_type},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_UMTS_ROAMING_PDP_TYPE,
   ds_3gpp_profile_cache_write_umts_roaming_pdp_type,
   ds_3gpp_profile_validate_roaming_pdp_type},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_IWLAN_TO_LTE_ROAMING_HO_FLAG,
   ds_3gpp_profile_cache_write_roaming_ho_iwlan_to_lte,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_LTE_TO_IWLAN_ROAMING_HO_FLAG,
   ds_3gpp_profile_cache_write_roaming_ho_lte_to_iwlan,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_FAILURE_TIMERS,
   ds_3gpp_profile_cache_write_failure_timer,
   NULL},

  {(ds_profile_identifier_type)
   TECH_3GPP_PROFILE_PARAM_OVERRIDE_HOME_PDP_TYPE,
   ds_3gpp_profile_cache_write_override_home_pdp_type,
    NULL},

  {(ds_profile_identifier_type)
   GENERAL_PROFILE_PARAM_PROFILE_NAME,
   ds_3gpp_profile_cache_write_profile_name,      
   NULL},

  /* index = 46*/
  {(ds_profile_identifier_type)
      GENERAL_PROFILE_PARAM_APN_NAME,
  ds_3gpp_profile_cache_write_pdp_context_apn,
  NULL},

  {(ds_profile_identifier_type)
      GENERAL_PROFILE_PARAM_SUBS_ID,
    ds_3gpp_profile_cache_write_subscription_id,
    NULL},

  {(ds_profile_identifier_type)
    GENERAL_PROFILE_PARAM_IPV6_DELEGATION,
    ds_3gpp_profile_cache_write_ipv6_delegation,      
    NULL},

  {(ds_profile_identifier_type)
    GENERAL_PROFILE_PARAM_CLAT_ENABLE_FLAG,
    ds_3gpp_profile_cache_write_clat_enabled,
    NULL},

  {(ds_profile_identifier_type)
    COMMON_TECH_PROFILE_PARAM_PCSCF_DHCP_REQ_FLAG,
    ds_3gpp_profile_cache_write_request_pcscf_address_using_dhcp_flag,
    NULL},

  {(ds_profile_identifier_type)
    COMMON_TECH_PROFILE_PARAM_DNS_DHCP_REQ_FLAG,
    ds_3gpp_profile_cache_write_request_dns_address_using_dhcp_flag,
    NULL},
  
  {(ds_profile_identifier_type)
    COMMON_TECH_PROFILE_PARAM_PDP_TYPE,
    ds_3gpp_profile_cache_write_pdp_type,
    ds_3gpp_profile_validate_pdp_type},

  {(ds_profile_identifier_type)
   COMMON_TECH_PROFILE_PARAM_USER_APP_DATA,
   ds_3gpp_profile_cache_write_user_app_data,      
   NULL},

  {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_MNC,
  ds_3gpp_profile_cache_write_mcc,
  ds_3gpp_profile_validate_mcc},

  {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_MCC,
  ds_3gpp_profile_cache_write_mnc,
  ds_3gpp_profile_validate_mnc},

  /* index = 50*/
    {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_OPERATOR_RESERVED_PCO,
  ds_3gpp_profile_cache_write_operartor_reserved_pco,
  ds_3gpp_profile_validate_operator_pco},

    {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_AUTH_PASSWORD,
    ds_3gpp_profile_cache_write_auth_password,
    NULL},

        {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_AUTH_USERNAME,
    ds_3gpp_profile_cache_write_auth_username,
    NULL},

    {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_AUTH_TYPE,
    ds_3gpp_profile_cache_write_auth_type,
    NULL},

    {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_PCSCF_REQ_FLAG,
    ds_3gpp_profile_cache_write_request_pcscf_address_flag,
    NULL},

    {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_LINGER_PARAMS,
    ds_3gpp_profile_cache_write_linger_params,
    ds_3gpp_profile_validate_linger_params},

    {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_DNS_ADDR_V6_SECONDARY,
      ds_3gpp_profile_cache_write_v6_dns_addr_secondary,
      NULL},

    {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_DNS_ADDR_V6_PRIMARY,
      ds_3gpp_profile_cache_write_v6_dns_addr_primary,
      NULL},

    {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_DNS_ADDR_V4_SECONDARY,
      ds_3gpp_profile_cache_write_v4_dns_addr_secondary,
      NULL},

    {(ds_profile_identifier_type)
     COMMON_TECH_PROFILE_PARAM_DNS_ADDR_V4_PRIMARY,
      ds_3gpp_profile_cache_write_v4_dns_addr_primary,
      NULL},


    {(ds_profile_identifier_type)
        COMMON_TECH_PROFILE_PARAM_APN_CLASS,
    ds_3gpp_profile_cache_write_apn_class,
    NULL},

     {(ds_profile_identifier_type)
      COMMON_TECH_PROFILE_PARAM_APN_DISABLE_FLAG,
      ds_3gpp_profile_cache_write_apn_disable_flag,
      NULL},

};

/*===========================================================================
FUNCTION dsi_profile_set_if_ident_apn_param

DESCRIPTION
  This function checks if the identifier passed is one of apn parameters
  and sets apn_param_changed if it is an apn_param
 
PARAMETERS 
  ident:                paramter that got changed
  
DEPENDENCIES 
  
RETURN VALUE 
  TRUE  -- if the changed ident is an apn_param
  FALSE -- Otherwise
  
SIDE EFFECTS 
  
===========================================================================*/
boolean dsi_profile_set_if_ident_apn_param
(
   ds_profile_db_ident_type               ident
)
{
  boolean               ret_val = FALSE;
 /*- - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - - - */
  switch (ident)
  {
     case TECH_3GPP_PROFILE_PARAM_APN_DISABLE_FLAG:
     case GENERAL_PROFILE_PARAM_APN_NAME:
     case TECH_3GPP_PROFILE_PARAM_PDN_REQ_WAIT_TIMER:
     case TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_PER_BLOCK:
     case TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_TIMER:
     case TECH_3GPP_PROFILE_PARAM_APN_BEARER:
     case TECH_3GPP_PROFILE_PARAM_APN_CLASS:
     case TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_TYPE:
     case COMMON_TECH_PROFILE_PARAM_PDP_TYPE :
     case COMMON_TECH_PROFILE_PARAM_APN_CLASS:
     case COMMON_TECH_PROFILE_PARAM_APN_DISABLE_FLAG:
       ret_val = TRUE;
       ds_profile_apn_param_changed = TRUE;
       break;
     
     default:
       break;
  }
  
  DS_3GPP_MSG1_MED("3gpp_is_apn_param: %d",ret_val);
  return ret_val;
}


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_GET_APN_PARAM_CHANGED

DESCRIPTION
  This function returns apn_param_changed

PARAMETERS 
  void

DEPENDENCIES 
  
RETURN VALUE 
  TRUE         If apn_params has changed
  FALSE        Otherwise
 
SIDE EFFECTS 
  
===========================================================================*/
boolean dsi_profile_3gpp_get_apn_changed_param
( 
  void
)
{
 /*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/
  DS_3GPP_MSG1_MED("APN param changed:%d",ds_profile_apn_param_changed);
  return ds_profile_apn_param_changed;

}

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_RESET_APN_PARAM_CHANGED

DESCRIPTION
  This function resets apn_param_changed

PARAMETERS 
  void

DEPENDENCIES 
  
RETURN VALUE 
void 
 
SIDE EFFECTS 
  
===========================================================================*/
void dsi_profile_3gpp_reset_apn_changed_param
( 
  void
)
{
 /*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/
  
  ds_profile_apn_param_changed = FALSE;
  DS_3GPP_MSG1_MED("APN param changed:%d",ds_profile_apn_param_changed);
}


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_GET_INDEX_FROM_IDENT

DESCRIPTION
  This function gets index for the identifier to index into the function table.

PARAMETERS 
  ident : identifier for which index is to be returned

DEPENDENCIES 
  
RETURN VALUE 
  returns index
SIDE EFFECTS 
  
===========================================================================*/
int8 dsi_profile_3gpp_modem_get_index_from_ident( 
  ds_profile_db_ident_type ident
)
{
  int8 index = -1;
/*- - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/
  //TODO : Change it have for loop to go over the table and get the ident validate function.
  if ((ident >= TECH_3GPP_PROFILE_PARAM_MIN) && (ident <= TECH_3GPP_PROFILE_PARAM_MAX))
  {
    index = ident - TECH_3GPP_PROFILE_PARAM_MIN;
  }
  else if ((ident >= GENERAL_PROFILE_PARAM_MIN) && (ident <= GENERAL_PROFILE_PARAM_MAX))
  {
    index = ident - GENERAL_PROFILE_PARAM_MIN;
    index += ((TECH_3GPP_PROFILE_PARAM_MAX - TECH_3GPP_PROFILE_PARAM_MIN) +1);
  } 
  else if((ident >= COMMON_TECH_PARAM_MIN) && (ident <= COMMON_TECH_PARAM_MAX))
  {
    index = ident - COMMON_TECH_PARAM_MIN;
    index += ((TECH_3GPP_PROFILE_PARAM_MAX - TECH_3GPP_PROFILE_PARAM_MIN)+ 
              (GENERAL_PROFILE_PARAM_MAX - GENERAL_PROFILE_PARAM_MIN)+2);
  }

  if((index >= 0 ) && (ident != ds_profile_3gpp_fn_tbl[index].ident))
  {
    index = -1;
  }
 
  return index;
}
/*lint -restore Restore lint error 656*/

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_GET_VALIDATION_FUNC

DESCRIPTION
  This function returns the validation function pointer corresponding
  to the identifier passed

PARAMETERS 
  ident : identifier for which index is to be returned
  
DEPENDENCIES 
  
RETURN VALUE 
  returns validate_fn_type
  
SIDE EFFECTS 
  
===========================================================================*/
validate_3gpp_fn_type dsi_profile_3gpp_modem_get_validation_func
(
   ds_profile_db_ident_type ident
)
{
  int8 ident_index = -1;
 /*------------------------------------------------------------------------*/
  ident_index = dsi_profile_3gpp_modem_get_index_from_ident(ident);

  if (ident_index < 0)
  {
    DS_3GPP_MSG3_ERROR("Identifier index is not valid:%d for ident: %d",ident_index,ident,0);
    return NULL;
  }

  return ds_profile_3gpp_fn_tbl[ident_index].validate_fn;

}
      

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_WRITE_IDENT_INFO

DESCRIPTION
  This function updates the identifier info in the cache

PARAMETERS 
   uint16 profile_number,
   ds_profile_db_ident_type ident,
   ds_profile_db_info_type  *info
   ds_profile_db_supported_tech_mask tech_mask
   boolean                           apn_param_check       
   old pdp profile data
  
DEPENDENCIES 
  
RETURN VALUE 
  void
  
SIDE EFFECTS 
  
===========================================================================*/
void dsi_profile_3gpp_modem_write_ident_info
(
   uint16 profile_number,
   ds_profile_db_ident_type ident,
   const ds_profile_db_3gpp_tech_params_type *ds_3gpp_tech_params_ptr,
   const ds_profile_db_gen_params_type       *gen_params,
   ds_profile_db_supported_tech_mask          tech_mask,
   boolean                                    apn_param_check,
   ds_umts_pdp_profile_type                   *old_pdp_profile_data
)
{
  int8 ident_index = 0;
  list_type *list_ptr = NULL;
  ds_profile_3gpp_cb_func_tbl_type *cb_tbl_ptr = NULL;
  ds_umts_pdp_subs_e_type           subs_id = 
                                          DS_UMTS_PDP_ACTIVE_SUBSCRIPTION_NONE ;
  boolean                           is_val_changed = TRUE;
  int8                              cache_index = -1;
  ds_umts_pdp_profile_type         *ds_umts_pdp_profile_ptr = NULL;
  byte                                  *old_apn = NULL;
 /*------------------------------------------------------------------------*/
  ident_index = dsi_profile_3gpp_modem_get_index_from_ident(ident);
    
  /*----------------------------------------------------------------------- 
   If the identifier is an apn_param set the apn_param_changed to true
   -----------------------------------------------------------------------*/
  if(apn_param_check)
  {
    (void)dsi_profile_set_if_ident_apn_param(ident);
  }
    
  if (ident_index < 0)
  {
    DS_3GPP_MSG3_ERROR("Identifier index is not valid:%d",ident_index,0,0);
    return;
  }
  if(gen_params == NULL) 
  {
    DS_3GPP_MSG0_ERROR("dsi_profile_3gpp_modem_write_ident_info: gen_params is NULL");
    return;
  }       
  subs_id = dsumts_subs_mgr_get_subs_id_from_db_subs_id(gen_params->subscription_id);
  if(ds_umts_pdp_check_subscription_id(subs_id) == DS_UMTS_PDP_INVALID_SUBS_ID)
  {
    DS_3GPP_MSG0_ERROR("subs info invalid");
    return;
  }    
  cache_index = ds_3gpp_profile_cache_get_cache_index(profile_number, subs_id);

  if(cache_index <= 0 || cache_index > DS_UMTS_MAX_PDP_PROFILE_NUM)
  {
    DS_3GPP_MSG1_HIGH("Cache index not found: %d", cache_index);
    return;
  }
  ds_umts_pdp_profile_ptr = 
          DS_UMTS_PDP_PROFILE_CACHE(subs_id, cache_index);

  if (ds_umts_pdp_profile_ptr == NULL)
  {
    DS_3GPP_MSG0_ERROR("Cache Ptr is NULL");
    return;
  }

  if((gen_params != NULL && ds_3gpp_tech_params_ptr != NULL))
  {   
    switch(ident)
    {
     case TECH_3GPP_PROFILE_PARAM_APN_DISABLE_FLAG:
       if (ds_3gpp_tech_params_ptr->tech_common_params.apn_disable_flag == 
            ds_umts_pdp_profile_ptr->apn_disable_flag)
       {   
         is_val_changed = FALSE;
       }
     break;
     case GENERAL_PROFILE_PARAM_APN_NAME:
       if((ds_umts_pdp_profile_ptr->context.valid_flg)&&
          (strncasecmp((char*)ds_umts_pdp_profile_ptr->context.apn, 
                gen_params->apn_name, DS_UMTS_MAX_APN_STRING_LEN+1) ==0))
       {
         is_val_changed = FALSE;
       }
       break;
      case TECH_3GPP_PROFILE_PARAM_PDN_REQ_WAIT_TIMER:
       if(ds_3gpp_tech_params_ptr->pdn_req_wait_time == 
              ds_umts_pdp_profile_ptr->pdn_req_wait_time)
       {
         is_val_changed = FALSE;
       }            
       break;
     case TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_PER_BLOCK:
       if(ds_3gpp_tech_params_ptr->max_pdn_conn_per_blk == 
                ds_umts_pdp_profile_ptr->max_pdn_conn_per_blk)
       {
         is_val_changed = FALSE;
       }
       break;
     case TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_TIMER:
       if(ds_3gpp_tech_params_ptr->max_pdn_conn_time == 
                    ds_umts_pdp_profile_ptr->max_pdn_conn_time)
       {
         is_val_changed = FALSE;
       }
       break;
     case TECH_3GPP_PROFILE_PARAM_ROAMING_DISALLOWED:
        if(ds_3gpp_tech_params_ptr->roaming_disallowed  == 
                  ds_umts_pdp_profile_ptr->roaming_disallowed)
        {
          is_val_changed = FALSE;
        }
        break;
    case TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_TYPE:

      if ((ds_umts_pdp_profile_ptr->context.valid_flg == TRUE)&&
          (ds_umts_pdp_profile_ptr->context.pdp_type == 
                  ds_3gpp_tech_params_ptr->pdp_context.pdp_type))
      {
        is_val_changed = FALSE;        
      }    
      break;
     default:
       break;
    }
  }
  if(!is_val_changed)
  { 
    DS_3GPP_MSG1_ERROR("input and cache value is same for ident:%d, no update !!",
                       ident_index);
    return;
  }
  ds_profile_3gpp_fn_tbl[ident_index].write_fn(profile_number,
                                               ds_3gpp_tech_params_ptr,
                                               gen_params,tech_mask);
    
  /* ----------------------------------------------------------------------
     Dispatch the handler for apn_disable_flag or apn_change_handler
     appropriately
     Also populate apn_disable_flag appropriately when needed.
   ----------------------------------------------------------------------*/
  if ( (gen_params != NULL && ds_3gpp_tech_params_ptr != NULL) &&
      ((ident == TECH_3GPP_PROFILE_PARAM_APN_DISABLE_FLAG) ||
      (ident == GENERAL_PROFILE_PARAM_APN_NAME) || 
      (ident == TECH_3GPP_PROFILE_PARAM_PDN_REQ_WAIT_TIMER)||
      (ident == TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_PER_BLOCK) ||
      (ident == TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_TIMER) ||
      (ident == TECH_3GPP_PROFILE_PARAM_ROAMING_DISALLOWED) ||
      (ident == TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_TYPE)))
     {
       list_ptr = ds_profile_3gpp_get_callback_table_list();
    /*-------------------------------------------------------------------- 
      Get the pointer to the head node in the list
      --------------------------------------------------------------------*/
       cb_tbl_ptr = (ds_profile_3gpp_cb_func_tbl_type*) 
                    list_peek_front( list_ptr );
       while ( cb_tbl_ptr != NULL )
       {
         switch (ident)
         {
           case TECH_3GPP_PROFILE_PARAM_APN_DISABLE_FLAG:
             if (cb_tbl_ptr->apn_disable_flag_change_handler != NULL)
             {
               cb_tbl_ptr->apn_disable_flag_change_handler
                       (profile_number, (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                       ds_3gpp_tech_params_ptr->
                       tech_common_params.apn_disable_flag);
             }
             break;
           case GENERAL_PROFILE_PARAM_APN_NAME:
             if (cb_tbl_ptr->apn_name_change_handler != NULL)
             {
               /*-------------------------------------------------------------------- 
                 Check old_profile_data and populate old_apn
                 --------------------------------------------------------------------*/
               if ((old_pdp_profile_data != NULL) && 
                   (old_pdp_profile_data->context.valid_flg))
               {
                 old_apn = old_pdp_profile_data->context.apn;
               }

               cb_tbl_ptr->apn_name_change_handler(profile_number, 
                       (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                        (void *)old_apn);
             }
             break;
           case TECH_3GPP_PROFILE_PARAM_PDN_REQ_WAIT_TIMER:
             if (cb_tbl_ptr->pdn_req_wait_time_chg_hdlr != NULL)
             {
               cb_tbl_ptr->pdn_req_wait_time_chg_hdlr
                   (profile_number,
                   (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                    ds_3gpp_tech_params_ptr->pdn_req_wait_time);
             }
             break;
           case  TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_PER_BLOCK:
             if (cb_tbl_ptr->max_pdn_conn_per_blk_chg_hdlr != NULL)
             {
               cb_tbl_ptr->max_pdn_conn_per_blk_chg_hdlr
                    (profile_number,
                     (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                     ds_3gpp_tech_params_ptr->max_pdn_conn_per_blk);
             }
             break;
           case TECH_3GPP_PROFILE_PARAM_MAX_PDN_CONN_TIMER:
             if (cb_tbl_ptr->max_pdn_conn_time_chg_hdlr != NULL)
             {
               cb_tbl_ptr->max_pdn_conn_time_chg_hdlr
                      (profile_number,
                       (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                       ds_3gpp_tech_params_ptr->max_pdn_conn_time);
             }
             break;
           case TECH_3GPP_PROFILE_PARAM_ROAMING_DISALLOWED:
             if (cb_tbl_ptr->roaming_disallowed_flag_chg_hdlr != NULL)
             {
               cb_tbl_ptr->roaming_disallowed_flag_chg_hdlr
                      (profile_number, 
                       (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                       ds_3gpp_tech_params_ptr->roaming_disallowed);
             }
             break;
           case TECH_3GPP_PROFILE_PARAM_PDP_CONTEXT_PDP_TYPE:
             if (cb_tbl_ptr->pdp_type_chg_hdlr != NULL)
             {
               cb_tbl_ptr->pdp_type_chg_hdlr(profile_number,
                          (sys_modem_as_id_e_type)(gen_params->subscription_id - 1),
                          (ds_umts_pdp_type_enum_type)ds_3gpp_tech_params_ptr->
                                                          pdp_context.pdp_type);
             }
             break;
           default:
            break;
         }
      /*--------------------------------------------------------------
            Get the next hdlr table in the list
      --------------------------------------------------------------*/
         cb_tbl_ptr = list_peek_next(list_ptr, &(cb_tbl_ptr->link));
       }
     }
}


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_GET_LIST_NODE

DESCRIPTION
  This function is used to get info from a particular node in the list

PARAMETERS 
  hndl : iterator handle
  list_info : pointer to store information to be returned
  
DEPENDENCIES 
  
RETURN VALUE 
  DS_PROFILE_REG_RESULT_SUCCESS
  DS_PROFILE_REG_RESULT_FAIL
  
SIDE EFFECTS 
  
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_get_list_node(
  ds_util_itr_hndl_type       hndl,
  ds_profile_list_info_type  *list_info
)
{
  ds_profile_3gpp_list_info_type node;
  uint32 info_size = sizeof(ds_profile_3gpp_list_info_type);

  /* Initialize node */
  memset( (void *)&node, 0, sizeof(ds_profile_3gpp_list_info_type) );

  if ( ds_util_itr_get_data(hndl, (void *)&node, &info_size) != DS_SUCCESS)
  {
    DS_PROFILE_LOGE("_3gpp_get_list_node: unable to get node from list", 0);
    return DS_PROFILE_REG_RESULT_FAIL;
  }

  if ( (list_info->name->len >= DS_PROFILE_STR_LEN( node.prf_name )) && 
       (list_info->name->buf != NULL) )
  {
    list_info->num = node.prf_num;
    list_info->name->len = (uint16)DS_PROFILE_STR_LEN( node.prf_name );

    /* Clear user supplied list_info->name->buf before updating with new value */
    memset( (void *)list_info->name->buf, 
            0, list_info->name->len );

    memscpy( (void *)list_info->name->buf,  list_info->name->len,
            (void *)node.prf_name, 
                      list_info->name->len);
  }
  else
  {
    DS_PROFILE_LOGE("_3gpp_get_list_node: user supplied bad list_node", 0);
    return DS_PROFILE_REG_RESULT_ERR_INVAL;
  }
   
  return DS_PROFILE_REG_RESULT_SUCCESS;
}


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_SET_PDP_PROFILE_NUM_FOR_TETHERED_CALLS

DESCRIPTION
  This function sets the profile number specified to be used for tethered 
  calls. It writes the value specified to the file the tethered_call_prof_num file

PARAMETERS 
  subs_id : Subscription ID 
  profile_number  : profile number 

DEPENDENCIES 

RETURN VALUE 
  DS_UMTS_PDP_SUCCESS              : the operation completed successfully
  DS_UMTS_PDP_NOT_INITIALIZED      : Registry API library not initialized
  DS_UMTS_PDP_INVALID_PROFILE_NUM  : Invalid profile number
  DS_UMTS_PDP_ACCESS_ERROR         : Error in updating the file

SIDE EFFECTS 
  None
===========================================================================*/
ds_umts_pdp_profile_status_etype
   dsi_profile_3gpp_set_pdp_profile_num_for_tethered_calls
(
  ds_profile_subs_etype subs_id,
  uint16 profile_number
)
{
   ds_umts_pdp_profile_status_etype ret_val = DS_UMTS_PDP_FAIL;
  /*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/
  if(ds_umts_update_default_tethered_prof_num(
     dsumts_subs_mgr_get_subs_id_from_ds_profile_subs_id(subs_id), profile_number))
  {
     ret_val = DS_UMTS_PDP_SUCCESS;
  }

  return ret_val;

} /* dsi_profile_3gpp_set_pdp_profile_num_for_tethered_calls */

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_SET_PDP_PROFILE_NUM_FOR_EMBEDDED_CALLS

DESCRIPTION
  This function sets the profile number specified to be used for embedded 
  calls. It writes the value specified to the file the embedded_call_prof_num
  file

PARAMETERS 
  subs_id: Subscription ID 
  profile_number  : profile number 

DEPENDENCIES 

RETURN VALUE 
  DS_UMTS_PDP_SUCCESS              : the operation completed successfully
  DS_UMTS_PDP_NOT_INITIALIZED      : Registry API library not initialized
  DS_UMTS_PDP_INVALID_PROFILE_NUM  : Invalid profile number
  DS_UMTS_PDP_ACCESS_ERROR         : Error in updating the file

SIDE EFFECTS 
  None
===========================================================================*/
ds_umts_pdp_profile_status_etype
   dsi_profile_3gpp_set_pdp_profile_num_for_embedded_calls
(
  ds_profile_subs_etype subs_id,
  uint16 profile_number

)
{
   ds_umts_pdp_profile_status_etype ret_val = DS_UMTS_PDP_FAIL;
  /*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -*/
  if(ds_umts_update_embedded_call_prof_num(
     dsumts_subs_mgr_get_subs_id_from_ds_profile_subs_id(subs_id), profile_number))
  {
     ret_val = DS_UMTS_PDP_SUCCESS;
  }

  return ret_val;

} /* dsi_profile_3gpp_set_pdp_profile_num_for_embedded_calls */


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_SET_DEFAULT_PROFILE

DESCRIPTION
  This function is used to set default profile number for a particular
  family

PARAMETERS 
  family : type of profile (socket, rmnet, atcop)
  num : profile number

DEPENDENCIES 
  
RETURN VALUE 
  
SIDE EFFECTS 
  
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_set_default_profile(  
  uint32                 family, 
  ds_profile_subs_etype subs_id, 
  ds_profile_num_type    num
)
{
  ds_umts_pdp_profile_status_etype status = DS_UMTS_PDP_FAIL;

  switch ( family )
  {
    /* EMBEDDED */
    case DS_PROFILE_EMBEDDED_PROFILE_FAMILY:
       status = dsi_profile_3gpp_set_pdp_profile_num_for_embedded_calls
                       (subs_id ,num);
    break;

    /* TETHERED ( RmNet/ATCoP/DUN ) */
    case DS_PROFILE_TETHERED_PROFILE_FAMILY:
       status = dsi_profile_3gpp_set_pdp_profile_num_for_tethered_calls
                      ( subs_id ,num );
    break;

    default:
      DS_PROFILE_LOGE(" invalid profile family %d", family);
      return DS_PROFILE_REG_INVAL_PROFILE_FAMILY;
  }

  if(status != DS_UMTS_PDP_SUCCESS)
  {
     return DS_PROFILE_REG_RESULT_FAIL;
  }
  return DS_PROFILE_REG_RESULT_SUCCESS; 
}

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_GET_DEFAULT_PROFILE_NUMBER_PER_SUBS

DESCRIPTION
  This function gets the profile number for the specifies subscription.
  It gets the value specified to the embedded_call_prof_nums_dsds file or 
  tethered_call_prof_nums_dsds file.

PARAMETERS 
  family           : Denotes embedded or tethered profile
  subs             : Denotes one of two active subscriptions
  profile_number   : Profile number

DEPENDENCIES 
  ds_umts_pdp_registry_init_flag should be set(we should have been initialized)

RETURN VALUE 
  DS_UMTS_PDP_SUCCESS              : The operation completed successfully
  DS_UMTS_PDP_NOT_INITIALIZED      : Registry API library not initialized
  DS_UMTS_PDP_INVALID_PROFILE_NUM  : Invalid profile number
  DS_UMTS_PDP_ACCESS_ERROR         : Error in updating the file

SIDE EFFECTS 
  None
===========================================================================*/

ds_umts_pdp_profile_status_etype
dsi_profile_3gpp_get_default_profile_number_per_subs
(
  ds_umts_profile_family_e_type        family,
  ds_profile_subs_etype             subs_id,
  uint16                              *profile_number
)
{
  ds_umts_pdp_profile_status_etype status = DS_UMTS_PDP_FAIL;
  *profile_number = 0;


/*---------------------------------------------------------------------
    Check if the subscription id is valid
  ---------------------------------------------------------------------*/

  if( subs_id < DS_PROFILE_ACTIVE_SUBSCRIPTION_1 ||
      subs_id > DS_PROFILE_ACTIVE_SUBSCRIPTION_MAX )
  {
    return DS_UMTS_PDP_INVALID_SUBS_ID;
  }


  status = ds_umts_get_default_profile_number_internal(family, 
                      dsumts_subs_mgr_get_subs_id_from_ds_profile_subs_id(subs_id),
                                           profile_number);

  if(status == DS_UMTS_PDP_ACCESS_ERROR)
  {
    DS_3GPP_MSG3_ERROR("Setting default profile to 1",0,0,0);
    *profile_number = 1;
    status = DS_UMTS_PDP_SUCCESS; /* hack, need */
}

  return status;
}





/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_GET_DEFAULT_PROFILE

DESCRIPTION
  This function is used to get default profile number for a particular
  family

PARAMETERS 
  family : type of profile (socket, rmnet, atcop)
  num : profile number

DEPENDENCIES 
  
RETURN VALUE 
  
SIDE EFFECTS 
  
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_get_default_profile(
  uint32                 family, 
  ds_profile_num_type   *num
)
{
  ds_umts_pdp_profile_status_etype return_status = DS_UMTS_PDP_FAIL;

  if (num == NULL)
  {
    DS_3GPP_MSG0_ERROR("Profile NUM PTR is NULL");
    return DS_PROFILE_REG_RESULT_FAIL;  
  }

  memset((void*)num,0,sizeof(ds_profile_num_type));

  return_status = ds_umts_get_default_profile_number_internal(family, 
                           dsumts_subs_mgr_get_subs_id_from_db_subs_id(ds_3gpp_profile_get_default_sub_id()),
                            num);

  if(return_status == DS_UMTS_PDP_ACCESS_ERROR)
  {
    DS_3GPP_MSG0_ERROR("Setting default profile to 1");
    *num = 1;
    return DS_PROFILE_REG_RESULT_SUCCESS; /* hack, need */
  }
  else if (return_status != DS_UMTS_PDP_SUCCESS)
  {
     return DS_PROFILE_REG_RESULT_FAIL;
  }
  else
  {
     return DS_PROFILE_REG_RESULT_SUCCESS;
  }
}

/*===========================================================================
FUNCTION DS_PROFILE_3GPP_SET_DEFAULT_PROFILE_NUMBER_PER_SUBS

DESCRIPTION
  This function sets the profile number for tethered or embedded family for 
  the specified subscription. The value is written to either 
  embedded_call_prof_nums_dsds or tethered_call_prof_nums_dsds file.

PARAMETERS 
  family           : Denotes embedded or tetherd profile
  subs             : Denotes one of two active subscriptions
  profile_number   : Profile number

DEPENDENCIES 


RETURN VALUE 
  DS_UMTS_PDP_SUCCESS              : The operation completed successfully
  DS_UMTS_PDP_NOT_INITIALIZED      : Registry API library not initialized
  DS_UMTS_PDP_INVALID_PROFILE_NUM  : Invalid profile number
  DS_UMTS_PDP_ACCESS_ERROR         : Error in updating the file

SIDE EFFECTS 
  None
===========================================================================*/

ds_umts_pdp_profile_status_etype
dsi_profile_3gpp_set_default_profile_number_per_subs
(
  ds_umts_profile_family_e_type        family,
  ds_umts_pdp_subs_e_type              subs_id,
  uint16                               profile_number
)
{
  ds_umts_pdp_profile_status_etype status = DS_UMTS_PDP_FAIL;

  if(ds_umts_pdp_check_subscription_id(subs_id) == 
               DS_UMTS_PDP_INVALID_SUBS_ID)
  {
     DS_3GPP_MSG1_ERROR("Invalid Subs id:%d",subs_id);
     return DS_UMTS_PDP_INVALID_SUBS_ID;
  }

  status = ds_umts_set_default_profile_number_internal(family, subs_id, profile_number);

  return status;
}


/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_SET_DEFAULT_PROFILE_PER_SUBS

DESCRIPTION
  This function is used to set default profile number for a particular
  family and subscription.

PARAMETERS 
  family  : profile family  (embedded or tethered)
  subs_id : subscription id ( subs 1 or subs 2)
  num     : profile number

DEPENDENCIES 
  None
  
RETURN VALUE 
  DS_PROFILE_REG_RESULT_SUCCESS   : On successful operation
  DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_TYPE : Profile type is invalid
  DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM  : Invalid profile number
  DS_PROFILE_REG_RESULT_ERR_INVAL_OP : Operation not supported for tech type
  DS_PROFILE_REG_RESULT_FAIL      : On general errors. This return 
                                    code provides blanket coverage
  DS_PROFILE_REG_RESULT_ERR_INVAL_SUBS_ID : Invalid subscription id passed
  
SIDE EFFECTS 
  None
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_set_default_profile_per_subs(  
  uint32                  family,
  ds_profile_subs_etype  subs_id,
  ds_profile_num_type     num
)
{
  ds_umts_pdp_profile_status_etype return_status = DS_UMTS_PDP_FAIL;

  return_status = dsi_profile_3gpp_set_default_profile_number_per_subs( 
                     (ds_umts_profile_family_e_type)family, 
                     dsumts_subs_mgr_get_subs_id_from_ds_profile_subs_id(subs_id), 
                     num );
  
  if (return_status != DS_UMTS_PDP_SUCCESS) 
  {
    return DS_PROFILE_REG_RESULT_FAIL;
  }
  else
  {
     return DS_PROFILE_REG_RESULT_SUCCESS;
  }

  }

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_GET_DEFAULT_PROFILE_PER_SUBS

DESCRIPTION
  This function is used to get default profile number form the specified
  family and subscription.

PARAMETERS 
  family  : type of profile (embedded or tethered)
  subs_id : subscription id (subs 1 or subs 2)
  num     : profile number

DEPENDENCIES 
  None
  
RETURN VALUE 
  DS_PROFILE_REG_RESULT_SUCCESS   : On successful operation
  DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_TYPE : Profile type is invalid
  DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM  : Invalid profile number
  DS_PROFILE_REG_RESULT_ERR_INVAL_OP : Operation not supported for tech type
  DS_PROFILE_REG_RESULT_FAIL      : On general errors. This return 
                                    code provides blanket coverage
  DS_PROFILE_REG_RESULT_ERR_INVAL_SUBS_ID : Invalid subscription id passed
  
SIDE EFFECTS 
  None  
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_get_default_profile_per_subs(
  uint32                  family,
  ds_profile_subs_etype  subs_id,
  ds_profile_num_type     *num
)
{
  ds_umts_pdp_profile_status_etype return_status = DS_UMTS_PDP_FAIL;

  return_status = dsi_profile_3gpp_get_default_profile_number_per_subs( 
                     (ds_umts_profile_family_e_type)family, 
                     subs_id, 
                     num );

  if (return_status != DS_UMTS_PDP_SUCCESS) 
  {
    return DS_PROFILE_REG_RESULT_FAIL;
  }
  else
  {
     return DS_PROFILE_REG_RESULT_SUCCESS;
  }
}

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_RESET_PARAM

DESCRIPTION
  This function is used to reset a particular identifier value to default.
  Calls the corresponding pdpreg function. Valid for particular identifiers
  no-op for others.

PARAMETERS 
  num : profile number
  ident : identifier for the paramter

DEPENDENCIES 
  
RETURN VALUE 
  
SIDE EFFECTS 
  
===========================================================================*/

ds_profile_status_etype dsi_profile_3gpp_modem_reset_param(
  ds_profile_num_type         num,
  ds_profile_identifier_type  ident
)
{
  ds_umts_pdp_profile_status_etype return_status = DS_UMTS_PDP_FAIL;

  if ( !DS_PROFILE_3GPP_IDENT_IS_VALID(ident) )
  {
    return DS_PROFILE_REG_RESULT_ERR_INVAL_IDENT;
  }

  switch ( ident )
  {
    case DS_PROFILE_3GPP_PROFILE_PARAM_UMTS_REQ_QOS:
    case DS_PROFILE_3GPP_PROFILE_PARAM_UMTS_REQ_QOS_EXTENDED:
      return_status = ds_umts_reset_pdp_profile_umts_qos_req_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_UMTS_MIN_QOS:
    case DS_PROFILE_3GPP_PROFILE_PARAM_UMTS_MIN_QOS_EXTENDED:
      return_status = ds_umts_reset_pdp_profile_umts_qos_min_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_SRC_STAT_DESC_REQ:
      return_status = ds_umts_reset_pdp_profile_src_stat_desc_req_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_SRC_STAT_DESC_MIN:
        return_status = ds_umts_reset_pdp_profile_src_stat_desc_min_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_GPRS_REQ_QOS:
      return_status = ds_umts_reset_pdp_profile_gprs_qos_req_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_GPRS_MIN_QOS:
      return_status = ds_umts_reset_pdp_profile_gprs_qos_min_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_LTE_REQ_QOS:
      return_status = ds_3gpp_reset_pdp_profile_lte_qos_info( num );
    break;

    case DS_PROFILE_3GPP_PROFILE_PARAM_TFT_FILTER_ID1:
    case DS_PROFILE_3GPP_PROFILE_PARAM_TFT_FILTER_ID2:
      return_status = ds_umts_reset_pdp_profile_tft_all_info( num );
    break;

    default:
      return DS_PROFILE_REG_RESULT_ERR_INVAL_OP;
  }

  if (return_status != DS_UMTS_PDP_SUCCESS) 
  {
    return DS_PROFILE_REG_RESULT_FAIL;
  }
  else
  {
     return DS_PROFILE_REG_RESULT_SUCCESS;
  }
   
}

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_MODEM_RESET_PROFILE_TO_DEFAULT

DESCRIPTION
  This function is used to reset profile to default values. Calls
  corresponding pdpreg function

PARAMETERS 
  num : profile number

DEPENDENCIES 
  
RETURN VALUE 
  
SIDE EFFECTS 
  
===========================================================================*/

ds_profile_status_etype dsi_profile_3gpp_modem_reset_profile_to_default(  
  ds_profile_num_type    num
)
{ 
/*lint -save -e64*/
  ds_umts_pdp_profile_status_etype return_status = DS_UMTS_PDP_FAIL;
  return_status = ds_umts_set_pdp_profile_all_data_to_default( num, 
                              (ds_ip_version_enum_type)DS_PROFILE_3GPP_IP_V4V6 ); 
/*lint -restore Restore lint error 64*/
  if (return_status != DS_UMTS_PDP_SUCCESS) 
  {
    return DS_PROFILE_REG_RESULT_FAIL;
  }
  else
  {
     return DS_PROFILE_REG_RESULT_SUCCESS;
  }
}

/*===========================================================================
FUNCTION DSI_PROFILE_3GPP_VALIDATE_PROFILE_NUM

DESCRIPTION
  This function is used to validate a profile number.

PARAMETERS 
  num : profile number
  
DEPENDENCIES 
  
RETURN VALUE 
  DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM
  DS_PROFILE_REG_RESULT_SUCCESS
  
SIDE EFFECTS 
  
===========================================================================*/
ds_profile_status_etype dsi_profile_3gpp_validate_profile_num(
  ds_profile_num_type num
)
{
  uint16 min_num = 0;
  uint16 max_num = 0;

  /* check profile number */
  dsi_profile_get_profile_num_range(DS_PROFILE_TECH_3GPP, 
                                    &min_num, 
                                    &max_num);

  if ( ( num > max_num ) || ( num < min_num ) )
  {
    return DS_PROFILE_REG_RESULT_ERR_INVAL_PROFILE_NUM;
  }

  return DS_PROFILE_REG_RESULT_SUCCESS;
}

/*===========================================================================
FUNCTION DS_PROFILE_3GPP_MODEM_INIT

DESCRIPTION
  This function is called on the library init. It initializes the function
  pointers to valid functions for 3gpp

PARAMETERS 
  fntbl : pointer to table of function pointers

DEPENDENCIES 
  
RETURN VALUE 
  returns the mask for 3gpp. (Used later as valid mask which is ORed value
  returned from all techs.
SIDE EFFECTS 
  
===========================================================================*/
uint8 ds_profile_3gpp_modem_init( tech_fntbl_type *fntbl )
{

  /* Initialize PDP registry */
  if (DS_UMTS_PDP_SUCCESS != ds_umts_pdp_registry_init())
  {
    ASSERT(0);
    return 0;
  }

  /* Init function pointers */
  fntbl->create                       = ds_profile_db_handler_create;
  fntbl->del                          = ds_profile_db_handler_delete;
  fntbl->profile_read                 = ds_profile_db_handler_profile_read;
  fntbl->profile_write                = ds_profile_db_handler_profile_write;
  fntbl->validate_profile_num         = ds_profile_db_handler_validate_profile_num;
  fntbl->get_list                     = ds_profile_db_handler_get_list;
  fntbl->get_list_node                = ds_profile_db_handler_get_list_node;
  fntbl->reset_param                  = ds_profile_db_handler_reset_param;
  fntbl->reset_profile_to_default     = ds_profile_db_handler_reset_profile_to_default;
  fntbl->set_default_profile          = ds_profile_db_handler_set_default_profile;
  fntbl->get_default_profile          = ds_profile_db_handler_get_default_profile;
  fntbl->set_default_profile_per_subs = ds_profile_db_handler_set_default_profile_per_subs;
  fntbl->get_default_profile_per_subs = ds_profile_db_handler_get_default_profile_per_subs;
  fntbl->get_num_range                = ds_profile_db_handler_get_num_range;

  DS_PROFILE_LOGD("ds_profile_3gpp_modem_init:initializing function pointers", 0);
  return (0x01 << DS_PROFILE_TECH_3GPP);
}

/*lint -restore Restore lint error 641*/
