#ifndef HSU_MDM_APIS_RPC_H
#define HSU_MDM_APIS_RPC_H

/* HSU_MDM_APIS TOOL VERSION: 4.39 */
/* GENERATED: TUE JUN 22 2010 */
/*=============================================================================
                      H S U _ M D M _ A P I S _ R P C . H

GENERAL DESCRIPTION
  This is an AUTO GENERATED file that provides declarations pertaining to the
  exporting of the hsu_mdm_apis api using ONCRPC.

  ---------------------------------------------------------------------------
  Copyright (c) 2010 Qualcomm Technologies Incorporated.
  All Rights Reserved. QUALCOMM Proprietary and Confidential.
  ---------------------------------------------------------------------------
=============================================================================*/

/*=============================================================================

                              Edit History

                             AUTO GENERATED                                  */
/* Generated by following versions of Htorpc modules:
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/htorpc.pl#2 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/Start.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/Htoxdr.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/XDR.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/Output.pm#2 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/Parser.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/Metacomments.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/05.01/htorpc/lib/Htorpc/SymbolTable.pm#1  

hsu_mdm_apis Definition File(s):

=============================================================================*/
/*=============================================================================
$Header: //components/rel/tz.bf/2.5.c10/trustzone_images/core/api/rapi/wiredconnectivity/inc/hsu_mdm_apis_rpc.h#1 $ 
=============================================================================*/


/* Include ONCRPC headers */
#include "oncrpc.h"
#include "comdef.h"

#define HSU_MDM_APISPROG					0x30000064
#define HSU_MDM_APISVERS					0x00010003 /* 0x00010003 */
/*defines for feature and tool version*/
#define HSU_MDM_APIS_TOOLVERS					0x00040027
#define HSU_MDM_APIS_FEATURES					0x00000001
 

#define HSU_API_CHG_IS_CONNECTED_VERS                     	0x00010001
#define HSU_API_DISABLE_PMIC_OTG_COMPARATORS_VERS         	0x00010002
#define HSU_API_DISABLE_PMIC_ULPIDATA0_IRQ_HANDLER_VERS   	0x00010001
#define HSU_API_DISCONNECT_PULLDOWNS_UICC_VERS            	0x00010002
#define HSU_API_ENABLE_PMIC_OTG_COMPARATORS_VERS          	0x00010002
#define HSU_API_ENABLE_PMIC_ULPIDATA0_IRQ_HANDLER_VERS    	0x00010001
#define HSU_API_INIT_CHG_VERS                             	0x00010001
#define HSU_API_INIT_PHY_VERS                             	0x00010001
#define HSU_API_INIT_UICC_VERS                            	0x00010001
#define HSU_API_NOTIF_CHARGER_CONNECTED_VERS              	0x00010001
#define HSU_API_NOTIF_CHARGER_DISCONNECTED_VERS           	0x00010001
#define HSU_API_NOTIF_CHARGER_IS_AVAIL_VERS               	0x00010001
#define HSU_API_NOTIF_CHARGER_NOT_AVAIL_VERS              	0x00010001
#define HSU_API_POLLDOWN_UICC_VERS                        	0x00010001
#define HSU_API_START_UICC_VERS                           	0x00010001
#define HSU_API_UPDATE_IS_SERIAL_NUMBER_NULL_VERS         	0x00010001
#define HSU_API_UPDATE_PRODUCT_ID_VERS                    	0x00010001
#define HSU_API_UPDATE_SERIAL_NUMBER_VERS                 	0x00010001
#define HSU_API_UPDATE_VENDOR_ID_VERS                     	0x00010003
#define HSU_API_USB_RESET_REWORK_INSTALLED_VERS           	0x00010001
#define HSU_API_VBUS_POWERUP_VERS                         	0x00010001
#define HSU_API_VBUS_SHUTDOWN_VERS                        	0x00010001
#define HSU_DLOAD_ENABLE_DISABLE_CORE_VERS                	0x00010002
#define HSU_DLOAD_IS_WALL_CHARGER_VERS                    	0x00010002
#define HSU_DLOAD_SESS_IS_VALID_VERS                      	0x00010002
#define HSU_DLOAD_SET_USB_IMAX_VERS                       	0x00010002
#define HSU_MDM_APIS_API_VERSIONS_VERS                    	0x00010001
#define HSU_MDM_APIS_NULL_VERS                            	0x00010001
#define HSU_MDM_APIS_RPC_GLUE_CODE_INFO_REMOTE_VERS       	0x00010001
/* prototypes for the app_init routines for the api and the api's callback
 * services
 */
extern void hsu_mdm_apis_app_init( void );
extern void hsu_mdm_apiscb_app_init( void );

/* prototypes for the app_lock routines for the api and the api's callback
 * services
 */
#define hsu_mdm_apis_app_enable()  hsu_mdm_apis_app_lock( FALSE )
#define hsu_mdm_apis_app_disable() hsu_mdm_apis_app_lock( TRUE )
extern void hsu_mdm_apis_app_lock( boolean lock );

#define hsu_mdm_apiscb_app_enable()  hsu_mdm_apiscb_app_lock( FALSE )
#define hsu_mdm_apiscb_app_disable() hsu_mdm_apiscb_app_lock( TRUE )
extern void hsu_mdm_apiscb_app_lock( boolean lock );

/* prototypes for glue code info querty functions:
 *
 * toolvers   : Tool version
 * features   : Features turned on in the code.
 *              0x00000001    ONCRPC Server Cleanup Support
 * proghash   : Unique hash value that represents the API XDR definition
 * cbproghash : Unique hash value that represents the Callbacks' XDR definition
 */
extern boolean hsu_mdm_apis_rpc_glue_code_info_remote    /* REMOTE INFO */
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
);
extern boolean hsu_mdm_apis_rpc_glue_code_info_local     /* LOCAL INFO */
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
);

/* prototype for API null routine */
extern boolean hsu_mdm_apis_null(void);

/* prototype for API version function */
extern uint32 *hsu_mdm_apis_api_versions
(
   uint32 *len
);

/* Start forward xdr procedure numbers */

#define ONCRPC_HSU_MDM_APIS_NULL_PROC 0 
 #define ONCRPC_HSU_MDM_APIS_RPC_GLUE_CODE_INFO_REMOTE_PROC 1 
 #define ONCRPC_HSU_API_INIT_PHY_PROC 2 
 #define ONCRPC_HSU_API_INIT_UICC_PROC 3 
 #define ONCRPC_HSU_API_START_UICC_PROC 4 
 #define ONCRPC_HSU_API_POLLDOWN_UICC_PROC 5 
 #define ONCRPC_HSU_API_VBUS_POWERUP_PROC 6 
 #define ONCRPC_HSU_API_VBUS_SHUTDOWN_PROC 7 
 #define ONCRPC_HSU_API_UPDATE_PRODUCT_ID_PROC 8 
 #define ONCRPC_HSU_API_UPDATE_SERIAL_NUMBER_PROC 9 
 #define ONCRPC_HSU_API_UPDATE_IS_SERIAL_NUMBER_NULL_PROC 10 
 #define ONCRPC_HSU_API_NOTIF_CHARGER_NOT_AVAIL_PROC 11 
 #define ONCRPC_HSU_API_NOTIF_CHARGER_IS_AVAIL_PROC 12 
 #define ONCRPC_HSU_API_NOTIF_CHARGER_DISCONNECTED_PROC 13 
 #define ONCRPC_HSU_API_NOTIF_CHARGER_CONNECTED_PROC 14 
 #define ONCRPC_HSU_API_INIT_CHG_PROC 15 
 #define ONCRPC_HSU_API_CHG_IS_CONNECTED_PROC 16 
 #define ONCRPC_HSU_API_USB_RESET_REWORK_INSTALLED_PROC 17 
 #define ONCRPC_HSU_API_ENABLE_PMIC_ULPIDATA0_IRQ_HANDLER_PROC 18 
 #define ONCRPC_HSU_API_DISABLE_PMIC_ULPIDATA0_IRQ_HANDLER_PROC 19 
 #define ONCRPC_HSU_DLOAD_IS_WALL_CHARGER_PROC 20 
 #define ONCRPC_HSU_DLOAD_SET_USB_IMAX_PROC 21 
 #define ONCRPC_HSU_API_DISABLE_PMIC_OTG_COMPARATORS_PROC 22 
 #define ONCRPC_HSU_DLOAD_SESS_IS_VALID_PROC 23 
 #define ONCRPC_HSU_DLOAD_ENABLE_DISABLE_CORE_PROC 24 
 #define ONCRPC_HSU_API_DISCONNECT_PULLDOWNS_UICC_PROC 25 
 #define ONCRPC_HSU_API_ENABLE_PMIC_OTG_COMPARATORS_PROC 26 
 #define ONCRPC_HSU_MDM_APIS_API_VERSIONS_PROC 0xffffffff

/*Start: procedure added to FORWARD xdr in version 0x00010003*/

 #define ONCRPC_HSU_API_UPDATE_VENDOR_ID_PROC 27
 

/*End: procedure added to FORWARD xdr in version 0x00010003*/

/* End forward xdr procedure numbers */
/* Start callback xdr procedure numbers */
/* End callback xdr procedure numbers */


/* XDR Routine Prototypes go here */

#endif /* ! HSU_MDM_APIS_RPC_H */
