#ifndef PING_MDM_RPC_RPC_H
#define PING_MDM_RPC_RPC_H

/* PING_MDM_RPC TOOL VERSION: 4.35 */
/*=============================================================================
                      P I N G _ M D M _ R P C _ R P C . H

GENERAL DESCRIPTION
  This is an AUTO GENERATED file that provides declarations pertaining to the
  exporting of the ping_mdm_rpc api using ONCRPC.

  ---------------------------------------------------------------------------
  Copyright (c) 2009 Qualcomm Technologies Incorporated.
  All Rights Reserved. QUALCOMM Proprietary and Confidential.
  ---------------------------------------------------------------------------
=============================================================================*/

/*=============================================================================

                              Edit History

                             AUTO GENERATED                                  */
/* Generated by following versions of Htorpc modules:
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/htorpc.pl#7 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Start.pm#2 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Htoxdr.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/XDR.pm#2 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Output.pm#6 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Parser.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Metacomments.pm#4 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/SymbolTable.pm#2  

ping_mdm_rpc Definition File(s):
Id: //source/qcom/qct/core/api/rapi/mproc/rel/04.07/inc/ping_mdm_rpc.h#1
=============================================================================*/
/*=============================================================================
$Header: //components/rel/tz.bf/2.5.c10/trustzone_images/core/api/rapi/mproc/inc/ping_mdm_rpc_rpc.h#1 $ 
=============================================================================*/


/* Include ONCRPC headers */
#include "oncrpc.h"
#include "comdef.h"

#define PING_MDM_RPCPROG					0x30000081
#define PING_MDM_RPCVERS					0x00010002 /* 0x00010002 */
/*defines for feature and tool version*/
#define PING_MDM_RPC_TOOLVERS					0x00040023
#define PING_MDM_RPC_FEATURES					0x00000001
 

#define PING_MDM_GET_MAX_TASKS_VERS                       	0x00010002
#define PING_MDM_GET_CURRENT_NUM_TASKS_VERS               	0x00010002
#define PING_MDM_REGISTER_DATA_CB_VERS                    	0x00010001
#define PING_MDM_REGISTER_VERS                            	0x00010001
#define PING_MDM_UN_REGISTER_VERS                         	0x00010001
#define PING_MDM_UN_REGISTER_DATA_CB_VERS                 	0x00010001
#define PING_MDM_DATA_VERS                                	0x00010001
#define PING_MDM_RPC_API_VERSIONS_VERS                    	0x00010001
#define PING_MDM_RESET_NOMINAL_TASKS_VERS                 	0x00010002
#define PING_MDM_RPC_RPC_GLUE_CODE_INFO_REMOTE_VERS       	0x00010001
#define PING_MDM_REGISTER_RANDOM_DATA_CB_VERS             	0x00010002
#define PING_MDM_RPC_NULL_VERS                            	0x00010001
#define PING_MDM_RPCCBPROG					0x31000081
#define PING_MDM_RPCCBVERS					0x00010002 /* 0x00010002 */

#define PING_MDM_RPC_CB_NULL_VERS                         	0X00010002
#define PING_MDM_DATA_CB_F_TYPE_VERS                      	0X00010001
#define PING_MDM_CB_F_TYPE_VERS                           	0X00010001
/* prototypes for the app_init routines for the api and the api's callback
 * services
 */
extern void ping_mdm_rpc_app_init( void );
extern void ping_mdm_rpccb_app_init( void );

/* prototypes for the app_lock routines for the api and the api's callback
 * services
 */
#define ping_mdm_rpc_app_enable()  ping_mdm_rpc_app_lock( FALSE )
#define ping_mdm_rpc_app_disable() ping_mdm_rpc_app_lock( TRUE )
extern void ping_mdm_rpc_app_lock( boolean lock );

#define ping_mdm_rpccb_app_enable()  ping_mdm_rpccb_app_lock( FALSE )
#define ping_mdm_rpccb_app_disable() ping_mdm_rpccb_app_lock( TRUE )
extern void ping_mdm_rpccb_app_lock( boolean lock );

/* prototypes for glue code info querty functions:
 *
 * toolvers   : Tool version
 * features   : Features turned on in the code.
 *              0x00000001    ONCRPC Server Cleanup Support
 * proghash   : Unique hash value that represents the API XDR definition
 * cbproghash : Unique hash value that represents the Callbacks' XDR definition
 */
extern boolean ping_mdm_rpc_rpc_glue_code_info_remote    /* REMOTE INFO */
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
);
extern boolean ping_mdm_rpc_rpc_glue_code_info_local     /* LOCAL INFO */
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
);

/* prototype for API null routine */
extern boolean ping_mdm_rpc_null(void);

/* prototype for API version function */
extern uint32 *ping_mdm_rpc_api_versions
(
   uint32 *len
);

/* Start forward xdr procedure numbers */

#define ONCRPC_PING_MDM_RPC_NULL_PROC 0 
 #define ONCRPC_PING_MDM_RPC_RPC_GLUE_CODE_INFO_REMOTE_PROC 1 
 #define ONCRPC_PING_MDM_REGISTER_PROC 2 
 #define ONCRPC_PING_MDM_UN_REGISTER_PROC 3 
 #define ONCRPC_PING_MDM_DATA_PROC 4 
 #define ONCRPC_PING_MDM_UN_REGISTER_DATA_CB_PROC 5 
 #define ONCRPC_PING_MDM_REGISTER_DATA_CB_PROC 6 
 #define ONCRPC_PING_MDM_GET_MAX_TASKS_PROC 7 
 #define ONCRPC_PING_MDM_RESET_NOMINAL_TASKS_PROC 8 
 #define ONCRPC_PING_MDM_GET_CURRENT_NUM_TASKS_PROC 9 
 #define ONCRPC_PING_MDM_REGISTER_RANDOM_DATA_CB_PROC 10 
 #define ONCRPC_PING_MDM_RPC_API_VERSIONS_PROC 0xffffffff 















/* End forward xdr procedure numbers */
/* Start callback xdr procedure numbers */
#define ONCRPC_PING_MDM_DATA_CB_F_TYPE_PROC 1 
 #define ONCRPC_PING_MDM_CB_F_TYPE_PROC 2 


/* End callback xdr procedure numbers */


/* XDR Routine Prototypes go here */

#endif /* ! PING_MDM_RPC_RPC_H */
