#ifndef MCS_HWIO_H
#define MCS_HWIO_H
/*===========================================================================

                 M O D E M   H W I O   H E A D E R    F I L E

DESCRIPTION
  All the declarations and definitions necessary to support interaction
  with the QUALCOMM Modem/MSS/Nav hardware for MSM8960.

REFERENCES
  CDMA Mobile Station ASIC Specification Sheet

  Copyright (c) 2014 Qualcomm Technologies Incorporated.
  All Rights Reserved.
  Qualcomm Confidential and Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.
===========================================================================*/

/*===========================================================================

                     INCLUDE FILES FOR MODULE

===========================================================================*/

/*
 * Basic HWIO definitions.
 */
#include "msmhwio.h"

/*
 * Chipset specific base addresses.
 */
#include "msmhwiobase.h"

/*
 * Autogenerated files.
 */
#include "mcs_hwio_modem.h"

/*
 * Manually generated files.
 */
#include "mcs_hwio_ver.h"
#include "mcs_int_map.h"

/*===========================================================================

                        DATA DECLARATIONS

===========================================================================*/


#endif  /* MCS_HWIO_H */

