#ifndef HDR_VARIATION_H
#define HDR_VARIATION_H

/* This file is autogenerated from the FEATURE database
 * It defines a) global features required for target=M8974 variant=AAAAANAAM and used by <hdr>
 *            b) top level features used exclusively by <hdr>
 *    A global feature is defined as being used by more than one SU.
 *    A top level feature is a feature that is expected to vary between build variants.
 *
 * - By including this file instead of customer.h, <hdr> decouples itself from other team's cust files.
 * - Only features defined in this file vary the compilation of <hdr>.
 * - At the bottom this file includes a manually maintained file owned by <hdr> where <hdr>
 *   can define other features that are derived from these top level features.
 * - Mainlining or eliminating global features that are not legitimate top level features will reduce
 *   the size of this file.
 */ 

/* For Phase 1 just keep customer.h and make sure it gets included first */
#include <customer.h>


#include "hdr_local_defines.h"

#endif /* HDR_VARIATION_H */
