#ifndef AEEDATETIME_IDL
#define AEEDATETIME_IDL

/*qidl location=top target=all % 
===============================================================================
FILE: AEEDateTime

SERVICES: None

DESCRIPTION:
   This file contains the method definitions for the DateTime and Daylight 
   adjustment.
   
PUBLIC CLASSES: None
 
INITIALIZATION AND SEQUENCING REQUIREMENTS:  None
 
   Copyright (c) 2008 QUALCOMM Incorporated.   
   All Rights Reserved.
   Qualcomm Confidential and Proprietary
===============================================================================
*/

#include "AEEStdDef.idl"


struct AEEDateTime {
   uint16   wYear;
   uint16   wMonth;
   uint16   wDay;
   uint16   wHour;
   uint16   wMinute;
   uint16   wSecond;
   uint16   wWeekDay;
};


/*qidl location=bottom target=all % 
%==============================================================================
DATA STRUCTURES DOCUMENTATION
===============================================================================
AEEDateTime

Description: 
   This structure contains date and time information.

Definition:

struct AEEDateTime {
   uint16   wYear;
   uint16   wMonth;
   uint16   wDay;
   uint16   wHour;
   uint16   wMinute;
   uint16   wSecond;
   uint16   wWeekDay;
};

Members:
   wYear : 4-digit year 
   wMonth : Month 1-12 (January=1, December=12) 
   wDay : Day 1-31
   wHour : Hour 0-23 
   wMinute : Minute 0-59 
   wSecond : Seconds 0-59 
   wWeekDay : Day of the week 0-6 (0=Monday, 6=Sunday)
   
Comments: 
   None

See Also:
   tapi_MMInfo.
===============================================================================
*/

#endif /* ifndef AEEDATETIME_IDL*/
