#ifndef IMAGE_VERSION_QC_AUTO_UPDATE_H
#define IMAGE_VERSION_QC_AUTO_UPDATE_H

#ifndef QC_IMAGE_VERSION_OVERRIDE_STRING
  #define QC_IMAGE_VERSION_STRING_AUTO_UPDATED 	"TZ.BF.2.0.T200053.2"
#else
  #define QC_IMAGE_VERSION_STRING_AUTO_UPDATED 	QC_IMAGE_VERSION_OVERRIDE_STRING
#endif

#endif  /* IMAGE_VERSION_QC_AUTO_UPDATE_H */

