#ifndef IMAGE_VERSION_OEM_AUTO_UPDATE_H
#define IMAGE_VERSION_OEM_AUTO_UPDATE_H

#ifndef OEM_IMAGE_VERSION_OVERRIDE_STRING
  #define OEM_IMAGE_VERSION_STRING_AUTO_UPDATED 	"OEM VERSION GOES IN THESE BYTES."
#else
  #define OEM_IMAGE_VERSION_STRING_AUTO_UPDATED 	OEM_IMAGE_VERSION_OVERRIDE_STRING
#endif

#endif  /* IMAGE_VERSION_OEM_AUTO_UPDATE_H */

