# specify the COM port
$comport = 9;
#
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile00 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile01 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile02 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile03 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile04 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile05 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile06 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile07 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile08 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile09 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile10 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile11 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile12 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile13 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile14 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile15 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile16 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile17 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile18 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile19 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile20 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile21 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile22 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile23 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile24 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile25 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile26 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile27 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile28 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile29 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile30 $comport");
sleep(1);
system("perl pd_file_delete_with_qxdm_del_resp.pl AlmFile31 $comport");
sleep(1);

