#ifndef __VSS_ITTYOOB_PUBLIC_IF_H__
#define __VSS_ITTYOOB_PUBLIC_IF_H__

/**
  @file vss_ittyoob_public_if.h
  @brief This file contains the APR API definitions for Teletypewriter (TTY) 
  out of band (OOB).
*/

/*===========================================================================
NOTE: The @brief description and any detailed descriptions above do not appear 
      in the PDF. 

      The CVD_mainpage.dox file contains all file/group descriptions 
      that are in the output PDF generated using Doxygen and Latex. To edit or 
      update any of the file/group text in the PDF, edit the 
      CVD_mainpage.dox file or contact Tech Pubs.

      The above description for this file is part of the vss_itty_public_if 
      group description in the CVD_mainpage.dox file. 
=============================================================================*/
/*===========================================================================
Copyright (C) 2013 QUALCOMM Technologies Incorporated.
All rights reserved.
Qualcomm Confidential and Proprietary
===========================================================================*/

#include "apr_comdef.h"

/** @addtogroup vss_ittyoob_public_if
@{ */

/****************************************************************************
 * TELETYPEWRITER (TTY) Out of Band (OOB) APIS                                            *
 ****************************************************************************/

/**
  This command allows a client to register for accessing out of band TTY
  character data interface.
 
  @par Payload
  none.
 
  @return 
  #APRV2_IBASIC_RSP_RESULT

  @dependencies
  The HLOS is expected to enable a TTY device and set the correct mode
  (VCO,  HCO, or FULL). The out of band TTY stream client must call this 
  registration API before MVM is commanded to start voice.

*/
#define VSS_ITTYOOB_CMD_REGISTER ( 0x00012E76 )
  

/**
  Command to deregister access for OOB TTY Characters.
 
  @par Payload
  none.
 
  @return 
  #APRV2_IBASIC_RSP_RESULT

  @dependencies
  This command will disable OOBTTY events exchange.

*/
#define VSS_ITTYOOB_CMD_DEREGISTER ( 0x00012E77 )


/**
  Event to send a detected character to Client.
 
  @par Payload
  #vss_ittyoob_evt_tx_char_t
 
  @return 
  None.

  @dependencies
  These events are generated by the stream only when it is in READY state.

*/
#define VSS_ITTYOOB_EVT_SEND_TX_CHAR ( 0x00012E78 )

/** @brief Type definition for #vss_ittyoob_evt_tx_char_t.
*/
typedef struct vss_ittyoob_evt_tx_char_t vss_ittyoob_evt_tx_char_t;

#include "apr_pack_begin.h"
/** @brief Payload structure for the #VSS_ITTYOOB_EVT_SEND_TX_CHAR 
    event.
*/
struct vss_ittyoob_evt_tx_char_t
{
  uint16_t tty_char;		
   /**< Character in UTF-16 format. */
}
#include "apr_pack_end.h"
;


/**
  Command from Client to send a character.
 
  @par Payload
  #vss_ittyoob_cmd_rx_char_t
 
  @return 
  #APRV2_IBASIC_RSP_RESULT

  @dependencies
  These command is accepted by the stream only when it is in READY state,
  otherwise stream will reply with response #APR_EFAILED.

*/
#define VSS_ITTYOOB_CMD_SEND_RX_CHAR ( 0x00012E79 )

/** @brief Type definition for #vss_ittyoob_cmd_rx_char_t.
*/
typedef struct vss_ittyoob_cmd_rx_char_t vss_ittyoob_cmd_rx_char_t;

#include "apr_pack_begin.h"
/** @brief Payload structure for the #VSS_ITTYOOB_CMD_SEND_RX_CHAR 
    event.
*/
struct vss_ittyoob_cmd_rx_char_t
{
  uint16_t tty_char;		
   /**< Character in UTF-16 format. */
}
#include "apr_pack_end.h"
;

/** @} */ /* end_addtogroup vss_ittyoob_public_if */

#endif /* __VSS_ITTYOOB_PUBLIC_IF_H__ */

