#ifndef __HAL_CLK_TEST_H__
#define __HAL_CLK_TEST_H__

/*
==============================================================================

FILE:         HALclkTest.h

DESCRIPTION:
  This file contains the ids for configuring the debug clock circuitry
  for the clock HAL.

==============================================================================

                             Edit History

$Header: //components/rel/rpm.bf/2.1.1/core/systemdrivers/hal/clk/hw/msm8976/inc/HALclkTest.h#1 $

when          who     what, where, why
----------    ---     --------------------------------------------------------
05/30/2014            Auto-generated.

==============================================================================
            Copyright (c) 2014 QUALCOMM Technologies Incorporated.
                    All Rights Reserved.
                  QUALCOMM Proprietary/GTDR
==============================================================================
*/


/*============================================================================

             DEFINITIONS AND DECLARATIONS FOR MODULE

=============================================================================*/


/* ============================================================================
**    Defines
** ==========================================================================*/

/*
 * Masks used during test clock frequency calculation setup.
 */
#define HAL_CLK_TEST_TYPE_MASK    (0xF0000)
#define HAL_CLK_TEST_SEL_MASK     (0x07FFF)


/*
 * Subsystem domains
 */
#define HAL_CLK_GCC_TEST          (2 << 0x10)
#define HAL_CLK_MSS_TEST          (5 << 0x10)
#define HAL_CLK_WCSS_TEST         (6 << 0x10)


/*
 * GCC debug clocks
 */
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_AXI_CLK                                    (HAL_CLK_GCC_TEST | 0x000)
#define HAL_CLK_GCC_TEST_GCC_SYS_MM_NOC_AXI_CLK                                 (HAL_CLK_GCC_TEST | 0x001)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_QDSS_STM_AXI_CLK                           (HAL_CLK_GCC_TEST | 0x002)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_APSS_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x003)
#define HAL_CLK_GCC_TEST_GCC_SNOC_PCNOC_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x004)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_IPA_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x005)
#define HAL_CLK_GCC_TEST_GCC_SYS_NOC_AT_CLK                                     (HAL_CLK_GCC_TEST | 0x006)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x008)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_DDR_CFG_CLK                                  (HAL_CLK_GCC_TEST | 0x009)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_RPM_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x00A)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_TIC_CLK                                      (HAL_CLK_GCC_TEST | 0x00B)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_AT_CLK                                       (HAL_CLK_GCC_TEST | 0x00C)
#define HAL_CLK_GCC_TEST_GCC_GP1_CLK                                            (HAL_CLK_GCC_TEST | 0x010)
#define HAL_CLK_GCC_TEST_GCC_GP2_CLK                                            (HAL_CLK_GCC_TEST | 0x011)
#define HAL_CLK_GCC_TEST_GCC_GP3_CLK                                            (HAL_CLK_GCC_TEST | 0x012)
#define HAL_CLK_GCC_TEST_GCC_NOC_CONF_XPU_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x018)
#define HAL_CLK_GCC_TEST_GCC_IMEM_AXI_CLK                                       (HAL_CLK_GCC_TEST | 0x020)
#define HAL_CLK_GCC_TEST_GCC_IMEM_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x021)
#define HAL_CLK_GCC_TEST_GCC_GMEM_SYS_NOC_AXI_CLK                               (HAL_CLK_GCC_TEST | 0x028)
#define HAL_CLK_GCC_TEST_GCC_BIMC_GFX_CLK                                       (HAL_CLK_GCC_TEST | 0x02D)
#define HAL_CLK_GCC_TEST_GCC_MSS_CFG_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x030)
#define HAL_CLK_GCC_TEST_GCC_MSS_Q6_BIMC_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x031)
#define HAL_CLK_GCC_TEST_MSS_GCC_DBG_CLK                                        (HAL_CLK_GCC_TEST | 0x032)
#define HAL_CLK_GCC_TEST_GCC_RPM_CFG_XPU_CLK                                    (HAL_CLK_GCC_TEST | 0x038)
#define HAL_CLK_GCC_TEST_GCC_QDSS_DAP_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x040)
#define HAL_CLK_GCC_TEST_GCC_QDSS_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x041)
#define HAL_CLK_GCC_TEST_GCC_QDSS_AT_CLK                                        (HAL_CLK_GCC_TEST | 0x042)
#define HAL_CLK_GCC_TEST_GCC_QDSS_ETR_USB_CLK                                   (HAL_CLK_GCC_TEST | 0x043)
#define HAL_CLK_GCC_TEST_GCC_QDSS_STM_CLK                                       (HAL_CLK_GCC_TEST | 0x044)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TRACECLKIN_CLK                                (HAL_CLK_GCC_TEST | 0x045)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV2_CLK                                (HAL_CLK_GCC_TEST | 0x046)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV3_CLK                                (HAL_CLK_GCC_TEST | 0x048)
#define HAL_CLK_GCC_TEST_GCC_QDSS_DAP_CLK                                       (HAL_CLK_GCC_TEST | 0x049)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV4_CLK                                (HAL_CLK_GCC_TEST | 0x04A)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV8_CLK                                (HAL_CLK_GCC_TEST | 0x04B)
#define HAL_CLK_GCC_TEST_GCC_QDSS_TSCTR_DIV16_CLK                               (HAL_CLK_GCC_TEST | 0x04C)
#define HAL_CLK_GCC_TEST_GCC_APSS_TCU_ASYNC_CLK                                 (HAL_CLK_GCC_TEST | 0x050)
#define HAL_CLK_GCC_TEST_GCC_MDP_TBU_CLK                                        (HAL_CLK_GCC_TEST | 0x051)
#define HAL_CLK_GCC_TEST_GCC_GFX_TBU_CLK                                        (HAL_CLK_GCC_TEST | 0x052)
#define HAL_CLK_GCC_TEST_GCC_GFX_TCU_CLK                                        (HAL_CLK_GCC_TEST | 0x053)
#define HAL_CLK_GCC_TEST_GCC_VENUS_TBU_CLK                                      (HAL_CLK_GCC_TEST | 0x054)
#define HAL_CLK_GCC_TEST_GCC_MSS_TBU_AXI_CLK                                    (HAL_CLK_GCC_TEST | 0x055)
#define HAL_CLK_GCC_TEST_GCC_MSS_TBU_GSS_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x056)
#define HAL_CLK_GCC_TEST_GCC_MSS_TBU_Q6_AXI_CLK                                 (HAL_CLK_GCC_TEST | 0x057)
#define HAL_CLK_GCC_TEST_GCC_GTCU_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x058)
#define HAL_CLK_GCC_TEST_GCC_SMMU_XPU_CLK                                       (HAL_CLK_GCC_TEST | 0x059)
#define HAL_CLK_GCC_TEST_GCC_VFE_TBU_CLK                                        (HAL_CLK_GCC_TEST | 0x05A)
#define HAL_CLK_GCC_TEST_GCC_SMMU_CFG_CLK                                       (HAL_CLK_GCC_TEST | 0x05B)
#define HAL_CLK_GCC_TEST_GCC_JPEG_TBU_CLK                                       (HAL_CLK_GCC_TEST | 0x05C)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_TBU_CLK                                      (HAL_CLK_GCC_TEST | 0x05D)
#define HAL_CLK_GCC_TEST_GCC_PRONTO_TBU_CLK                                     (HAL_CLK_GCC_TEST | 0x05E)
#define HAL_CLK_GCC_TEST_GCC_SMMU_CATS_CLK                                      (HAL_CLK_GCC_TEST | 0x05F)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_SYSTEM_CLK                                  (HAL_CLK_GCC_TEST | 0x060)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_AHB_CLK                                     (HAL_CLK_GCC_TEST | 0x061)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_INACTIVITY_TIMERS_CLK                       (HAL_CLK_GCC_TEST | 0x062)
#define HAL_CLK_GCC_TEST_GCC_USB2A_PHY_SLEEP_CLK                                (HAL_CLK_GCC_TEST | 0x063)
#define HAL_CLK_GCC_TEST_GCC_USB_HS_PHY_CFG_AHB_CLK                             (HAL_CLK_GCC_TEST | 0x064)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x068)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x069)
#define HAL_CLK_GCC_TEST_GCC_SDCC1_ICE_CORE_CLK                                 (HAL_CLK_GCC_TEST | 0x06A)
#define HAL_CLK_GCC_TEST_GCC_SDCC2_APPS_CLK                                     (HAL_CLK_GCC_TEST | 0x070)
#define HAL_CLK_GCC_TEST_GCC_SDCC2_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x071)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x088)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_SLEEP_CLK                                    (HAL_CLK_GCC_TEST | 0x089)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP1_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08A)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP1_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08B)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART1_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x08C)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART1_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x08D)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP2_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x08E)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP2_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x090)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART2_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x091)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_UART2_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x092)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP3_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x093)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP3_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x094)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP4_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x095)
#define HAL_CLK_GCC_TEST_GCC_BLSP1_QUP4_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x096)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x098)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_SLEEP_CLK                                    (HAL_CLK_GCC_TEST | 0x099)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP1_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x09A)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP1_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x09B)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART1_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x09C)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART1_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x09D)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP2_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x09E)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP2_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A0)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART2_APPS_CLK                               (HAL_CLK_GCC_TEST | 0x0A1)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_UART2_SIM_CLK                                (HAL_CLK_GCC_TEST | 0x0A2)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP3_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A3)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP3_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A4)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP4_SPI_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A5)
#define HAL_CLK_GCC_TEST_GCC_BLSP2_QUP4_I2C_APPS_CLK                            (HAL_CLK_GCC_TEST | 0x0A6)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_TOP_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x0A8)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x0A9)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_MICRO_AHB_CLK                                (HAL_CLK_GCC_TEST | 0x0AA)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_GP0_CLK                                      (HAL_CLK_GCC_TEST | 0x0AB)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_GP1_CLK                                      (HAL_CLK_GCC_TEST | 0x0AC)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_MCLK0_CLK                                    (HAL_CLK_GCC_TEST | 0x0AD)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_MCLK1_CLK                                    (HAL_CLK_GCC_TEST | 0x0AE)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CCI_CLK                                      (HAL_CLK_GCC_TEST | 0x0AF)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CCI_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x0B0)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0PHYTIMER_CLK                             (HAL_CLK_GCC_TEST | 0x0B1)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1PHYTIMER_CLK                             (HAL_CLK_GCC_TEST | 0x0B2)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_JPEG0_CLK                                    (HAL_CLK_GCC_TEST | 0x0B3)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_JPEG_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x0B4)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_JPEG_AXI_CLK                                 (HAL_CLK_GCC_TEST | 0x0B5)
#define HAL_CLK_GCC_TEST_GCC_JPEG_QDSS_AT_CLK                                   (HAL_CLK_GCC_TEST | 0x0B6)
#define HAL_CLK_GCC_TEST_GCC_JPEG_QDSS_TSCTR_DIV8_CLK                           (HAL_CLK_GCC_TEST | 0x0B7)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE0_CLK                                     (HAL_CLK_GCC_TEST | 0x0B8)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CPP_CLK                                      (HAL_CLK_GCC_TEST | 0x0B9)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CPP_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x0BA)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x0BB)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE_AXI_CLK                                  (HAL_CLK_GCC_TEST | 0x0BC)
#define HAL_CLK_GCC_TEST_GCC_VFE_QDSS_AT_CLK                                    (HAL_CLK_GCC_TEST | 0x0BD)
#define HAL_CLK_GCC_TEST_GCC_VFE_QDSS_TSCTR_DIV8_CLK                            (HAL_CLK_GCC_TEST | 0x0BE)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI_VFE0_CLK                                 (HAL_CLK_GCC_TEST | 0x0BF)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0_CLK                                     (HAL_CLK_GCC_TEST | 0x0C0)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x0C1)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0PHY_CLK                                  (HAL_CLK_GCC_TEST | 0x0C2)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0RDI_CLK                                  (HAL_CLK_GCC_TEST | 0x0C3)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI0PIX_CLK                                  (HAL_CLK_GCC_TEST | 0x0C4)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1_CLK                                     (HAL_CLK_GCC_TEST | 0x0C5)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x0C6)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1PHY_CLK                                  (HAL_CLK_GCC_TEST | 0x0C7)
#define HAL_CLK_GCC_TEST_GCC_PRNG_XPU_CFG_AHB_CLK                               (HAL_CLK_GCC_TEST | 0x0C8)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_MPU_CFG_AHB_CLK                              (HAL_CLK_GCC_TEST | 0x0C9)
#define HAL_CLK_GCC_TEST_GCC_PDM_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x0D0)
#define HAL_CLK_GCC_TEST_GCC_PDM_XO4_CLK                                        (HAL_CLK_GCC_TEST | 0x0D1)
#define HAL_CLK_GCC_TEST_GCC_PDM2_CLK                                           (HAL_CLK_GCC_TEST | 0x0D2)
#define HAL_CLK_GCC_TEST_GCC_PRNG_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x0D8)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1RDI_CLK                                  (HAL_CLK_GCC_TEST | 0x0E0)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI1PIX_CLK                                  (HAL_CLK_GCC_TEST | 0x0E1)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_ISPIF_AHB_CLK                                (HAL_CLK_GCC_TEST | 0x0E2)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI2_CLK                                     (HAL_CLK_GCC_TEST | 0x0E3)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI2_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x0E4)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI2PHY_CLK                                  (HAL_CLK_GCC_TEST | 0x0E5)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI2RDI_CLK                                  (HAL_CLK_GCC_TEST | 0x0E6)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI2PIX_CLK                                  (HAL_CLK_GCC_TEST | 0x0E7)
#define HAL_CLK_GCC_TEST_GCC_TCSR_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x0E8)
#define HAL_CLK_GCC_TEST_GCC_CPP_TBU_CLK                                        (HAL_CLK_GCC_TEST | 0x0E9)
#define HAL_CLK_GCC_TEST_GCC_CPP_QDSS_TSCTR_DIV8_CLK                            (HAL_CLK_GCC_TEST | 0x0ED)
#define HAL_CLK_GCC_TEST_GCC_BOOT_ROM_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x0F0)
#define HAL_CLK_GCC_TEST_GCC_USB_FS_SYSTEM_CLK                                  (HAL_CLK_GCC_TEST | 0x0F0)
#define HAL_CLK_GCC_TEST_GCC_USB_FS_AHB_CLK                                     (HAL_CLK_GCC_TEST | 0x0F1)
#define HAL_CLK_GCC_TEST_GCC_USB_FS_IC_CLK                                      (HAL_CLK_GCC_TEST | 0x0F4)
#define HAL_CLK_GCC_TEST_GCC_MSG_RAM_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x0F8)
#define HAL_CLK_GCC_TEST_GCC_TLMM_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x100)
#define HAL_CLK_GCC_TEST_GCC_TLMM_CLK                                           (HAL_CLK_GCC_TEST | 0x101)
#define HAL_CLK_GCC_TEST_GCC_MPM_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x108)
#define HAL_CLK_GCC_TEST_GCC_RPM_PROC_FCLK                                      (HAL_CLK_GCC_TEST | 0x110)
#define HAL_CLK_GCC_TEST_GCC_RPM_PROC_HCLK                                      (HAL_CLK_GCC_TEST | 0x111)
#define HAL_CLK_GCC_TEST_GCC_RPM_BUS_AHB_CLK                                    (HAL_CLK_GCC_TEST | 0x112)
#define HAL_CLK_GCC_TEST_GCC_RPM_SLEEP_CLK                                      (HAL_CLK_GCC_TEST | 0x113)
#define HAL_CLK_GCC_TEST_GCC_RPM_TIMER_CLK                                      (HAL_CLK_GCC_TEST | 0x114)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_ACC_CLK                                   (HAL_CLK_GCC_TEST | 0x118)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x119)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_CLK                                       (HAL_CLK_GCC_TEST | 0x11A)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_SENSE_CLK                                 (HAL_CLK_GCC_TEST | 0x11B)
#define HAL_CLK_GCC_TEST_GCC_SEC_CTRL_BOOT_ROM_PATCH_CLK                        (HAL_CLK_GCC_TEST | 0x11C)
#define HAL_CLK_GCC_TEST_GCC_SPMI_SER_CLK                                       (HAL_CLK_GCC_TEST | 0x120)
#define HAL_CLK_GCC_TEST_GCC_SPMI_PCNOC_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x121)
#define HAL_CLK_GCC_TEST_GCC_SPMI_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x122)
#define HAL_CLK_GCC_TEST_GCC_SPDM_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x128)
#define HAL_CLK_GCC_TEST_GCC_SPDM_MSTR_AHB_CLK                                  (HAL_CLK_GCC_TEST | 0x129)
#define HAL_CLK_GCC_TEST_GCC_SPDM_FF_CLK                                        (HAL_CLK_GCC_TEST | 0x12A)
#define HAL_CLK_GCC_TEST_GCC_SPDM_BIMC_CY_CLK                                   (HAL_CLK_GCC_TEST | 0x12B)
#define HAL_CLK_GCC_TEST_GCC_SPDM_SNOC_CY_CLK                                   (HAL_CLK_GCC_TEST | 0x12C)
#define HAL_CLK_GCC_TEST_GCC_SPDM_PCNOC_CY_CLK                                  (HAL_CLK_GCC_TEST | 0x12D)
#define HAL_CLK_GCC_TEST_GCC_SPDM_RPM_CY_CLK                                    (HAL_CLK_GCC_TEST | 0x12E)
#define HAL_CLK_GCC_TEST_GCC_SPDM_MM_SNOC_CY_CLK                                (HAL_CLK_GCC_TEST | 0x12F)
#define HAL_CLK_GCC_TEST_GCC_CRYPTO_CLK                                         (HAL_CLK_GCC_TEST | 0x130)
#define HAL_CLK_GCC_TEST_GCC_CRYPTO_AXI_CLK                                     (HAL_CLK_GCC_TEST | 0x131)
#define HAL_CLK_GCC_TEST_GCC_CRYPTO_AHB_CLK                                     (HAL_CLK_GCC_TEST | 0x132)
#define HAL_CLK_GCC_TEST_GCC_AHB_CLK                                            (HAL_CLK_GCC_TEST | 0x140)
#define HAL_CLK_GCC_TEST_GCC_SPDM_CSI0_CLK                                      (HAL_CLK_GCC_TEST | 0x140)
#define HAL_CLK_GCC_TEST_GCC_XO_CLK                                             (HAL_CLK_GCC_TEST | 0x141)
#define HAL_CLK_GCC_TEST_GCC_SPDM_PCLK0_CLK                                     (HAL_CLK_GCC_TEST | 0x141)
#define HAL_CLK_GCC_TEST_GCC_XO_DIV4_CLK                                        (HAL_CLK_GCC_TEST | 0x142)
#define HAL_CLK_GCC_TEST_GCC_SPDM_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x142)
#define HAL_CLK_GCC_TEST_GCC_IM_SLEEP_CLK                                       (HAL_CLK_GCC_TEST | 0x143)
#define HAL_CLK_GCC_TEST_GCC_SPDM_GFX3D_CLK                                     (HAL_CLK_GCC_TEST | 0x143)
#define HAL_CLK_GCC_TEST_GCC_SPDM_VFE0_CLK                                      (HAL_CLK_GCC_TEST | 0x144)
#define HAL_CLK_GCC_TEST_GCC_SPDM_VCODEC0_CLK                                   (HAL_CLK_GCC_TEST | 0x145)
#define HAL_CLK_GCC_TEST_GCC_SPDM_MDP_CLK                                       (HAL_CLK_GCC_TEST | 0x146)
#define HAL_CLK_GCC_TEST_GCC_SPDM_JPEG0_CLK                                     (HAL_CLK_GCC_TEST | 0x147)
#define HAL_CLK_GCC_TEST_GCC_BIMC_XO_CLK                                        (HAL_CLK_GCC_TEST | 0x150)
#define HAL_CLK_GCC_TEST_GCC_BIMC_CFG_AHB_CLK                                   (HAL_CLK_GCC_TEST | 0x151)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SLEEP_CLK                                     (HAL_CLK_GCC_TEST | 0x152)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SYSNOC_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x153)
#define HAL_CLK_GCC_TEST_GCC_BIMC_CLK                                           (HAL_CLK_GCC_TEST | 0x154)
#define HAL_CLK_GCC_TEST_GCC_BIMC_APSS_AXI_CLK                                  (HAL_CLK_GCC_TEST | 0x155)
#define HAL_CLK_GCC_TEST_GCC_BIMC_AT_CLK                                        (HAL_CLK_GCC_TEST | 0x156)
#define HAL_CLK_GCC_TEST_GCC_BIMC_GPU_CLK                                       (HAL_CLK_GCC_TEST | 0x157)
#define HAL_CLK_GCC_TEST_GCC_DDR_DIM_CFG_CLK                                    (HAL_CLK_GCC_TEST | 0x158)
#define HAL_CLK_GCC_TEST_GCC_BIMC_APSS_TCU_CLK                                  (HAL_CLK_GCC_TEST | 0x159)
#define HAL_CLK_GCC_TEST_GCC_BIMC_DDR_CH0_CLK                                   (HAL_CLK_GCC_TEST | 0x15A)
#define HAL_CLK_GCC_TEST_GCC_DDR_DIM_SLEEP_CLK                                  (HAL_CLK_GCC_TEST | 0x15B)
#define HAL_CLK_GCC_TEST_GCC_BIMC_DDR_CPLL0_CLK                                 (HAL_CLK_GCC_TEST | 0x15C)
#define HAL_CLK_GCC_TEST_GCC_BIMC_DDR_CPLL1_CLK                                 (HAL_CLK_GCC_TEST | 0x15D)
#define HAL_CLK_GCC_TEST_GCC_BIMC_SYSNOC_MM_AXI_CLK                             (HAL_CLK_GCC_TEST | 0x15F)
#define HAL_CLK_GCC_TEST_GCC_LPASS_Q6_AXI_CLK                                   (HAL_CLK_GCC_TEST | 0x160)
#define HAL_CLK_GCC_TEST_LPASS_GCC_DBG_CLK                                      (HAL_CLK_GCC_TEST | 0x161)
#define HAL_CLK_GCC_TEST_GCC_LPASS_MPORT_AXI_CLK                                (HAL_CLK_GCC_TEST | 0x162)
#define HAL_CLK_GCC_TEST_GCC_LPASS_SWAY_CLK                                     (HAL_CLK_GCC_TEST | 0x163)
#define HAL_CLK_GCC_TEST_GCC_APSS_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x168)
#define HAL_CLK_GCC_TEST_GCC_APSS_AXI_CLK                                       (HAL_CLK_GCC_TEST | 0x169)
#define HAL_CLK_GCC_TEST_APSS_GCC_DBG_CLK                                       (HAL_CLK_GCC_TEST | 0x16A)
#define HAL_CLK_GCC_TEST_GCC_SNOC_BUS_TIMEOUT0_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x170)
#define HAL_CLK_GCC_TEST_GCC_SNOC_BUS_TIMEOUT2_AHB_CLK                          (HAL_CLK_GCC_TEST | 0x171)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT0_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x178)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT1_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x179)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT2_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x17A)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT3_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x17B)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT4_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x17C)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT5_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x180)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT6_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x181)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT7_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x182)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT8_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x183)
#define HAL_CLK_GCC_TEST_GCC_PCNOC_BUS_TIMEOUT9_AHB_CLK                         (HAL_CLK_GCC_TEST | 0x184)
#define HAL_CLK_GCC_TEST_GCC_DEHR_CLK                                           (HAL_CLK_GCC_TEST | 0x188)
#define HAL_CLK_GCC_TEST_GCC_RBCPR_CLK                                          (HAL_CLK_GCC_TEST | 0x190)
#define HAL_CLK_GCC_TEST_GCC_RBCPR_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x191)
#define HAL_CLK_GCC_TEST_GCC_IPA_TBU_CLK                                        (HAL_CLK_GCC_TEST | 0x198)
#define HAL_CLK_GCC_TEST_WCSS_GCC_DBG_CLK                                       (HAL_CLK_GCC_TEST | 0x198)
#define HAL_CLK_GCC_TEST_GCC_VFE1_TBU_CLK                                       (HAL_CLK_GCC_TEST | 0x199)
#define HAL_CLK_GCC_TEST_GCC_LPASS_TBU_CLK                                      (HAL_CLK_GCC_TEST | 0x19A)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CSI_VFE1_CLK                                 (HAL_CLK_GCC_TEST | 0x1A0)
#define HAL_CLK_GCC_TEST_USB2_PHY_GCC_ATEST_ULPI_0_CLK                          (HAL_CLK_GCC_TEST | 0x1A0)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE1_CLK                                     (HAL_CLK_GCC_TEST | 0x1A1)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE1_AHB_CLK                                 (HAL_CLK_GCC_TEST | 0x1A2)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_VFE1_AXI_CLK                                 (HAL_CLK_GCC_TEST | 0x1A3)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_CPP_AXI_CLK                                  (HAL_CLK_GCC_TEST | 0x1A3)
#define HAL_CLK_GCC_TEST_GCC_VFE1_QDSS_AT_CLK                                   (HAL_CLK_GCC_TEST | 0x1A5)
#define HAL_CLK_GCC_TEST_GCC_VFE1_QDSS_TSCTR_DIV8_CLK                           (HAL_CLK_GCC_TEST | 0x1A6)
#define HAL_CLK_GCC_TEST_GCC_CPP_QDSS_AT_CLK                                    (HAL_CLK_GCC_TEST | 0x1A7)
#define HAL_CLK_GCC_TEST_USB2_PHY_GCC_ATEST_ULPI_1_CLK                          (HAL_CLK_GCC_TEST | 0x1A8)
#define HAL_CLK_GCC_TEST_GCC_IPA_CLK                                            (HAL_CLK_GCC_TEST | 0x1B0)
#define HAL_CLK_GCC_TEST_GCC_IPA_AHB_CLK                                        (HAL_CLK_GCC_TEST | 0x1B1)
#define HAL_CLK_GCC_TEST_GCC_IPA_SLEEP_CLK                                      (HAL_CLK_GCC_TEST | 0x1B2)
#define HAL_CLK_GCC_TEST_GCC_IPA_2X_CLK                                         (HAL_CLK_GCC_TEST | 0x1B3)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_CORE0_VCODEC0_CLK                           (HAL_CLK_GCC_TEST | 0x1B8)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_CORE1_VCODEC0_CLK                           (HAL_CLK_GCC_TEST | 0x1B9)
#define HAL_CLK_GCC_TEST_GCC_CAMSS_MCLK2_CLK                                    (HAL_CLK_GCC_TEST | 0x1BD)
#define HAL_CLK_GCC_TEST_GCC_SPDM_BIMC_DDR_CH0_CY_CLK                           (HAL_CLK_GCC_TEST | 0x1BE)
#define HAL_CLK_GCC_TEST_GPLL0_DTEST                                            (HAL_CLK_GCC_TEST | 0x1C0)
#define HAL_CLK_GCC_TEST_GPLL0_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1C1)
#define HAL_CLK_GCC_TEST_BIMC_PLL_DTEST                                         (HAL_CLK_GCC_TEST | 0x1C4)
#define HAL_CLK_GCC_TEST_BIMC_PLL_LOCK_DET                                      (HAL_CLK_GCC_TEST | 0x1C5)
#define HAL_CLK_GCC_TEST_MPM_GCC_TEMP_SENSOR_RINGOSC_CLK                        (HAL_CLK_GCC_TEST | 0x1C8)
#define HAL_CLK_GCC_TEST_APSS_GCC_RINGOSC_CLK                                   (HAL_CLK_GCC_TEST | 0x1D0)
#define HAL_CLK_GCC_TEST_GPLL3_DTEST                                            (HAL_CLK_GCC_TEST | 0x1D8)
#define HAL_CLK_GCC_TEST_GPLL3_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1D9)
#define HAL_CLK_GCC_TEST_GPLL4_DTEST                                            (HAL_CLK_GCC_TEST | 0x1DA)
#define HAL_CLK_GCC_TEST_GPLL4_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1DB)
#define HAL_CLK_GCC_TEST_GPLL5_DTEST                                            (HAL_CLK_GCC_TEST | 0x1DC)
#define HAL_CLK_GCC_TEST_GPLL5_LOCK_DET                                         (HAL_CLK_GCC_TEST | 0x1DD)
#define HAL_CLK_GCC_TEST_GCC_DCD_XO_CLK                                         (HAL_CLK_GCC_TEST | 0x1E0)
#define HAL_CLK_GCC_TEST_GCC_OXILI_TIMER_CLK                                    (HAL_CLK_GCC_TEST | 0x1E9)
#define HAL_CLK_GCC_TEST_GCC_OXILI_GFX3D_CLK                                    (HAL_CLK_GCC_TEST | 0x1EA)
#define HAL_CLK_GCC_TEST_GCC_OXILI_AHB_CLK                                      (HAL_CLK_GCC_TEST | 0x1EB)
#define HAL_CLK_GCC_TEST_GCC_OXILI_QDSS_AT_CLK                                  (HAL_CLK_GCC_TEST | 0x1EC)
#define HAL_CLK_GCC_TEST_GCC_OXILI_QDSS_TSCTR_DIV8_CLK                          (HAL_CLK_GCC_TEST | 0x1ED)
#define HAL_CLK_GCC_TEST_GCC_SPDM_VFE1_CLK                                      (HAL_CLK_GCC_TEST | 0x1EE)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_QDSS_APB_CLK                                (HAL_CLK_GCC_TEST | 0x1EF)
#define HAL_CLK_GCC_TEST_GCC_OXILI_GMEM_CLK                                     (HAL_CLK_GCC_TEST | 0x1F0)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_VCODEC0_CLK                                 (HAL_CLK_GCC_TEST | 0x1F1)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_AXI_CLK                                     (HAL_CLK_GCC_TEST | 0x1F2)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_AHB_CLK                                     (HAL_CLK_GCC_TEST | 0x1F3)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_QDSS_AT_CLK                                 (HAL_CLK_GCC_TEST | 0x1F4)
#define HAL_CLK_GCC_TEST_GCC_VENUS0_QDSS_TSCTR_DIV8_CLK                         (HAL_CLK_GCC_TEST | 0x1F5)
#define HAL_CLK_GCC_TEST_GCC_MDSS_AHB_CLK                                       (HAL_CLK_GCC_TEST | 0x1F6)
#define HAL_CLK_GCC_TEST_GCC_MDSS_AXI_CLK                                       (HAL_CLK_GCC_TEST | 0x1F7)
#define HAL_CLK_GCC_TEST_GCC_MDSS_PCLK0_CLK                                     (HAL_CLK_GCC_TEST | 0x1F8)
#define HAL_CLK_GCC_TEST_GCC_MDSS_MDP_CLK                                       (HAL_CLK_GCC_TEST | 0x1F9)
#define HAL_CLK_GCC_TEST_GCC_MDSS_VSYNC_CLK                                     (HAL_CLK_GCC_TEST | 0x1FB)
#define HAL_CLK_GCC_TEST_GCC_MDSS_BYTE0_CLK                                     (HAL_CLK_GCC_TEST | 0x1FC)
#define HAL_CLK_GCC_TEST_GCC_MDSS_ESC0_CLK                                      (HAL_CLK_GCC_TEST | 0x1FD)
#define HAL_CLK_GCC_TEST_GCC_MDSS_QDSS_AT_CLK                                   (HAL_CLK_GCC_TEST | 0x1FE)
#define HAL_CLK_GCC_TEST_GCC_MDSS_QDSS_TSCTR_DIV8_CLK                           (HAL_CLK_GCC_TEST | 0x1FF)


/*
 * MSS debug clocks
 */
#define HAL_CLK_MSS_TEST_CLK_UIM2                                               (HAL_CLK_MSS_TEST | 0x01)
#define HAL_CLK_MSS_TEST_CLK_UIM0                                               (HAL_CLK_MSS_TEST | 0x02)
#define HAL_CLK_MSS_TEST_CLK_UIM1                                               (HAL_CLK_MSS_TEST | 0x03)
#define HAL_CLK_MSS_TEST_CLK_XO_UIM0                                            (HAL_CLK_MSS_TEST | 0x04)
#define HAL_CLK_MSS_TEST_CLK_XO_UIM1                                            (HAL_CLK_MSS_TEST | 0x05)
#define HAL_CLK_MSS_TEST_CLK_XO_Q6                                              (HAL_CLK_MSS_TEST | 0x07)
#define HAL_CLK_MSS_TEST_CLK_BIT_COXM_CLK                                       (HAL_CLK_MSS_TEST | 0x07)
#define HAL_CLK_MSS_TEST_CLK_SLEEP_Q6                                           (HAL_CLK_MSS_TEST | 0x09)
#define HAL_CLK_MSS_TEST_PLL_LOCK_DET_MPLL2                                     (HAL_CLK_MSS_TEST | 0x0A)
#define HAL_CLK_MSS_TEST_PLL_LOCK_DET_MPLL1                                     (HAL_CLK_MSS_TEST | 0x0B)
#define HAL_CLK_MSS_TEST_PLL_LOCK_DET_MPLL0                                     (HAL_CLK_MSS_TEST | 0x0C)
#define HAL_CLK_MSS_TEST_CLK_Q6_MON                                             (HAL_CLK_MSS_TEST | 0x0D)
#define HAL_CLK_MSS_TEST_CLK_BUS_BRIDGE_MON                                     (HAL_CLK_MSS_TEST | 0x0E)
#define HAL_CLK_MSS_TEST_CLK_XO_UIM2                                            (HAL_CLK_MSS_TEST | 0x0F)
#define HAL_CLK_MSS_TEST_CLK_Q6                                                 (HAL_CLK_MSS_TEST | 0x11)
#define HAL_CLK_MSS_TEST_MPLL2_DTEST                                            (HAL_CLK_MSS_TEST | 0x12)
#define HAL_CLK_MSS_TEST_MPLL1_DTEST                                            (HAL_CLK_MSS_TEST | 0x13)
#define HAL_CLK_MSS_TEST_MPLL0_DTEST                                            (HAL_CLK_MSS_TEST | 0x14)
#define HAL_CLK_MSS_TEST_CLK_Q6_PLL2_RCG2                                       (HAL_CLK_MSS_TEST | 0x18)
#define HAL_CLK_MSS_TEST_MPLL1_MAIN_MODEM_CX_TO_LS                              (HAL_CLK_MSS_TEST | 0x19)
#define HAL_CLK_MSS_TEST_MPLL1_EARLY_DIV3_MODEM_CX_TO_LS                        (HAL_CLK_MSS_TEST | 0x1A)
#define HAL_CLK_MSS_TEST_MPLL1_EARLY_DIV5                                       (HAL_CLK_MSS_TEST | 0x1B)
#define HAL_CLK_MSS_TEST_CLK_BUS_MODEM_BRIDGE_CX                                (HAL_CLK_MSS_TEST | 0x21)
#define HAL_CLK_MSS_TEST_CLK_BUS_MODEM_CX_TO_LS                                 (HAL_CLK_MSS_TEST | 0x22)
#define HAL_CLK_MSS_TEST_CLK_BUS_DIV_MODEM                                      (HAL_CLK_MSS_TEST | 0x22)
#define HAL_CLK_MSS_TEST_CLK_BUS_DIV_MODEM_PLL0                                 (HAL_CLK_MSS_TEST | 0x22)
#define HAL_CLK_MSS_TEST_CLK_BUS_NC_HM_BRIDGE_CX                                (HAL_CLK_MSS_TEST | 0x23)
#define HAL_CLK_MSS_TEST_CLK_BUS_NAV_CX_TO_LS                                   (HAL_CLK_MSS_TEST | 0x24)
#define HAL_CLK_MSS_TEST_CLK_BUS_MODEM_FROM_CMUX                                (HAL_CLK_MSS_TEST | 0x24)
#define HAL_CLK_MSS_TEST_MPLL1_EARLY_DIV3_NAV_CX_TO_LS                          (HAL_CLK_MSS_TEST | 0x25)
#define HAL_CLK_MSS_TEST_MPLL1_MAIN_NAV_CX_TO_LS                                (HAL_CLK_MSS_TEST | 0x26)
#define HAL_CLK_MSS_TEST_MPLL0_MAIN_MODEM_CX_TO_LS                              (HAL_CLK_MSS_TEST | 0x27)
#define HAL_CLK_MSS_TEST_CLK_VMIDMT_SNOC_AXI                                    (HAL_CLK_MSS_TEST | 0x29)
#define HAL_CLK_MSS_TEST_CLK_MODEM_SNOC_AXI                                     (HAL_CLK_MSS_TEST | 0x2A)
#define HAL_CLK_MSS_TEST_CLK_NAV_SNOC_AXI                                       (HAL_CLK_MSS_TEST | 0x2B)
#define HAL_CLK_MSS_TEST_CLK_MODEM_CFG_AHB                                      (HAL_CLK_MSS_TEST | 0x2C)
#define HAL_CLK_MSS_TEST_CLK_BUS_COMBODAC_COMP                                  (HAL_CLK_MSS_TEST | 0x2D)
#define HAL_CLK_MSS_TEST_CLK_BUS_CSR                                            (HAL_CLK_MSS_TEST | 0x2E)
#define HAL_CLK_MSS_TEST_CLK_BUS_BRIDGE                                         (HAL_CLK_MSS_TEST | 0x2F)
#define HAL_CLK_MSS_TEST_CLK_BUS_COXM                                           (HAL_CLK_MSS_TEST | 0x30)
#define HAL_CLK_MSS_TEST_CLK_BUS_SLAVE_TIMEOUT                                  (HAL_CLK_MSS_TEST | 0x31)
#define HAL_CLK_MSS_TEST_BUS_SLAVE_TIMEOUT_TIME_BASE                            (HAL_CLK_MSS_TEST | 0x32)
#define HAL_CLK_MSS_TEST_CLK_BUS_ATB                                            (HAL_CLK_MSS_TEST | 0x33)
#define HAL_CLK_MSS_TEST_CLK_BUS_UIM0                                           (HAL_CLK_MSS_TEST | 0x34)
#define HAL_CLK_MSS_TEST_CLK_BUS_UIM1                                           (HAL_CLK_MSS_TEST | 0x35)
#define HAL_CLK_MSS_TEST_CLK_BUS_Q6_VECTOR                                      (HAL_CLK_MSS_TEST | 0x38)
#define HAL_CLK_MSS_TEST_CLK_BUS_RBCPR                                          (HAL_CLK_MSS_TEST | 0x39)
#define HAL_CLK_MSS_TEST_CLK_BUS_RBCPR_REF                                      (HAL_CLK_MSS_TEST | 0x3A)
#define HAL_CLK_MSS_TEST_CLK_BUS_Q6_SCALAR                                      (HAL_CLK_MSS_TEST | 0x3B)
#define HAL_CLK_MSS_TEST_CLK_BUS_Q6                                             (HAL_CLK_MSS_TEST | 0x3B)
#define HAL_CLK_MSS_TEST_CLK_BUS_UIM2                                           (HAL_CLK_MSS_TEST | 0x3C)
#define HAL_CLK_MSS_TEST_CLK_BUS_DIV                                            (HAL_CLK_MSS_TEST | 0x3C)
#define HAL_CLK_MSS_TEST_CLK_BUS_DIV_PLL0                                       (HAL_CLK_MSS_TEST | 0x3C)
#define HAL_CLK_MSS_TEST_CLK_DAC0                                               (HAL_CLK_MSS_TEST | 0x3D)
#define HAL_CLK_MSS_TEST_MPLL1_OUT_EARLY_DIV5                                   (HAL_CLK_MSS_TEST | 0x3E)
#define HAL_CLK_MSS_TEST_CLK_DAC1                                               (HAL_CLK_MSS_TEST | 0x3F)


/*
 * WCSS debug clocks
 */
#define HAL_CLK_WCSS_TEST_WCSS_TOP_AHB_CLK                                      (HAL_CLK_WCSS_TEST | 0x11)
#define HAL_CLK_WCSS_TEST_WCSS_TOP_SLP_CLK                                      (HAL_CLK_WCSS_TEST | 0x12)
#define HAL_CLK_WCSS_TEST_WCSS_TOP_XO_CLK                                       (HAL_CLK_WCSS_TEST | 0x13)
#define HAL_CLK_WCSS_TEST_WCSS_DAC_SM_CLK                                       (HAL_CLK_WCSS_TEST | 0x13)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_CPU_CLK                                   (HAL_CLK_WCSS_TEST | 0x14)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_AHB_CLK                                   (HAL_CLK_WCSS_TEST | 0x15)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_TRC_CLK                                   (HAL_CLK_WCSS_TEST | 0x16)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_PHY_DBG_CLK                               (HAL_CLK_WCSS_TEST | 0x17)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_BT_32M_CLK                                (HAL_CLK_WCSS_TEST | 0x18)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_BT_FM_19M_CLK                             (HAL_CLK_WCSS_TEST | 0x19)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_SLP_CLK                                   (HAL_CLK_WCSS_TEST | 0x1A)
#define HAL_CLK_WCSS_TEST_WCSS_COMMON_XO_CLK                                    (HAL_CLK_WCSS_TEST | 0x1B)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_PHY_MAIN1_FAST_CLK                          (HAL_CLK_WCSS_TEST | 0x1C)
#define HAL_CLK_WCSS_TEST_WLAN_PHY_MAIN1_TX_CLK                                 (HAL_CLK_WCSS_TEST | 0x1D)
#define HAL_CLK_WCSS_TEST_WLAN_PHY_MAIN1_RX_CLK                                 (HAL_CLK_WCSS_TEST | 0x1E)
#define HAL_CLK_WCSS_TEST_WLAN_PHY_MAIN2_CLK                                    (HAL_CLK_WCSS_TEST | 0x1F)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_PHY_DBG_CLK                                 (HAL_CLK_WCSS_TEST | 0x20)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_PHY_DAC_CLK                                 (HAL_CLK_WCSS_TEST | 0x21)
#define HAL_CLK_WCSS_TEST_O_WCSS_ADC_240M_CLK                                   (HAL_CLK_WCSS_TEST | 0x22)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_ADC_CLK                                     (HAL_CLK_WCSS_TEST | 0x23)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_RFIF_CLK                                    (HAL_CLK_WCSS_TEST | 0x24)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_AHB_CLK                                     (HAL_CLK_WCSS_TEST | 0x25)
#define HAL_CLK_WCSS_TEST_O_WCSS_AXI_M_CLK                                      (HAL_CLK_WCSS_TEST | 0x26)
#define HAL_CLK_WCSS_TEST_O_WCSS_AHB_S0_CLK                                     (HAL_CLK_WCSS_TEST | 0x27)
#define HAL_CLK_WCSS_TEST_WCSS_WLAN_RFA_CAL_CLK                                 (HAL_CLK_WCSS_TEST | 0x29)
#define HAL_CLK_WCSS_TEST_O_WCSS_BUS_TIMEOUT_CLK                                (HAL_CLK_WCSS_TEST | 0x2A)


#endif // __HAL_CLK_TEST_H__
