/* HSU_APP_APIS TOOL VERSION: 4.37 */
/* GENERATED: THU FEB  4 2010 */
/*=============================================================================
                     H S U _ A P P _ A P I S _ C L N T . C

GENERAL DESCRIPTION
  This is an AUTO GENERATED file that provides RPC client functionality for the
  hsu_app_apis API.

  ---------------------------------------------------------------------------
  Copyright (c) 2010 Qualcomm Technologies Incorporated.
  All Rights Reserved. QUALCOMM Proprietary and Confidential.
  ---------------------------------------------------------------------------
=============================================================================*/

/*=============================================================================

                              Edit History

                             AUTO GENERATED                                  */
/* Generated by following versions of Htorpc modules:
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/htorpc.pl#9 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/Start.pm#6 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/Htoxdr.pm#1 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/XDR.pm#7 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/Output.pm#22 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/Parser.pm#4 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/Metacomments.pm#7 
Id: //source/qcom/qct/core/mproc/tools/main/latest/htorpc/lib/Htorpc/SymbolTable.pm#5   

hsu_app_apis Definition File(s):
Id: //source/qcom/qct/core/api/wiredconnectivity/rel/2h09/hsu_app_apis.h#2
=============================================================================*/
/*=============================================================================
$Header: //components/rel/tz.bf/2.5.c10/trustzone_images/core/api/rapi/wiredconnectivity/src/hsu_app_apis_clnt.c#1 $ 
=============================================================================*/


/* Include files */
#include "oncrpc.h"
#include "hsu_app_apis.h"
#include "hsu_app_apis_rpc.h"

/* Only one copy needed per API */
static opaque_auth Hsu_app_apisCred = { ONCRPC_AUTH_NONE, 0, 0 };
static opaque_auth Hsu_app_apisVerf = { ONCRPC_AUTH_NONE, 0, 0 };


/*=======================================================================
             API RPC Clients Implementation
=======================================================================*/

boolean hsu_app_apis_null(void)
{
  xdr_s_type       *clnt;
  rpc_reply_header  reply_header;
  boolean           xdr_status = TRUE;
  int               xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_APP_APIS_NULL_VERS, 0);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(HSU_APP_APISPROG, HSU_APP_APIS_NULL_VERS, 0);
    return FALSE;
  }

  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( ! xdr_call_msg_start( clnt,
                             HSU_APP_APISPROG, HSU_APP_APIS_NULL_VERS,
                             ONCRPC_HSU_APP_APIS_NULL_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf ) ) {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    return FALSE;
  }
  /* XDR OP NUMBER = 1 */

  if ( reply_header.stat != RPC_MSG_ACCEPTED )
  {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }
  else if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS )
  {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 2 */
    xdr_op_number = 2;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }
  else
  {
    return TRUE;
  }
} /* hsu_app_apis_null */

boolean hsu_app_apis_rpc_glue_code_info_remote
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
)
{
  xdr_s_type       *clnt;
  rpc_reply_header  reply_header;
  uint32            result = 0;
  boolean           xdr_status = TRUE;
  int               xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_APP_APIS_RPC_GLUE_CODE_INFO_REMOTE_VERS, 0);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(HSU_APP_APISPROG, HSU_APP_APIS_RPC_GLUE_CODE_INFO_REMOTE_VERS, 0);
    return FALSE;
  }
  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( ! xdr_call_msg_start( clnt,
                             HSU_APP_APISPROG, HSU_APP_APIS_RPC_GLUE_CODE_INFO_REMOTE_VERS,
                             ONCRPC_HSU_APP_APIS_RPC_GLUE_CODE_INFO_REMOTE_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf ) ) {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    // return here without calling XDR_MSG_DONE
    return FALSE;
  }
  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( reply_header.stat != RPC_MSG_ACCEPTED )
  {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }
  else if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS )
  {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 2 */
    xdr_op_number = 2;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }

  if ( xdr_status )
  {
    if ( toolvers != NULL )
    {
      *toolvers = result;
    }
    /* XDR OP NUMBER = 3 */
    xdr_op_number = 3;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }
  if ( xdr_status )
  {
    if ( features != NULL )
    {
      *features = result;
    }
    /* XDR OP NUMBER = 4 */
    xdr_op_number = 4;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }

  if ( xdr_status )
  {
    if ( proghash != NULL )
    {
      *proghash = result;
    }
    /* XDR OP NUMBER = 5 */
    xdr_op_number = 5;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }
  if ( xdr_status )
  {
    if ( cbproghash != NULL )
    {
      *cbproghash = result;
    }
    /* XDR OP NUMBER = 6 */
    xdr_op_number = 6;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 7 */
    xdr_op_number = 7;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }
  else
  {
    return TRUE;
  }
} /* hsu_app_apis_rpc_glue_code_info_remote */

boolean hsu_app_apis_rpc_glue_code_info_local
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
)
{
  if ( toolvers != NULL )
  {
    *toolvers = HSU_APP_APIS_TOOLVERS; /* 4.37 */
  }

  if ( features != NULL )
  {
    *features = HSU_APP_APIS_FEATURES; /* ONCRPC Server Cleanup Support */
                
  }

  if ( proghash != NULL )
  {
    *proghash = 0x00010001; /* 0x00010001 */
  }

  if ( cbproghash != NULL )
  {
    *cbproghash = 0x00010001; /* 0x00010001 */
  }

  return TRUE;
} /* hsu_app_apis_rpc_glue_code_info_local */

unsigned short hsu_api_get_product_id(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  unsigned short hsu_api_get_product_id_result;

  do {
    clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_API_GET_PRODUCT_ID_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(HSU_APP_APISPROG, HSU_API_GET_PRODUCT_ID_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               HSU_APP_APISPROG, HSU_API_GET_PRODUCT_ID_VERS,
                               ONCRPC_HSU_API_GET_PRODUCT_ID_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT16( clnt, &hsu_api_get_product_id_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return hsu_api_get_product_id_result;
} /* hsu_api_get_product_id */

void hsu_api_chg_force_resume(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean xdr_status = TRUE;
  int xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_API_CHG_FORCE_RESUME_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(HSU_APP_APISPROG, HSU_API_CHG_FORCE_RESUME_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    return;
  }

  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  xdr_status = xdr_call_msg_start( clnt,
                                   HSU_APP_APISPROG, HSU_API_CHG_FORCE_RESUME_VERS,
                                   ONCRPC_HSU_API_CHG_FORCE_RESUME_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf );

  if ( ! xdr_status )
  {
    XDR_OP_ERR(clnt, xdr_op_number);
    return;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    return;
  }
  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    xdr_op_number++;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return;
  }
} /* hsu_api_chg_force_resume */

void hsu_api_exit_lpm(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean xdr_status = TRUE;
  int xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_API_EXIT_LPM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(HSU_APP_APISPROG, HSU_API_EXIT_LPM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    return;
  }

  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  xdr_status = xdr_call_msg_start( clnt,
                                   HSU_APP_APISPROG, HSU_API_EXIT_LPM_VERS,
                                   ONCRPC_HSU_API_EXIT_LPM_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf );

  if ( ! xdr_status )
  {
    XDR_OP_ERR(clnt, xdr_op_number);
    return;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    return;
  }
  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    xdr_op_number++;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return;
  }
} /* hsu_api_exit_lpm */


/*=======================================================================
             API Standard Functions for version info
=======================================================================*/

uint32 *hsu_app_apis_api_versions(uint32 *len)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  uint32 i;
  boolean output_pointer_not_null;
  void *memset_temp;
  uint32 length_uint32;
  uint32 *hsu_app_apis_api_versions_result = NULL;

  do {
    clnt = rpc_clnt_lookup2(HSU_APP_APISPROG, HSU_APP_APIS_API_VERSIONS_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(HSU_APP_APISPROG, HSU_APP_APIS_API_VERSIONS_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               HSU_APP_APISPROG, HSU_APP_APIS_API_VERSIONS_VERS,
                               ONCRPC_HSU_APP_APIS_API_VERSIONS_PROC, &Hsu_app_apisCred, &Hsu_app_apisVerf );

    /* Send TRUE if len is not NULL and FALSE otherwise so that the server
     * can correctly allocate memory for the service to use
     */
    output_pointer_not_null = (len != NULL);

    (void) XDR_SEND_UINT8( clnt, &output_pointer_not_null );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT32( clnt, &length_uint32 );

  if ( length_uint32 > 0 )
  {
    memset_temp = oncrpcxdr_mem_alloc( clnt, length_uint32 * sizeof( *hsu_app_apis_api_versions_result ));
    memset(memset_temp, 0, length_uint32 * sizeof( *hsu_app_apis_api_versions_result ));
    hsu_app_apis_api_versions_result = memset_temp;


    /* Calling array of XDR routines */
    for ( i = 0; i < (length_uint32); i++ ) {
      /*lint -save -e545*/
      (void) XDR_RECV_UINT32( clnt, &(hsu_app_apis_api_versions_result[i]) );
      /*lint -restore */
    }
  }

  /*lint -save -e123*/
  XDR_RECV_POINTER_NO_ERRCHK( clnt, &len, XDR_RECV_UINT32 );
  /*lint -restore */


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return hsu_app_apis_api_versions_result;
} /* hsu_app_apis_api_versions */




/*=======================================================================
             API Callbacks RPC Server Implementation
=======================================================================*/


void hsu_app_apiscb_app_init( void ) {
} /* hsu_app_apiscb_app_init */

void hsu_app_apiscb_app_lock( boolean lock ){
} /* hsu_app_apiscb_app_enable */

