#ifndef DS_EPC_SM_DEFS_H
#define DS_EPC_SM_DEFS_H

typedef enum
{
  EPC_SSM_MIN_EV = 0,
  EPC_SSM_LTE_ATTACH_INIT_EV = EPC_SSM_MIN_EV,
  EPC_SSM_LTE_EV,
  EPC_SSM_EHRPD_EV,
  EPC_SSM_HRPD_EV,
  EPC_SSM_1X_EV,
  EPC_SSM_LTE_TUNNELING_ENABLE_EV,
  EPC_SSM_LTE_TUNNELING_DISABLE_EV,
  EPC_SSM_OTHER_EV,
  EPC_SSM_MAX_EV = EPC_SSM_OTHER_EV
}epc_ssm_input_event_type; 

typedef enum
{
  EPC_PDN_META_MIN_EV = 0,
  EPC_PDN_META_SSM_OOS_EV = EPC_PDN_META_MIN_EV,
  EPC_PDN_META_SSM_LTE_ATTACHING_EV,
  EPC_PDN_META_SSM_LTE_EV, 
  EPC_PDN_META_SSM_LTE_TUNNELING_EV,
  EPC_PDN_META_SSM_EHRPD_EV,
  EPC_PDN_META_SSM_HRPD_EV,
  EPC_PDN_META_SSM_1X_EV,
  EPC_PDN_META_SSM_GSM_EV,
  EPC_PDN_META_SSM_WCDMA_EV,
  EPC_PDN_META_SSM_TDSCDMA_EV,
  EPC_PDN_META_SSM_OTHER_EV,
  EPC_PDN_META_SSM_IWLAN_EV,
  EPC_PDN_META_SSM_WLAN_LOCAL_EV,
  EPC_PDN_META_SSM_MAX_EV = EPC_PDN_META_SSM_WLAN_LOCAL_EV,
  EPC_PDN_META_IF_EPC_UP_EV = EPC_PDN_META_SSM_MAX_EV + 1,
  EPC_PDN_META_IF_EPC_DOWN_EV,
  EPC_PDN_META_IF_EPC_GOING_DOWN_EV,
  EPC_PDN_META_IF_TEARDOWN_EV,
  EPC_PDN_META_MAX_EV = EPC_PDN_META_IF_TEARDOWN_EV
}epc_pdn_meta_sm_input_event_type; 

typedef enum
{
  EPC_PDN_HO_MIN_EV = 0,
  EPC_PDN_HO_SM_HO_EV = EPC_PDN_HO_MIN_EV,
  EPC_PDN_HO_SM_SWITCH_HO_EV,
  EPC_PDN_HO_SM_PREREG_EV,
  EPC_PDN_HO_SM_SRAT_RCVRD_EV,
  EPC_PDN_HO_SM_HO_RSP_SUCCESS_EV,
  EPC_PDN_HO_SM_HO_RSP_FAILURE_EV,
  EPC_PDN_HO_IF_TRAT_UP_EV,
  EPC_PDN_HO_IF_TRAT_DOWN_EV,
  EPC_PDN_HO_IF_SRAT_DOWN_EV,
  EPC_PDN_HO_TMR_SRAT_TMR_EXP_EV,
  EPC_PDN_HO_WAIT_TRAT_DOWN_EV,
  EPC_PDN_HO_IF_COMP_TRAT_DOWN_EV,
  EPC_PDN_HO_IF_COMP_TRAT_UP_EV,
  EPC_PDN_HO_MAX_EV = EPC_PDN_HO_IF_COMP_TRAT_UP_EV 
}epc_pdn_ho_sub_sm_input_event_type; 

#endif /*DS_EPC_SM_DEFS_H*/
