/* NV TOOL VERSION: 4.37 */
/* GENERATED: MON JUN  7 2010 */
/*=============================================================================
                               N V _ C L N T . C

GENERAL DESCRIPTION
  This is an AUTO GENERATED file that provides RPC client functionality for the
  nv API.

  ---------------------------------------------------------------------------
  Copyright (c) 2010 Qualcomm Technologies Incorporated.
  All Rights Reserved. QUALCOMM Proprietary and Confidential.
  ---------------------------------------------------------------------------
=============================================================================*/

/*=============================================================================

                              Edit History

                             AUTO GENERATED                                  */
/* Generated by following versions of Htorpc modules:
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/htorpc.pl#8 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Start.pm#3 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Htoxdr.pm#1 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/XDR.pm#3 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Output.pm#7 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Parser.pm#2 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/Metacomments.pm#5 
Id: //source/qcom/qct/core/mproc/tools/rel/04.07/htorpc/lib/Htorpc/SymbolTable.pm#3   

nv Definition File(s):
Id: //source/qcom/qct/core/services/nv/meta/main/latest/inc/nv.h#5
=============================================================================*/
/*=============================================================================
$Header: //components/rel/tz.bf/2.5.c10/trustzone_images/core/api/rapi/services/src/nv_clnt.c#1 $ 
=============================================================================*/


/* Include files */
#include "oncrpc.h"
#include "nv.h"
#include "nv_rpc.h"

/* Only one copy needed per API */
static opaque_auth NvCred = { ONCRPC_AUTH_NONE, 0, 0 };
static opaque_auth NvVerf = { ONCRPC_AUTH_NONE, 0, 0 };


/*=======================================================================
             API RPC Clients Implementation
=======================================================================*/

boolean nv_null(void)
{
  xdr_s_type       *clnt;
  rpc_reply_header  reply_header;
  boolean           xdr_status = TRUE;
  int               xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(NVPROG, NV_NULL_VERS, 0);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(NVPROG, NV_NULL_VERS, 0);
    return FALSE;
  }

  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( ! xdr_call_msg_start( clnt,
                             NVPROG, NV_NULL_VERS,
                             ONCRPC_NV_NULL_PROC, &NvCred, &NvVerf ) ) {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    return FALSE;
  }
  /* XDR OP NUMBER = 1 */

  if ( reply_header.stat != RPC_MSG_ACCEPTED )
  {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }
  else if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS )
  {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 2 */
    xdr_op_number = 2;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }
  else
  {
    return TRUE;
  }
} /* nv_null */

boolean nv_rpc_glue_code_info_remote
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
)
{
  xdr_s_type       *clnt;
  rpc_reply_header  reply_header;
  uint32            result = 0;
  boolean           xdr_status = TRUE;
  int               xdr_op_number = 0;

  clnt = rpc_clnt_lookup2(NVPROG, NV_RPC_GLUE_CODE_INFO_REMOTE_VERS, 0);

  if ( clnt == NULL ) {
    XDR_CLNT_LOOKUP2_ERR(NVPROG, NV_RPC_GLUE_CODE_INFO_REMOTE_VERS, 0);
    return FALSE;
  }
  oncrpcxdr_mem_free( clnt );

  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( ! xdr_call_msg_start( clnt,
                             NVPROG, NV_RPC_GLUE_CODE_INFO_REMOTE_VERS,
                             ONCRPC_NV_RPC_GLUE_CODE_INFO_REMOTE_PROC, &NvCred, &NvVerf ) ) {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }

  /* Send the RPC message and block waiting for a reply */
  if ( ! XDR_MSG_SEND( clnt, &reply_header ) )
  {
    XDR_MSG_SEND_ERR( clnt, &reply_header );
    // return here without calling XDR_MSG_DONE
    return FALSE;
  }
  /* XDR OP NUMBER = 1 */
  xdr_op_number = 1;
  if ( reply_header.stat != RPC_MSG_ACCEPTED )
  {
    XDR_CALL_REJECTED_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }
  else if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS )
  {
    XDR_ERR_ON_SERVER_ERR( clnt, &reply_header );
    xdr_status = FALSE;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 2 */
    xdr_op_number = 2;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }

  if ( xdr_status )
  {
    if ( toolvers != NULL )
    {
      *toolvers = result;
    }
    /* XDR OP NUMBER = 3 */
    xdr_op_number = 3;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }
  if ( xdr_status )
  {
    if ( features != NULL )
    {
      *features = result;
    }
    /* XDR OP NUMBER = 4 */
    xdr_op_number = 4;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }

  if ( xdr_status )
  {
    if ( proghash != NULL )
    {
      *proghash = result;
    }
    /* XDR OP NUMBER = 5 */
    xdr_op_number = 5;
    xdr_status = XDR_RECV_UINT32( clnt, &result );
  }
  if ( xdr_status )
  {
    if ( cbproghash != NULL )
    {
      *cbproghash = result;
    }
    /* XDR OP NUMBER = 6 */
    xdr_op_number = 6;
  }

  if ( xdr_status )
  {
    /* XDR OP NUMBER = 7 */
    xdr_op_number = 7;
  }

  if ( ! XDR_MSG_DONE( clnt ) || ! xdr_status )
  {
    XDR_OP_ERR( clnt, xdr_op_number );
    return FALSE;
  }
  else
  {
    return TRUE;
  }
} /* nv_rpc_glue_code_info_remote */

boolean nv_rpc_glue_code_info_local
(
  uint32 *toolvers,
  uint32 *features,
  uint32 *proghash,
  uint32 *cbproghash
)
{
  if ( toolvers != NULL )
  {
    *toolvers = NV_TOOLVERS; /* 4.37 */
  }

  if ( features != NULL )
  {
    *features = NV_FEATURES; /* ONCRPC Server Cleanup Support */
                
  }

  if ( proghash != NULL )
  {
    *proghash = 0x00090002; /* 0x00090002 */
  }

  if ( cbproghash != NULL )
  {
    *cbproghash = 0x00090002; /* 0x00090002 */
  }

  return TRUE;
} /* nv_rpc_glue_code_info_local */

nv_stat_enum_type nv_read_err_log(nv_err_log_type *nv_err_log_ptr)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_stat_enum_type nv_read_err_log_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_READ_ERR_LOG_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_READ_ERR_LOG_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_READ_ERR_LOG_VERS,
                               ONCRPC_NV_READ_ERR_LOG_PROC, &NvCred, &NvVerf );

    XDR_SEND_POINTER_NO_ERRCHK( clnt, &nv_err_log_ptr, xdr_nv_send_nv_err_log_type );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_ENUM( clnt, &nv_read_err_log_result );

  XDR_RECV_POINTER_NO_ERRCHK( clnt, &nv_err_log_ptr, xdr_nv_recv_nv_err_log_type );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_read_err_log_result;
} /* nv_read_err_log */

nv_stat_enum_type nv_write_err_log(nv_err_log_type *nv_err_log_ptr)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_stat_enum_type nv_write_err_log_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_WRITE_ERR_LOG_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_WRITE_ERR_LOG_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_WRITE_ERR_LOG_VERS,
                               ONCRPC_NV_WRITE_ERR_LOG_PROC, &NvCred, &NvVerf );

    XDR_SEND_POINTER_NO_ERRCHK( clnt, &nv_err_log_ptr, xdr_nv_send_nv_err_log_type );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_ENUM( clnt, &nv_write_err_log_result );

  XDR_RECV_POINTER_NO_ERRCHK( clnt, &nv_err_log_ptr, xdr_nv_recv_nv_err_log_type );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_write_err_log_result;
} /* nv_write_err_log */

word nv_max_size_of_roaming_list(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  word nv_max_size_of_roaming_list_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_MAX_SIZE_OF_ROAMING_LIST_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_MAX_SIZE_OF_ROAMING_LIST_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_MAX_SIZE_OF_ROAMING_LIST_VERS,
                               ONCRPC_NV_MAX_SIZE_OF_ROAMING_LIST_PROC, &NvCred, &NvVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT16( clnt, &nv_max_size_of_roaming_list_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_max_size_of_roaming_list_result;
} /* nv_max_size_of_roaming_list */

boolean nv_prl_is_valid(byte nam)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean nv_prl_is_valid_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_PRL_IS_VALID_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_PRL_IS_VALID_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_PRL_IS_VALID_VERS,
                               ONCRPC_NV_PRL_IS_VALID_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_UINT8( clnt, &nam );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_BOOLEAN( clnt, &nv_prl_is_valid_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_prl_is_valid_result;
} /* nv_prl_is_valid */

boolean nv_built(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean nv_built_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_BUILT_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_BUILT_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_BUILT_VERS,
                               ONCRPC_NV_BUILT_PROC, &NvCred, &NvVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_BOOLEAN( clnt, &nv_built_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_built_result;
} /* nv_built */

word nv_prl_version(byte nam)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  word nv_prl_version_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_PRL_VERSION_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_PRL_VERSION_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_PRL_VERSION_VERS,
                               ONCRPC_NV_PRL_VERSION_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_UINT8( clnt, &nam );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT16( clnt, &nv_prl_version_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_prl_version_result;
} /* nv_prl_version */

boolean nv_determine_esn_validity(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean nv_determine_esn_validity_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_DETERMINE_ESN_VALIDITY_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_DETERMINE_ESN_VALIDITY_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_DETERMINE_ESN_VALIDITY_VERS,
                               ONCRPC_NV_DETERMINE_ESN_VALIDITY_PROC, &NvCred, &NvVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_BOOLEAN( clnt, &nv_determine_esn_validity_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_determine_esn_validity_result;
} /* nv_determine_esn_validity */

nv_stat_enum_type nv_cmd_remote(nv_func_enum_type cmd,  nv_items_enum_type item,  nv_item_type *data_ptr)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_stat_enum_type nv_cmd_remote_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_CMD_REMOTE_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_CMD_REMOTE_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_CMD_REMOTE_VERS,
                               ONCRPC_NV_CMD_REMOTE_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_ENUM( clnt, &cmd );

    (void) XDR_SEND_ENUM( clnt, &item );

    /*lint -save -e123*/
    XDR_SEND_U_POINTER_NO_ERRCHK2( clnt, &data_ptr, &(item), xdr_nv_send_nv_item_type, XDR_SEND_ENUM );
    /*lint -restore */


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_ENUM( clnt, &nv_cmd_remote_result );

  /*lint -save -e123*/
  XDR_RECV_U_POINTER_NO_ERRCHK2( clnt, &data_ptr, &(item), xdr_nv_recv_nv_item_type, XDR_RECV_ENUM );
  /*lint -restore */


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_cmd_remote_result;
} /* nv_cmd_remote */

nv_stat_enum_type nv_cmd_ext_remote(
  nv_func_enum_type cmd,
  nv_items_enum_type item,
  nv_item_type *data_ptr,
  uint16 context
)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_stat_enum_type nv_cmd_ext_remote_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_CMD_EXT_REMOTE_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_CMD_EXT_REMOTE_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_CMD_EXT_REMOTE_VERS,
                               ONCRPC_NV_CMD_EXT_REMOTE_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_ENUM( clnt, &cmd );

    (void) XDR_SEND_ENUM( clnt, &item );

    /*lint -save -e123*/
    XDR_SEND_U_POINTER_NO_ERRCHK2( clnt, &data_ptr, &(item), xdr_nv_send_nv_item_type, XDR_SEND_ENUM );
    /*lint -restore */

    (void) XDR_SEND_UINT16( clnt, &context );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_ENUM( clnt, &nv_cmd_ext_remote_result );

  /*lint -save -e123*/
  XDR_RECV_U_POINTER_NO_ERRCHK2( clnt, &data_ptr, &(item), xdr_nv_recv_nv_item_type, XDR_RECV_ENUM );
  /*lint -restore */


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_cmd_ext_remote_result;
} /* nv_cmd_ext_remote */

nv_rtre_control_type nv_rtre_control(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_rtre_control_type nv_rtre_control_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_RTRE_CONTROL_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_RTRE_CONTROL_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_RTRE_CONTROL_VERS,
                               ONCRPC_NV_RTRE_CONTROL_PROC, &NvCred, &NvVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT16( clnt, &nv_rtre_control_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_rtre_control_result;
} /* nv_rtre_control */

boolean nv_rtre_use_ruim_for_nam(byte nam)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean nv_rtre_use_ruim_for_nam_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_RTRE_USE_RUIM_FOR_NAM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_RTRE_USE_RUIM_FOR_NAM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_RTRE_USE_RUIM_FOR_NAM_VERS,
                               ONCRPC_NV_RTRE_USE_RUIM_FOR_NAM_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_UINT8( clnt, &nam );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_BOOLEAN( clnt, &nv_rtre_use_ruim_for_nam_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_rtre_use_ruim_for_nam_result;
} /* nv_rtre_use_ruim_for_nam */

nv_rtre_polling_control_type nv_rtre_polling_control(void)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  nv_rtre_polling_control_type nv_rtre_polling_control_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_RTRE_POLLING_CONTROL_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_RTRE_POLLING_CONTROL_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_RTRE_POLLING_CONTROL_VERS,
                               ONCRPC_NV_RTRE_POLLING_CONTROL_PROC, &NvCred, &NvVerf );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT16( clnt, &nv_rtre_polling_control_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_rtre_polling_control_result;
} /* nv_rtre_polling_control */

boolean nv_rtre_polling_for_nam(byte nam)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  boolean nv_rtre_polling_for_nam_result;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_RTRE_POLLING_FOR_NAM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_RTRE_POLLING_FOR_NAM_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_RTRE_POLLING_FOR_NAM_VERS,
                               ONCRPC_NV_RTRE_POLLING_FOR_NAM_PROC, &NvCred, &NvVerf );

    (void) XDR_SEND_UINT8( clnt, &nam );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_BOOLEAN( clnt, &nv_rtre_polling_for_nam_result );


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_rtre_polling_for_nam_result;
} /* nv_rtre_polling_for_nam */


/*=======================================================================
             API Standard Functions for version info
=======================================================================*/

uint32 *nv_api_versions(uint32 *len)
{
  xdr_s_type *clnt;
  rpc_reply_header reply_header;

  uint32 i;
  boolean output_pointer_not_null;
  void *memset_temp;
  uint32 length_uint32;
  uint32 *nv_api_versions_result = NULL;

  do {
    clnt = rpc_clnt_lookup2(NVPROG, NV_API_VERSIONS_VERS, RPC_CLNT_LOOKUP_TIMEOUT);

    if ( clnt == NULL ) {
      XDR_CLNT_LOOKUP2_ERR_FATAL(NVPROG, NV_API_VERSIONS_VERS, RPC_CLNT_LOOKUP_TIMEOUT);
    }

    oncrpcxdr_mem_free( clnt );

    XDR_ERRCHK( clnt, ON );

    (void) xdr_call_msg_start( clnt,
                               NVPROG, NV_API_VERSIONS_VERS,
                               ONCRPC_NV_API_VERSIONS_PROC, &NvCred, &NvVerf );

    /* Send TRUE if len is not NULL and FALSE otherwise so that the server
     * can correctly allocate memory for the service to use
     */
    output_pointer_not_null = (len != NULL);

    (void) XDR_SEND_UINT8( clnt, &output_pointer_not_null );


    /* Send the RPC message and block waiting for a reply */
  } while ( ! XDR_MSG_SEND( clnt, &reply_header ) );

  if ( reply_header.stat != RPC_MSG_ACCEPTED ) {
    XDR_CALL_REJECTED_ERR_FATAL( clnt, &reply_header );
  }

  if ( reply_header.u.ar.stat != RPC_ACCEPT_SUCCESS ) {
    XDR_ERR_ON_SERVER_ERR_FATAL( clnt, &reply_header );
  }

  (void) XDR_RECV_UINT32( clnt, &length_uint32 );

  if ( length_uint32 > 0 )
  {
    memset_temp = oncrpcxdr_mem_alloc( clnt, length_uint32 * sizeof( *nv_api_versions_result ));
    memset(memset_temp, 0, length_uint32 * sizeof( *nv_api_versions_result ));
    nv_api_versions_result = memset_temp;


    /* Calling array of XDR routines */
    for ( i = 0; i < (length_uint32); i++ ) {
      /*lint -save -e545*/
      (void) XDR_RECV_UINT32( clnt, &(nv_api_versions_result[i]) );
      /*lint -restore */
    }
  }

  /*lint -save -e123*/
  XDR_RECV_POINTER_NO_ERRCHK( clnt, &len, XDR_RECV_UINT32 );
  /*lint -restore */


  if ( ! XDR_MSG_DONE( clnt ) )
  {
    XDR_OP_ERR_FATAL( clnt, 0 );
  }

  XDR_ERRCHK( clnt, OFF );

  return nv_api_versions_result;
} /* nv_api_versions */




/*=======================================================================
             API Callbacks RPC Server Implementation
=======================================================================*/


void nvcb_app_init( void ) {
} /* nvcb_app_init */

void nvcb_app_lock( boolean lock ){
} /* nvcb_app_enable */

