/*===========================================================================
   Copyright (c) 2012-2013 by Qualcomm Technologies, Incorporated.  All Rights Reserved.
===========================================================================*/

/*===========================================================================

                            EDIT HISTORY FOR FILE

  $Header: //components/rel/tz.bf/2.5.c10/trustzone_images/core/securemsm/trustzone/qsee/arch/msm8909/src/tzbsp_xpu_config.c#1 $
  $DateTime: 2016/06/17 14:31:11 $
  $Author: pwbldsvc $


when       who     what, where, why
--------   ---     ------------------------------------------------------------
07/06/12   sg      TLMM_BCR should be under TZ control only
07/05/12   sg      Add Modem Shared EFS partition
06/01/12   sg      Initial version.
=============================================================================*/

/* This pragma allows anonymous unions that are used by XPU HAL API */
#pragma anon_unions

#include <comdef.h>
#include <HALxpu2.h>

#include "tzbsp.h"
#include "tzbsp_mem.h"
#include "tzbsp_target.h"
#include "tzbsp_config.h"
#include "tzbsp_xpu.h"
#include "tzbsp_xpu_def.h"
#include "tzbsp_xpu_config.h"
#include "tzbsp_vmid_config.h"
#include "tzbsp_memory_map.h"
#include "tzbsp_hwio.h"

#define ARRAY_SIZE(xx) (sizeof(xx) / sizeof((xx)[0]))

static const tzbsp_mpu_rg_t g_rg_ebi[] = {
  /*RFSA buffer memory space. */
  {TZBSP_EBI1_RG_RFSA, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT | TZBSP_VMID_WLAN_BIT, 
      TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT | TZBSP_VMID_WLAN_BIT, 
      TZBSP_EBI1_RFSA_BASE, TZBSP_EBI1_RFSA_END},
  {TZBSP_EBI1_RG_TZ_NON_RELOC, TZBSP_XPU_SEC |TZBSP_XPU_ENABLE, 
      0, 0,
   TZBSP_EBI1_TZ_BASE, TZBSP_DIAG_BASE},
   /* By default all VMIDs can read/write the shared EBI1 memory space. */
  {TZBSP_EBI1_RG_SHARED, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
     (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
      ~(TZBSP_VMID_CP_BIT | TZBSP_VMID_VIDEO_BIT),
      TZBSP_EBI1_SHARED_MEM_BASE, TZBSP_EBI1_SHARED_MEM_END},
  {TZBSP_EBI1_RG_TZ_DIAG, (TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC),
    (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), /* Read access */
    0, /* Write access. No VMID. Controlled by xPROTNS  */
    TZBSP_DIAG_BASE, TZBSP_EBI1_SECCHANNEL_MSS_BASE}, /* Area */  
  /* Secure Channels */	
  {TZBSP_EBI1_RG_SECCHANNEL_MSS, TZBSP_XPU_ENABLE,
    (TZBSP_VMID_TZ_BIT | TZBSP_VMID_MSS_BIT ),
    TZBSP_VMID_TZ_BIT,
    TZBSP_EBI1_SECCHANNEL_MSS_BASE, TZBSP_EBI1_SECCHANNEL_MSS_END},
  {TZBSP_EBI1_RG_SECCHANNEL_LPASS, TZBSP_XPU_ENABLE,
    (TZBSP_VMID_TZ_BIT | TZBSP_VMID_LPASS_BIT | TZBSP_VMID_MSS_BIT),
	(TZBSP_VMID_TZ_BIT | TZBSP_VMID_LPASS_BIT | TZBSP_VMID_MSS_BIT),
    TZBSP_EBI1_SECCHANNEL_LPASS_BASE, TZBSP_EBI1_SECCHANNEL_LPASS_END},

/*  {TZBSP_EBI1_RG_SECCHANNEL_WCNSS, TZBSP_XPU_ENABLE,
    (TZBSP_VMID_TZ_BIT | TZBSP_VMID_WLAN_BIT ),
    TZBSP_VMID_TZ_BIT,
    TZBSP_EBI1_SECCHANNEL_WCNSS_BASE, TZBSP_EBI1_SECCHANNEL_WCNSS_END},
    */
  /* First MSA partition is the Modem Shared EFS partition */
  {TZBSP_EBI1_RG_MSA1, TZBSP_XPU_MODEM_PROT, 0, 0, 0, 0},
  /* MSA partition 2. Disabled on bootup. Configured by Modem */
  {TZBSP_EBI1_RG_MSA2, TZBSP_XPU_MODEM_PROT, 0, 0, 0, 0},
  /* MSA partition 3. Disabled on bootup. Configured by Modem */
  {TZBSP_EBI1_RG_MSA3, TZBSP_XPU_MODEM_PROT, 0, 0, 0, 0},
  /* MSA partition 4. Disabled on bootup. Configured by Modem */
  {TZBSP_EBI1_RG_MSA4, TZBSP_XPU_MODEM_PROT, 0, 0, 0, 0},
};

/**
 * BLSP1 APU resource groups (Multi VMID, full access/no access).
 * Pipe resources configured during BAM init
 */
static const tzbsp_rpu_rg_t g_rg_blsp1[] = {
  {TZBSP_BAM_BLSP1_RG_CONTROL, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_DEBUG, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_TRUST, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_BAM_BLSP1_RG_EE0, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE,
      TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  {TZBSP_BAM_BLSP1_RG_EE1, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE,
      TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  {TZBSP_BAM_BLSP1_RG_EE2, TZBSP_XPU_MODEM_PROT | TZBSP_XPU_ENABLE,
      0, 0},
  {TZBSP_BAM_BLSP1_RG_EE3, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  {TZBSP_BAM_BLSP1_RG_UART0, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_UART1, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP0, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP1, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP2, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP3, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP4, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_BAM_BLSP1_RG_QUP5, TZBSP_RWE | TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE,
    (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
    (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
};

/*
 * Boot ROM MPU RGs. Read/write access. Single VMID
 */
static const tzbsp_mpu_rg_t g_rg_bootrom[] = {
  /* Modem boot rom readable by Modem and not writeable by any */
  {TZBSP_BOOTROM_RG_MSS,  TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    0, 0, TZBSP_BOOT_ROM_MSS_BASE, TZBSP_BOOT_ROM_MSS_END},
  {TZBSP_BOOTROM_RG_APPS, TZBSP_XPU_ENABLE | TZBSP_XPU_SEC,
    0, 0, TZBSP_BOOT_ROM_APPS_XPU_BASE, TZBSP_BOOT_ROM_APPS_XPU_END},
  /* unused partition */
  {TZBSP_BOOTROM_RG_UNUSED, TZBSP_XPU_ENABLE | TZBSP_XPU_SEC,
    0, 0, 0xFFFFFFFF, 0xFFFFFFFF},
};


/**
 * GCC resource groups (Multi VMID, full access/no access). Super users have
 * implicit access to single VMID resources. RPM is super user for this xPU
 */
static const tzbsp_rpu_rg_t g_rg_gcc[] = {
        //TODO marking RG0 as MSA owned
  {TZBSP_GCC_RG_SPARE_GPLL_ENA_VOTE,   TZBSP_XPU_MODEM_PROT, 0, 0},
  {TZBSP_GCC_RG_BLSP1, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP1, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP2_I2C_APPS_CMD, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP3_I2C_APPS_CMD, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP4_I2C_APPS_CMD, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP5_I2C_APPS_CMD, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_BLSP1_QUP6_I2C_APPS_CMD, TZBSP_RWE | TZBSP_XPU_NON_SEC,  
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_GP1, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_GP2, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_GP3, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK)},
  {TZBSP_GCC_RG_IMEM, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_VENUS_RESTART,  TZBSP_XPU_SEC| TZBSP_ROE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_WCSS_RESTART, TZBSP_XPU_SEC | TZBSP_ROE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_SMMU, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_PRNG, TZBSP_ROE | TZBSP_XPU_SEC | TZBSP_MSA_ROE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_RESET_DEBUG, TZBSP_ROE | TZBSP_XPU_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_FLUSH_ETR_DEBUG_TIMER, TZBSP_ROE | TZBSP_XPU_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_GCC_RG_CRYPTO, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_AP_BIT},
  {TZBSP_GCC_RG_NOC_CONF_XPU_AHB,   TZBSP_XPU_SEC, 0, 0},
  {TZBSP_GCC_RG_SEC_CTR, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT},
  {TZBSP_GCC_RG_MSS_Q6_GPLL_ENA_VOTE, TZBSP_XPU_MODEM_PROT, 0, 0},
  //{TZBSP_GCC_RG_MSS_Q6_GPLL_ENA_VOTE, TZBSP_XPU_NON_SEC| TZBSP_RWE,
  //      TZBSP_VMID_MSS_BIT |  TZBSP_VMID_AP_BIT,  TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT},
  {TZBSP_GCC_RG_ULTAUDIO_PCNOC_MPORT, TZBSP_RWE | TZBSP_XPU_NON_SEC, 
      TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT, TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT},
  
  {TZBSP_GCC_RG_BLSP1_DEHR, TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT},
};

/**
 * TCSR_REG APU resource groups (Multi VMID, read access/write access).
 * TZ has implicit access to all partitions
 */
static const tzbsp_rpu_rg_t g_rg_tcsr_reg[] = {
  /* Read access given to modem for MSAEN Status register */
  {TZBSP_TCSR_REG_RG_QRIB_1, TZBSP_XPU_SEC | TZBSP_MSA_ROE | TZBSP_ROE, TZBSP_VMID_MSS_BIT, 0},
  {TZBSP_TCSR_REG_RG_QRIB_2, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_TCSR_REG_RG_ACC_CLT_CFG_INTR, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_TCSR_REG_RG_MSA_INTR, TZBSP_XPU_MODEM_PROT, 0, 0},
  {TZBSP_TCSR_REG_RG_CLK_GATING, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM_BIT, TZBSP_VMID_RPM_BIT},
  {TZBSP_TCSR_REG_RG_TIMEOUT_INTR, TZBSP_XPU_SEC | TZBSP_ROE | TZBSP_MSA_ROE, TZBSP_VMID_MSS_BIT, 0},
  //{TZBSP_TCSR_REG_RG_TZ_WONCE, TZBSP_XPU_SEC | TZBSP_ROE, 
  {TZBSP_TCSR_REG_RG_TZ_WONCE, TZBSP_XPU_SEC | TZBSP_ROE | TZBSP_MSA_ROE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_TCSR_REG_RG_MMSS_RPM_INTR, TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_RPM_BIT | TZBSP_VMID_AP_BIT},
  {TZBSP_TCSR_REG_RG_TBU_BYPASS, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_TCSR_REG_RG_DEBUG_BYPASS, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_TCSR_REG_RG_QPDI_CFG, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  {TZBSP_TCSR_REG_RG_ACC,  TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_AP_BIT | TZBSP_VMID_RPM_BIT},
  {TZBSP_TCSR_REG_RG_APC1_ACC, TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_AP_BIT},
  {TZBSP_TCSR_REG_RG_APC2_ACC, TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_AP_BIT},
  {TZBSP_TCSR_REG_RG_UNUSED_14, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_TCSR_REG_RG_UNUSED_15, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
};

/**
 * Crypto 0 APU resource groups (Multi VMID, full access/no access).
 * Pipe resources configured during BAM init
 */
static const tzbsp_rpu_rg_t g_rg_crypto0[] = {
  {TZBSP_CRYPTO0_RG_BAM_EE0, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_CRYPTO0_RG_BAM_EE1, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT},
  {TZBSP_CRYPTO0_RG_BAM_EE2, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_CRYPTO0_RG_BAM_EE3, TZBSP_XPU_SEC, 0, 0 },
  {TZBSP_CRYPTO0_RG_BAM_TRUST, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_CRYPTO0_RG_BAM_DEBUG, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT},
  {TZBSP_CRYPTO0_RG_CFG, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT },
  {TZBSP_CRYPTO0_RG_QC_KEY, (TZBSP_XPU_SEC | TZBSP_RWE), TZBSP_VMID_TZ_BIT, TZBSP_VMID_TZ_BIT},
  {TZBSP_CRYPTO0_RG_OEM_KEY, TZBSP_XPU_NON_SEC, TZBSP_VMID_TZ_BIT, TZBSP_VMID_TZ_BIT},
  {TZBSP_CRYPTO0_RG_LEGACY_SW_KEY, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_TZ_BIT},
  {TZBSP_CRYPTO0_RG_PIPE_SW_KEY, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_CRYPTO0_RG_DEBUG, TZBSP_XPU_SEC, 0, 0},
};

/*
 * DEHR APU RGs. Read/write access. Single VMID. For use cases where fuse
 * FEATURE_CONFIG7[MSA_ENA]=1.
 */
static const tzbsp_rpu_rg_t g_rg_dehr[] = {
  /* Lock/Enable bits written only by Modem. Initial DEHR config done by TZ, and
   * further changes blocked by lock bit. */
  {TZBSP_DEHR_APU_RG_SEC,   TZBSP_XPU_MODEM_PROT | TZBSP_ROGE, 0, 0},
  /* Readable by all, since both MSS and RPM need access */
  {TZBSP_DEHR_APU_RG_CFG, TZBSP_ROGE | TZBSP_XPU_SEC | TZBSP_MSA_ROE, 0, 0},
};
/*
 * MPM2 APU RGs. Read/write access. Single VMID
 */
static const tzbsp_rpu_rg_t g_rg_mpm2_apu[] = {
  {TZBSP_MPM2_APU_RG_REGS, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM, TZBSP_VMID_RPM},
  {TZBSP_MPM2_APU_RG_GLB_CTL_CTR, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM, TZBSP_VMID_RPM},
  {TZBSP_MPM2_APU_RG_GLB_RD_CTR, TZBSP_ROGE | TZBSP_XPU_NON_SEC, 0, 0},
  {TZBSP_MPM2_APU_RG_SLEEP_CTR, TZBSP_ROGE | TZBSP_XPU_NON_SEC, 0, 0},
  {TZBSP_MPM2_APU_RG_QTMR_AC, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM, TZBSP_VMID_RPM},
  {TZBSP_MPM2_APU_RG_QTMR_V1, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM, TZBSP_VMID_RPM},
  {TZBSP_MPM2_APU_RG_TSYNC, TZBSP_XPU_MODEM_PROT, 0, 0},
  {TZBSP_MPM2_APU_RG_TEMP_SENSOR, TZBSP_XPU_NON_SEC | TZBSP_ROGE | TZBSP_RWE, TZBSP_VMID_RPM, TZBSP_VMID_RPM},
  {TZBSP_MPM2_APU_RG_TEMP_SENSOR_TM, TZBSP_ROGE | TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_APCPU, TZBSP_VMID_APCPU},
  {TZBSP_MPM2_APU_RG_WDOG,  TZBSP_XPU_SEC, 0, 0},
  {TZBSP_MPM2_APU_RG_PSHOLD, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_APCPU, TZBSP_VMID_APCPU},
};

/**
 * MSS APU resource groups (Multi VMID, full access/no access).
 */
static const tzbsp_rpu_rg_t g_rg_mss_apu[] = {
  {TZBSP_MSS_APU_RG_RMB, TZBSP_RWE | TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_MSS_APU_RG_A2BAM, TZBSP_RWE | TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_MSS_APU_RG_Q6_RST, TZBSP_RWE | TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_MSS_APU_RG_MSS_CFG, TZBSP_XPU_MODEM_PROT, 0, 0},
  {TZBSP_MSS_APU_RG_ACC_SELECT, TZBSP_XPU_MODEM_PROT, 0, 0},
};


/**
 * OCIMEM MPU resource groups (Multi VMID, Read/Write access).
 */
static const tzbsp_mpu_rg_t g_rg_sys_imem[] = {

  {TZBSP_SYS_IMEM_RG_APP, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_NOACCESS_BIT | TZBSP_VMID_AP_BIT, TZBSP_VMID_NOACCESS_BIT | TZBSP_VMID_AP_BIT, 
      TZBSP_IMEM_USB_TRACE_PIPE_BASE, TZBSP_IMEM_USB_TRACE_PIPE_END}, 
  {TZBSP_SYS_IMEM_RG_TZ, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 
      0, 0,
      TZBSP_IMEM_TZ_BASE, TZBSP_IMEM_TZ_END}, 
  {TZBSP_SYS_IMEM_RG_SHARED, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
      TZBSP_IMEM_SHARED_BASE, TZBSP_IMEM_SHARED_END}, 
};
/*
 *  RPM APU RGs. Read/write access. Multi VMID
 */
const tzbsp_rpu_rg_t g_rg_rpm_apu[] = {
  {TZBSP_RPM_APU_RG0, TZBSP_XPU_NON_SEC | TZBSP_RWE, TZBSP_VMID_RPM_BIT, TZBSP_VMID_RPM_BIT},
  {TZBSP_RPM_APU_RG1, TZBSP_XPU_NON_SEC | TZBSP_RWE,  TZBSP_VMID_RPM_BIT, 0},
};


/*
 * Security Control RGs. Read/write access. Multi VMID
 */
const tzbsp_rpu_rg_t g_rg_sec_ctrl[] = {
  //Added MSA read only permission for RG0.
  {TZBSP_SEC_CTRL_RG0, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE |TZBSP_MSA_ROE | TZBSP_ROE, (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
  {TZBSP_SEC_CTRL_RG1, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG2, TZBSP_XPU_MODEM_PROT | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG3, TZBSP_XPU_MODEM_PROT | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG4, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE | TZBSP_MSA_RWE, (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT},
  {TZBSP_SEC_CTRL_RG5, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG6, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG7, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG8, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
  {TZBSP_SEC_CTRL_RG9, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0},
};

/*
 * SMMU DIME MPU RGs. Read/write access. Single VMID
 */
static const tzbsp_mpu_rg_t g_rg_smmu_dime[] = {
  {TZBSP_SMMU_DIME_RG_SECURE,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0, TZBSP_SMMU_DIME_START, TZBSP_SMMU_DIME_END}
};

/*
 * SMMU GPS MPU RGs. Read/write access. Single VMID
 */
static const tzbsp_mpu_rg_t g_rg_smmu_gps[] = {
  {TZBSP_SMMU_GPS_RG_SECURE,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0, TZBSP_SMMU_GPS_START, TZBSP_SMMU_GPS_END}
};

/*
 * SMMU QDSP MPU RGs. Read/write access. Single VMID
 */
static const tzbsp_mpu_rg_t g_rg_smmu_qdsp[] = {
  {TZBSP_SMMU_QDSP_RG0,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG0_START, TZBSP_SMMU_QDSP_RG0_END},
  {TZBSP_SMMU_QDSP_RG1,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG1_START, TZBSP_SMMU_QDSP_RG1_END},
  {TZBSP_SMMU_QDSP_RG2,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG2_START, TZBSP_SMMU_QDSP_RG2_END},
  {TZBSP_SMMU_QDSP_RG3,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG3_START, TZBSP_SMMU_QDSP_RG3_END},
  {TZBSP_SMMU_QDSP_RG4,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG4_START, TZBSP_SMMU_QDSP_RG4_END},
  {TZBSP_SMMU_QDSP_RG5,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG5_START, TZBSP_SMMU_QDSP_RG5_END},
  {TZBSP_SMMU_QDSP_RG6,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG6_START, TZBSP_SMMU_QDSP_RG6_END},
  {TZBSP_SMMU_QDSP_RG7,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG7_START, TZBSP_SMMU_QDSP_RG7_END},
  {TZBSP_SMMU_QDSP_RG8,  TZBSP_XPU_SEC | TZBSP_XPU_ENABLE| TZBSP_NON_SEC_RWE | TZBSP_RWE, 0, TZBSP_VMID_MSS, TZBSP_SMMU_QDSP_RG8_START, TZBSP_SMMU_QDSP_RG8_END},
};

/*
 * SMMU MPU RGs. Read/write access. Multi VMID
 */
static const tzbsp_mpu_rg_t g_rg_smmu[] = {
/* removed the read permission from all except MSS_RG in TCU MPU due to hadware bug CR703012 */

  {TZBSP_SMMU_RG_GLOB0, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE ,  0, 0, TZBSP_SMMU_GLOB0_START, TZBSP_SMMU_GLOB0_END},
  {TZBSP_SMMU_RG_STAGE2, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE ,  0, 0, TZBSP_SMMU_STAGE2_START, TZBSP_SMMU_STAGE2_END},
  {TZBSP_SMMU_RG_STAGE1, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE ,  0, 0, TZBSP_SMMU_STAGE1_START, TZBSP_SMMU_STAGE1_END},
  {TZBSP_SMMU_RG_SECURE, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE ,  0, 0, TZBSP_SMMU_SECURE_START, TZBSP_SMMU_SECURE_END},
  {TZBSP_SMMU_RG_HYP, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE ,  0, 0, TZBSP_SMMU_HYP_START, TZBSP_SMMU_HYP_END},
  {TZBSP_SMMU_RG_MSS,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),TZBSP_VMID_MSS_BIT, 
      TZBSP_SMMU_MSS_START, TZBSP_SMMU_MSS_END},
  {TZBSP_SMMU_RG_MMSS, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE , 0, 0, TZBSP_SMMU_MMSS_START, TZBSP_SMMU_MMSS_END},
  {TZBSP_SMMU_RG_GLOB1, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE , 0, 0, TZBSP_SMMU_GLOB1_START, TZBSP_SMMU_GLOB1_END},
  {TZBSP_SMMU_RG_GFX, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE , 0, 0, TZBSP_SMMU_GFX_START, TZBSP_SMMU_GFX_END},
};
 


/*
 * TLMM MPU RGs. Read/write access. Mulit VMID
 */
static const tzbsp_mpu_rg_t g_rg_tlmm[] = {
  {TZBSP_TLMM_RG_GPIO,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_RPM_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT,
      TZBSP_TLMM_GPIO_START, TZBSP_TLMM_GPIO_END},
  {TZBSP_TLMM_RG_DIR_CONN1,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_RPM_BIT | TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT,
      TZBSP_TLMM_DIR_CONN1_START, TZBSP_TLMM_DIR_CONN1_END},
  {TZBSP_TLMM_RG_DIR_CONN2,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_RPM_BIT , TZBSP_VMID_RPM_BIT,
      TZBSP_TLMM_DIR_CONN2_START, TZBSP_TLMM_DIR_CONN2_END},
  {TZBSP_TLMM_RG_DIR_CONN3,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_MSS_BIT , TZBSP_VMID_MSS_BIT,
      TZBSP_TLMM_DIR_CONN3_START, TZBSP_TLMM_DIR_CONN3_END},
  {TZBSP_TLMM_RG_DIR_CONN4,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
      TZBSP_VMID_RPM_BIT | TZBSP_VMID_WLAN_BIT, TZBSP_VMID_WLAN_BIT,
      TZBSP_TLMM_DIR_CONN4_START, TZBSP_TLMM_DIR_CONN4_END},
  {TZBSP_TLMM_RG_RFEE_CTRL,  TZBSP_XPU_NON_SEC |  TZBSP_XPU_ENABLE |TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
      TZBSP_TLMM_RFEE_START, TZBSP_TLMM_RFEE_END},
  {TZBSP_TLMM_RG_PMIC_HDRV_PULL,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_RPM_BIT,
      TZBSP_TLMM_PMIC_HDRV_PULL_START, TZBSP_TLMM_PMIC_HDRV_PULL_END},
  {TZBSP_TLMM_RG_MISC_RPM,  TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_RPM_BIT,
      TZBSP_TLMM_MISC_RPM_START, TZBSP_TLMM_MISC_RPM_END},
};


/*
 * Venus APU. Read/write access. Multi VMID. Venus access to these bypass the
 * xPU.
 */
static const tzbsp_rpu_rg_t g_rg_venus[] = {
  /* Vocdec SWI registers. read access to HLOS */
  {TZBSP_VENUS_RG_VOCODEC, TZBSP_XPU_NON_SEC,
   0, 0},
  /* Security registers */
  {TZBSP_VENUS_RG_SEC_AND_ARM9_RST, TZBSP_XPU_ENABLE | TZBSP_XPU_SEC, 0, 0},
  {TZBSP_VENUS_RG_SEC_VBIF, TZBSP_XPU_ENABLE | TZBSP_XPU_SEC, 0, 0},
};


/*
 * WLAN/Pronto Cfg APU RGs. Read/write access. Multi VMID
 */
static const tzbsp_rpu_rg_t g_rg_wlan[] = {
  {TZBSP_WLAN_RG_GEN,  TZBSP_XPU_NON_SEC | TZBSP_RWE,
     TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT,
     TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_WLAN_RG_BOOT, TZBSP_XPU_NON_SEC | TZBSP_RWE,
   TZBSP_VMID_WLAN_BIT | TZBSP_VMID_AP_BIT, TZBSP_VMID_WLAN_BIT},
};
/*
 * PCNOC Cfg RGs. Read/write access. Multi VMID
 */
static const tzbsp_mpu_rg_t g_rg_pcnoc_cfg[] = {

  {TZBSP_PCNOC_CFG_RG_ERR, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0,
   TZBSP_PCNOC_CFG_RG_ERR_BASE, TZBSP_PCNOC_CFG_RG_ERR_END},
  {TZBSP_PCNOC_PROF, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0,
   TZBSP_PCNOC_PROF_RG_BASE, TZBSP_PCNOC_PROF_RG_END},
  {TZBSP_PCNOC_RG2, TZBSP_XPU_SEC, 0, 0, 0, 0},
  {TZBSP_PCNOC_RG3, TZBSP_XPU_SEC, 0, 0, 0, 0},
};

/*
 * Peripheral PRNG APU resource groups (Multi VMID, Read/Write access).
 * Super users have implicit access to single VMID resources.
 */
static const tzbsp_rpu_rg_t g_rg_periph_prng[] = {
  {TZBSP_PERIPH_SS_RG_PRNG, TZBSP_XPU_SEC | TZBSP_ROE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0},
};

/*
 * RPM Cfg RGs. Read/write access. Multi VMID
 */
static const tzbsp_mpu_rg_t g_rg_rpm_cfg[] = {

  {TZBSP_RPM_CFG_RG_CSR, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE, 
   TZBSP_VMID_RPM_BIT, TZBSP_VMID_RPM_BIT,
   TZBSP_RPM_CFG_RG_CSR_BASE, TZBSP_RPM_CFG_RG_CSR_END},
  {TZBSP_RPM_CFG_RG_DATA_RAM, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
   TZBSP_VMID_RPM_BIT | TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_RPM_BIT,
   TZBSP_RPM_CFG_RG_DATA_RAM_BASE, TZBSP_RPM_CFG_RG_DATA_RAM_END},
};

/*
 * SNOC Cfg RGs. Read/write access. Multi VMID
 */
static const tzbsp_mpu_rg_t g_rg_snoc_cfg[] = {

  {TZBSP_SNOC_CFG_RG_ERR, TZBSP_XPU_SEC | TZBSP_XPU_ENABLE, 0, 0,
   TZBSP_SNOC_CFG_RG_ERR_BASE, TZBSP_SNOC_CFG_RG_ERR_END},
  {TZBSP_SNOC_CFG_RG_QOS_MSS, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
   TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT,
   TZBSP_SNOC_CFG_RG_QOS_MSS_BASE, TZBSP_SNOC_CFG_RG_QOS_MSS_END},
  {TZBSP_SNOC_CFG_RG_MSA_BLOCK, TZBSP_XPU_NON_SEC | TZBSP_XPU_ENABLE | TZBSP_RWE,
   TZBSP_VMID_AP_BIT | TZBSP_VMID_RPM_BIT | TZBSP_VMID_WLAN_BIT,
   TZBSP_VMID_AP_BIT | TZBSP_VMID_RPM_BIT | TZBSP_VMID_WLAN_BIT,
   TZBSP_SNOC_CFG_RG_MSA_BLOCK_BASE, TZBSP_SNOC_CFG_RG_MSA_BLOCK_END},
};

/*
 * PMIC ARB Cfg RGs. Read/write access. Multi VMID
 */
static const tzbsp_mpu_rg_t g_rg_pmic_arb[] = {
  {TZBSP_SPMI_RG_CFG, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_CFG_BASE, TZBSP_SPMI_RG_CFG_END},
  {TZBSP_SPMI_RG_RPM_CH, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_CH_START, TZBSP_SPMI_RG_RPM_CH_END},
  {TZBSP_SPMI_RG_MSS_CH, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_CH_BASE, TZBSP_SPMI_RG_MSS_CH_END},
  {TZBSP_SPMI_RG_RO_CH, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),  0,
   TZBSP_SPMI_RG_RO_CH_BASE, TZBSP_SPMI_RG_RO_CH_END},
  {TZBSP_SPMI_RG_RPM_INT0, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT0_BASE, TZBSP_SPMI_RG_RPM_INT0_END},
  {TZBSP_SPMI_RG_MSS_INT0, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_INT0_BASE, TZBSP_SPMI_RG_MSS_INT0_END},
  {TZBSP_SPMI_RG_RPM_INT1, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE,
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT1_BASE, TZBSP_SPMI_RG_RPM_INT1_END},
  {TZBSP_SPMI_RG_RPM_INT2, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT2_BASE, TZBSP_SPMI_RG_RPM_INT2_END},
  {TZBSP_SPMI_RG_MSS_INT1, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_INT1_BASE, TZBSP_SPMI_RG_MSS_INT1_END},
  {TZBSP_SPMI_RG_RPM_INT3, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT3_BASE, TZBSP_SPMI_RG_RPM_INT3_END},
  {TZBSP_SPMI_RG_MSS_INT2, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_INT2_BASE, TZBSP_SPMI_RG_MSS_INT2_END},
  {TZBSP_SPMI_RG_RPM_INT5, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT5_BASE, TZBSP_SPMI_RG_RPM_INT5_END},
  {TZBSP_SPMI_RG_MSS_INT3, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_INT3_BASE, TZBSP_SPMI_RG_MSS_INT3_END},
  {TZBSP_SPMI_RG_RPM_INT6, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_INT6_BASE, TZBSP_SPMI_RG_RPM_INT6_END},
  {TZBSP_SPMI_RG_MSS_ACC, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), TZBSP_VMID_MSS_BIT,
   TZBSP_SPMI_RG_MSS_ACC_BASE, TZBSP_SPMI_RG_MSS_ACC_END},
  {TZBSP_SPMI_RG_RPM_ACC, TZBSP_XPU_ENABLE | TZBSP_XPU_NON_SEC | TZBSP_RWE, 
      (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), 0,
   TZBSP_SPMI_RG_RPM_ACC_BASE, TZBSP_SPMI_RG_RPM_ACC_END},
};


/**
 * QPIC BAM APU resource groups(multi VMID, full access/no access).
 * Pipe resources configured during BAM init
 */
 
static const tzbsp_rpu_rg_t g_rg_qpic_bam[] = {
  {TZBSP_QPIC_RG_BAM_CONTROL, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_BAM_DEBUG, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_BAM_TRUST, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_QPIC_RG_BAM_EE0, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  {TZBSP_QPIC_RG_BAM_EE1, TZBSP_XPU_MODEM_PROT, 0, 0},
  {TZBSP_QPIC_RG_BAM_EE2, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_QPIC_RG_BAM_EE3, TZBSP_XPU_SEC, 0, 0},
  {TZBSP_QPIC_RG_CFG, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_OPERATIONAL, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_SUPERVISOR, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT, TZBSP_VMID_AP_BIT | TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_PROTECTED, TZBSP_XPU_NON_SEC, TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT},
  {TZBSP_QPIC_RG_LCDc, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
  /* Delay locking of QPIC till milestone to enable Flash programmer */ 
  {TZBSP_QPIC_RG_OBSOLETE, TZBSP_XPU_NON_SEC, TZBSP_VMID_AP_BIT, TZBSP_VMID_AP_BIT},
/* MSS permission removed post boot milestone as this is needed by MBA*/
  {TZBSP_QPIC_RG_MPU_CONFIG, TZBSP_XPU_NON_SEC, TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT},
};

 static const tzbsp_mpu_rg_t g_rg_qpic[] = {
   {TZBSP_QPIC_NAND_RG_RPM, TZBSP_XPU_SEC, 0, 0, 0, 0},
   {TZBSP_QPIC_NAND_RG_MSS, TZBSP_XPU_SEC, 0, 0, 0, 0},
   {TZBSP_QPIC_NAND_RG_APPS, TZBSP_XPU_SEC, 0, 0, 0, 0},
   {TZBSP_QPIC_NAND_RG_EFS, TZBSP_XPU_MODEM_PROT, 0, 0, 0, 0},
 };



const tzbsp_xpu_cfg_t g_tzbsp_xpu_cfg[] = {
  {HAL_XPU2_BIMC_MPU0, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
  /*
   * Default permissions for unmapped area. Accessible to all except
   * Modem & CP
   * TODO: Revoke access to no access vmid once boot time bimc violation issue
   * is fixed
   * Revoke modem write access once MBA image with msa partition configuration
   * is available
   */
   
   /* TODO: Removed the access from the VENUS bit in unmapped region 
            Removed the VIDEO BIT for venus to load VENUS as  venus XPU is not enabled now 
             */
      ~(TZBSP_VMID_CP_BIT),
      ~( TZBSP_VMID_CP_BIT),
      ARRAY_SIZE(g_rg_ebi), g_rg_ebi},
    {HAL_XPU2_BAM_BLSP1_DMA, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_blsp1), g_rg_blsp1},
    {HAL_XPU2_BOOT_ROM, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    0, 0,
    ARRAY_SIZE(g_rg_bootrom), g_rg_bootrom},

    {HAL_XPU2_CLK_CTL, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for RPU */
    0, 0,
    ARRAY_SIZE(g_rg_gcc), g_rg_gcc},
    {HAL_XPU2_TCSR_REGS, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for RPU */
    0, 0,
    ARRAY_SIZE(g_rg_tcsr_reg), g_rg_tcsr_reg},
    {HAL_XPU2_CRYPTO0_BAM, TZBSP_XPU_ENABLE,
    /* Unmapped area permissions are don't care for RPU */
    0, 0,
    ARRAY_SIZE(g_rg_crypto0), g_rg_crypto0},
    {HAL_XPU2_DEHR, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_dehr), g_rg_dehr},
    /* MDSS APU enabled during restore syscall from HLOS */
    {HAL_XPU2_MPM2, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_mpm2_apu), g_rg_mpm2_apu},
    {HAL_XPU2_MSS, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_mss_apu), g_rg_mss_apu},
    {HAL_XPU2_IMEM_MPU, TZBSP_XPU_ENABLE,
    0, 0,
    ARRAY_SIZE(g_rg_sys_imem), g_rg_sys_imem},
    {HAL_XPU2_RPM_APU, TZBSP_XPU_ENABLE, 
    0, 0, 
    ARRAY_SIZE(g_rg_rpm_apu), g_rg_rpm_apu},
    {  HAL_XPU2_SEC_CTRL_APU, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_sec_ctrl), g_rg_sec_ctrl},
    {HAL_XPU2_SMMU_500_DIME_MPU, TZBSP_XPU_ENABLE,
    TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT, TZBSP_VMID_MSS_BIT | TZBSP_VMID_AP_BIT,
    ARRAY_SIZE(g_rg_smmu_dime), g_rg_smmu_dime},
    {HAL_XPU2_SMMU_500_GPS_MPU, TZBSP_XPU_ENABLE,
    TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT,
    ARRAY_SIZE(g_rg_smmu_gps), g_rg_smmu_gps},
    {HAL_XPU2_SMMU_500_QDSP_MPU, TZBSP_XPU_ENABLE,
    TZBSP_VMID_MSS_BIT, TZBSP_VMID_MSS_BIT,
    ARRAY_SIZE(g_rg_smmu_qdsp), g_rg_smmu_qdsp},
    {HAL_XPU2_SMMU_500_TCU_MPU, TZBSP_XPU_ENABLE,
     (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),  
     (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
    ARRAY_SIZE(g_rg_smmu), g_rg_smmu},
    {HAL_XPU2_TLMM, TZBSP_XPU_ENABLE,
     (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
    ARRAY_SIZE(g_rg_tlmm), g_rg_tlmm},
    /* Venus APU enabled during video subsystem bring up */
    {HAL_XPU2_MMSS_VENUS, 0,
    0, 0,
    ARRAY_SIZE(g_rg_venus), g_rg_venus},
    {HAL_XPU2_PRONTO, TZBSP_XPU_ENABLE,
    /* Unmapped area permissions are don't care for APU */
    0, 0,
    ARRAY_SIZE(g_rg_wlan), g_rg_wlan},
    {HAL_XPU2_PCNOC_CFG, TZBSP_XPU_ENABLE,
     (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
    ARRAY_SIZE(g_rg_pcnoc_cfg), g_rg_pcnoc_cfg},
    //{HAL_XPU2_PERIPH_SS_APU, TZBSP_XPU_ENABLE,
    {HAL_XPU2_PRNG_CFG, TZBSP_XPU_ENABLE,
    /* Unmapped area permissions are don't care for RPU */
    0, 0,
    ARRAY_SIZE(g_rg_periph_prng), g_rg_periph_prng},
    {HAL_XPU2_RPM_CFG, TZBSP_XPU_ENABLE, 
    0, 0, 
    ARRAY_SIZE(g_rg_rpm_cfg), g_rg_rpm_cfg},
    {HAL_XPU2_SNOC_CFG, TZBSP_XPU_ENABLE,
    (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
    ARRAY_SIZE(g_rg_snoc_cfg), g_rg_snoc_cfg},
    {HAL_XPU2_PMIC_ARB, TZBSP_XPU_ENABLE,
    (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK), (~(TZBSP_VMID_NOACCESS_BIT) & TZBSP_ALL_VMID_BMSK),
    ARRAY_SIZE(g_rg_pmic_arb), g_rg_pmic_arb},
    {HAL_XPU2_QPIC_QPIC, TZBSP_XPU_ENABLE | TZBSP_XPU_MODEM_PROT,
    /* Unmapped area permissions are don't care for APU */
     0xFFFF, 0xFFFF,
     ARRAY_SIZE(g_rg_qpic_bam), g_rg_qpic_bam},
    {HAL_XPU2_QPIC_QPIC_MPU, TZBSP_XPU_ENABLE|TZBSP_XPU_MODEM_PROT,
     0xffff, 0xffff,
     ARRAY_SIZE(g_rg_qpic), g_rg_qpic},
};

const uint32 g_tzbsp_xpu_cfg_count =
    sizeof(g_tzbsp_xpu_cfg) / sizeof(g_tzbsp_xpu_cfg[0]);
