#ifndef QDI_CONSTANTS_H
#define QDI_CONSTANTS_H

/*======================================================================
                        qurt_qdi_constants.h

GENERAL DESCRIPTION
    Predefined invocation methods for drivers.  

 EXTERNALIZED FUNCTIONS
  none

 INITIALIZATION AND SEQUENCING REQUIREMENTS
  none

 Copyright (c) 2009-2011
             by Qualcomm Technologies, Inc. All Rights Reserved.
 ======================================================================*/
/*======================================================================
 
 											 EDIT HISTORY FOR FILE
 
 	 This section contains comments describing changes made to the
 	 module. Notice that changes are listed in reverse chronological
 	 order.
 
 	$Header: //components/rel/core.mpss/3.5.c12.3/kernel/qurt_mba/install/MBAv5/include/qurt_qdi_constants.h#1 $ 
 	$DateTime: 2016/12/13 07:59:23 $ $Author: mplcsds1 $
 
 
  when 				who 		what, where, why
  ---------- 	--- 		------------------------------------------------
  2011-11-25 	Jack			Add Header file
 ======================================================================*/


/*
||  Method numbers used for QDI
||
||  Here is the intended grouping of method numbers for QDI
||   including future usage:
||
||   Method 0 should always be unused and not responded to by
||    any driver.
||   Methods 1 and 2 are reserved for name registration and
||    name lookup.
||   Methods 3 through 31 are reserved for POSIX-type operations
||    on open handles.
||   Methods 32 through 127 are reserved for the QDI infrastructure
||    and may be extended in the future to provide standard
||    driver debug services, management services, and system
||    notifications.
||   Methods 128 through 255 are reserved for the use of automatically
||    generated methods such as might be generated by an IDL (interface
||    definition language).  The infrastructure may be extended to
||    perform services on these methods based on information provided
||    by the IDL, such as automatic buffer validation, etc.  These
||    method numbers should not be used for any "ad hoc" methods.
||   Methods with number >= 256 are "private" method numbers which are
||    outside the scope of the QDI infrastructure.  Drivers which want
||    to generate and consume their own "ad hoc" methods are free to
||    use these method numbers as they wish.  The infrastructure will
||    not generate these method numbers or respond to them, but will
||    pass them on unmolested.
||
||   Note that all driver implementations *should* return a value of
||    -1 when called with an unsupported method.  The standard error
||    return value for POSIX APIs is -1, so we emulate that behavior
||    here.
*/

#define QDI_UNUSED              0
#define QDI_REGISTER_DEVNAME    1
#define QDI_OPEN                2
#define QDI_CLOSE               3
#define QDI_READ                4
#define QDI_WRITE               5
#define QDI_IOCTL               6
#define QDI_MMAP                7

#define QDI_THREAD_INIT         32

#define QDI_THREAD_ENTER_LOCAL          33
#define QDI_THREAD_LEAVE_LOCAL          34
#define QDI_THREAD_ENTER_TRUSTED        35
#define QDI_THREAD_LEAVE_TRUSTED        36
#define QDI_CLIENT_NEW_HANDLE_FROM_OBJ  37
#define QDI_CLIENT_RELEASE_HANDLE       38
#define QDI_CLIENT_COPYIN               39
#define QDI_CLIENT_COPYOUT              40
#define QDI_CLIENT_LOCK_BUFFER          41
#define QDI_CLIENT_USERMALLOC           42
#define QDI_CLIENT_USERFREE             43

#define QDI_PRIVATE             256  /* Method numbers beginning at 256
                                        are private method numbers which
                                        are device-specific and available
                                        for use by device implementors. */

/*
||  Permission bitmasks for use with qurt_qdi_lock_buffer()
||
||  These numbers are chosen to match the POSIX file
||   permission bitmasks.
*/

#define QDI_PERM_W              2
#define QDI_PERM_R              4
#define QDI_PERM_RW             6

#endif /* QDI_CONSTANTS_H */
