#ifndef __TZBSP_HWIO_PRNG_H__
#define __TZBSP_HWIO_PRNG_H__


/* PRNG Bagheera */
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC0_CFG_SHFT HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC0_CFG_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC0_CFG_BMSK HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC0_CFG_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR0_EN_SHFT      HWIO_PRNG_PRNG_LFSR_CFG_LFSR0_EN_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR0_EN_BMSK      HWIO_PRNG_PRNG_LFSR_CFG_LFSR0_EN_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC1_CFG_SHFT HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC1_CFG_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC1_CFG_BMSK HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC1_CFG_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR1_EN_SHFT      HWIO_PRNG_PRNG_LFSR_CFG_LFSR1_EN_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR1_EN_BMSK      HWIO_PRNG_PRNG_LFSR_CFG_LFSR1_EN_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC2_CFG_SHFT HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC2_CFG_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC2_CFG_BMSK HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC2_CFG_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR2_EN_SHFT      HWIO_PRNG_PRNG_LFSR_CFG_LFSR2_EN_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR2_EN_BMSK      HWIO_PRNG_PRNG_LFSR_CFG_LFSR2_EN_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC3_CFG_SHFT HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC3_CFG_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_RING_OSC3_CFG_BMSK HWIO_PRNG_PRNG_LFSR_CFG_RING_OSC3_CFG_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR3_EN_SHFT      HWIO_PRNG_PRNG_LFSR_CFG_LFSR3_EN_SHFT
#define HWIO_SEC_PRNG_LFSR_CFG_LFSR3_EN_BMSK      HWIO_PRNG_PRNG_LFSR_CFG_LFSR3_EN_BMSK
#define HWIO_SEC_PRNG_LFSR_CFG_OUT                HWIO_PRNG_PRNG_LFSR_CFG_OUT
#define HWIO_SEC_PRNG_CONFIG_OUT                  HWIO_PRNG_PRNG_CONFIG_OUT
#define HWIO_SEC_PRNG_CONFIG_PRNG_EN_SHFT         HWIO_PRNG_PRNG_CONFIG_PRNG_EN_SHFT
#define HWIO_SEC_PRNG_STATUS_IN                   HWIO_PRNG_PRNG_STATUS_IN
#define HWIO_SEC_PRNG_STATUS_DATA_AVAIL_BMSK      HWIO_PRNG_PRNG_STATUS_DATA_AVAIL_BMSK
#define HWIO_SEC_PRNG_DATA_OUT_IN                 HWIO_PRNG_PRNG_DATA_OUT_IN

#endif /* __TZBSP_HWIO_PRNG_H__ */
